import React,{useState} from 'react';
import {BookOpen,FileText,Search,Trophy} from 'lucide-react';
import {useApp} from '../../context.jsx';
import {PAPER_COLLECTIONS} from '../../learningCatalog.js';
import availability from '../../competitionPaperAvailability.json';
import {readStored} from '../../study.js';
import {storage} from '../../storage.js';
import {Button,External,Modal} from '../UI.jsx';
import Competitions from './Competitions.jsx';
import s from './ConnectedSchool.module.css';
const verified=new Set(availability.filter(p=>p.available&&!p.frame).map(p=>p.url));
const PAPERS=PAPER_COLLECTIONS.filter(c=>c.programme==='Competition').flatMap(c=>c.links.filter(l=>verified.has(l.url)).map((l,i)=>({id:c.id+'-'+i,title:c.title+' · '+l.title,collection:c.title,provider:c.provider,source:c.source,url:l.url,kind:/solutions|answers|marking/i.test(l.title)?'Solutions':'Paper'})));
export default function CompetitionHub(){const {route}=useApp(),papers=route.query.get('view')==='papers';return <div className={s.page}><nav className={s.tabs} aria-label="Competition sections"><a href="#/competitions" aria-current={!papers?'page':undefined}><Trophy size={14}/> Competitions & training</a><a href="#/competitions?view=papers" aria-current={papers?'page':undefined}><BookOpen size={14}/> Past paper library</a></nav>{papers?<PaperLibrary/>:<Competitions/>}</div>;}
function PaperLibrary(){const{route}=useApp(),[query,setQuery]=useState(route.query.get('q')||''),[kind,setKind]=useState('all'),[limit,setLimit]=useState(30),[selected,setSelected]=useState(null);const visible=PAPERS.filter(p=>(kind==='all'||p.kind===kind)&&(p.title+' '+p.provider).toLowerCase().includes(query.toLowerCase()));return <section className={s.page}><header className={s.heading}><div><span className={s.eyebrow}>OFFICIAL PAPERS & SOLUTIONS</span><h1>Competition paper library</h1><p>{PAPERS.length} available PDFs to open in the website. Use the paper first, then compare with its solutions.</p></div></header><div className={s.filters}><label className={s.search}><Search size={17}/><input aria-label="Search competition papers" value={query} onChange={e=>{setQuery(e.target.value);setLimit(30);}} placeholder="Contest, year or grade…"/></label><select aria-label="Paper type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Papers and solutions</option><option value="Paper">Question papers</option><option value="Solutions">Solutions</option></select></div><p className={s.muted}>{visible.length} matching documents · Availability checked 4 October 2026</p><div className={s.grid}>{visible.slice(0,limit).map(p=><article className={`${s.panel} ${s.examCard}`} key={p.id}><FileText size={24}/><span className={s.eyebrow}>{p.provider} · {p.kind}</span><h3>{p.title}</h3><Button variant="secondary" onClick={()=>setSelected(p)}>Read here <BookOpen size={15}/></Button></article>)}</div>{visible.length>limit&&<Button variant="secondary" onClick={()=>setLimit(n=>n+30)}>Show more papers</Button>}{!visible.length&&<p className={s.empty}>No papers match. Try a contest name such as Gauss, Euclid, Pascal or BCC.</p>}<p className={s.muted}>The embedded documents load from their official publishers. This is the available Aster collection, not every competition paper ever published.</p><div className={s.actions}><External href="https://cemc.uwaterloo.ca/resources/past-contests">Waterloo contest archive</External><External href="https://ukmt.org.uk/competition-papers">UKMT free papers & solutions</External></div>{selected&&<PaperReader key={selected.id} paper={selected} onClose={()=>setSelected(null)}/>}</section>;}
function PaperReader({paper,onClose}){const key='aster-paper-notes-v1',[notes,setNotes]=useState(()=>readStored(key,{})[paper.id]||''),[error,setError]=useState('');function saveNotes(value){setNotes(value);try{storage.setItem(key,JSON.stringify({...readStored(key,{}),[paper.id]:value}));setError('');}catch{setError('Notes could not be saved. Copy them before closing.');}}return <Modal title={paper.title} onClose={onClose} size="large"><div className={s.reader}><iframe title={paper.title} src={paper.url+'#view=FitH'} referrerPolicy="no-referrer"/><p className={s.muted}>Use the PDF controls for pages and zoom. If your browser cannot display the PDF, open the publisher’s original.</p><External href={paper.url}>Open official PDF</External><label className={s.practice}>Your working notes<textarea aria-label="Paper working notes" value={notes} maxLength={10000} onChange={e=>saveNotes(e.target.value)} placeholder="Record question numbers, mistakes and strategies…"/></label>{error&&<p role="alert">{error}</p>}</div></Modal>;}
