import React,{lazy,Suspense,useState} from 'react';
import {useApp} from '../../context.jsx';
import {useSchool} from '../../schoolContext.jsx';
import {schoolDay} from '../../schoolSync.js';
import AssessmentPractice from './AssessmentPractice.jsx';
import {TodayClasses,SchoolResources,ConnectionStatus} from './SchoolConnection.jsx';
import s from './ConnectedSchool.module.css';
const LegacySchoolHub=lazy(()=>import('./SchoolHub.jsx'));
const ExamCoach=lazy(()=>import('../curriculum/ExamCoach.jsx'));
export default function ConnectedSchoolHub(){const {route,now}=useApp(),school=useSchool(),tab=route.query.get('tab')||'assessments',[date,setDate]=useState(schoolDay(now)),[error,setError]=useState('');return <div className={s.page}><header className={s.heading}><div><span className={s.eyebrow}>ISR · YOUR SCHOOL INFORMATION</span><h1>School</h1><p>Your assessments, timetable, resources and results.</p></div><a href="#/planner">Open the full calendar</a></header><nav className={s.tabs} aria-label="School sections">{[['assessments','Assessments & topics'],['schedule','Timetable'],['resources','Resources'],['photos','Exam photos'],['grades','Grades'],['news','School updates']].map(([key,label])=><a href={'#/school?tab='+key} key={key} aria-current={tab===key?'page':undefined}>{label}</a>)}</nav><Suspense fallback={<p>Opening school tools…</p>}>{['grades','news'].includes(tab)?<LegacySchoolHub key={tab} initialTab={tab} embedded/>:tab==='schedule'?<><label className={s.filters}>Choose a date <input type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><TodayClasses date={date} allowNext={false}/><ConnectionStatus/></>:tab==='resources'?<SchoolResources embedded/>:tab==='photos'?<ExamCoach/>:<AssessmentPractice/>}</Suspense><details className={s.outline}><summary>School connection & import details</summary><p>{school.coverage?.pages||0} school pages checked · {school.resources.length} resources · {school.assessments.length} assessments · {school.events.length} calendar entries.</p><p>School data and the private calendar feed stay on this computer. This catalogue lists the accessible materials; it does not imply every linked slide has been read.</p><p>{school.sync?.scheduleLabel||'Course resources and assessment guides update when a new school import is available.'}</p>{school.error&&<p>{school.error}</p>}<label>Import a saved school snapshot <input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{await school.importSnapshot(file);setError('');}catch(err){setError(err.message);}e.target.value='';}}/></label>{error&&<p role="alert">{error}</p>}</details></div>;}
