import React,{useState} from 'react';
import {RefreshCw,FileText,Presentation,ArrowUpRight,Clock3,CalendarDays,BookOpen,Search} from 'lucide-react';
import {useSchool} from '../../schoolContext.jsx';
import {useApp} from '../../context.jsx';
import {COURSES} from '../../study.js';
import {schoolDay,schoolTime,eventsForDay,examStatus,orderedAssessments,safeSchoolUrl} from '../../schoolSync.js';
import {Button,Modal,External} from '../UI.jsx';
import s from './ConnectedSchool.module.css';
export function ConnectionStatus(){const school=useSchool(),[busy,setBusy]=useState(false);return <div className={s.status}><span>{school.loading?'Loading school information…':school.checkedAt?`Course information checked ${new Date(school.checkedAt).toLocaleString('en-GB',{timeZone:'Europe/Berlin',dateStyle:'medium',timeStyle:'short'})}`:'No school import yet'}</span>{school.local&&<span>Calendar refreshes every 15 minutes while Aster is running</span>}<button disabled={busy} onClick={async()=>{setBusy(true);await school.refresh(true);setBusy(false);}}><RefreshCw size={12}/>{busy?'Checking…':'Refresh calendar & import'}</button>{school.calendarError&&<span role="status">{school.calendarError}</span>}{school.sync?.error&&<span role="status">{school.sync.error}</span>}</div>;}
export function TodayClasses({date,allowNext=true}){
 const {events,loading,checkedAt}=useSchool(),{now}=useApp();const today=date||schoolDay(now),closed=eventsForDay(events,today).find(e=>e.schoolClosed),classes=eventsForDay(events,today).filter(e=>e.kind==='class'),next=events.find(e=>e.kind==='class'&&e.date>today),showNext=allowNext&&!classes.length&&next,visible=showNext?eventsForDay(events,next.date).filter(e=>e.kind==='class'):classes;
 return <section className={s.schoolToday} aria-label="Today’s classes"><header className={s.heading}><div><span className={s.eyebrow}>{new Date(today+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</span><h2>{date&&date!==schoolDay(now)?'Classes for this day':'Today’s classes'}</h2>{!classes.length&&!loading&&<p>{closed?closed.title+'.':checkedAt?'No classes listed in your imported timetable for this day.':'Connect your school timetable to see your classes.'}{showNext&&` Next school day: ${new Date(next.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'})}.`}</p>}</div><a href={'#/planner?day='+today}>Open calendar <ArrowUpRight size={14}/></a></header>{loading&&!checkedAt?<p className={s.muted}>Reading your timetable…</p>:<div className={s.classList}>{visible.map(c=><a className={s.classCard} href={'#/subjects/'+c.subject} key={c.id} data-current={!showNext&&Date.parse(c.start)<=now&&Date.parse(c.end)>now} data-ended={!showNext&&Date.parse(c.end)<now}><time>{schoolTime(c.start)}–{schoolTime(c.end)}</time><strong>{COURSES[c.subject]?.name||c.title}</strong><small>{c.location?'Room '+c.location:'Room not provided'}</small></a>)}</div>}</section>;
}
export function SchoolDocument({documentId,onClose}){const {documents,local}=useSchool(),doc=documents.find(d=>d.id===documentId);return <Modal title={doc?.title||'School document'} onClose={onClose} size="large"><div className={s.reader}>{doc&&local?(doc.type==='pdf'?<iframe title={doc.title} src={'/api/local-school/files/'+doc.id}/>:doc.type==='png'?<img alt={doc.title} src={'/api/local-school/files/'+doc.id}/>:doc.text?<pre>{doc.text}</pre>:<a className="button button-primary" href={'/api/local-school/files/'+doc.id} download>Download original document</a>):<p>This document is available through the school portal.</p>}{doc&&<External href={safeSchoolUrl(doc.source)}>Open the teacher’s original</External>}</div></Modal>;}
export function SchoolResources({subject,embedded=false}){
 const school=useSchool(),[query,setQuery]=useState(''),[filter,setFilter]=useState(subject||'all'),[branch,setBranch]=useState('all'),[kind,setKind]=useState('all'),[grade,setGrade]=useState('8'),[limit,setLimit]=useState(40),[doc,setDoc]=useState(null);
 const visible=school.resources.filter(r=>(subject||filter==='all'||r.subject===filter)&&(subject?r.subject===subject:true)&&(branch==='all'||r.branch===branch)&&(kind==='all'||r.kind===kind)&&(grade==='all'||String(r.grade)===grade)&&`${r.title} ${r.unit} ${r.branch}`.toLowerCase().includes(query.toLowerCase()));
 return <section className={s.page}>{!embedded&&<header className={s.heading}><div><span className={s.eyebrow}>YOUR TEACHERS’ MATERIALS</span><h1>Course resources</h1><p>Slides, worksheets and assessment guides from your enrolled classes.</p></div></header>}<ConnectionStatus/><div className={s.filters}><label className={s.search}><Search size={16}/><input aria-label="Search school resources" placeholder="Search a topic, worksheet or PowerPoint…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40);}}/></label>{!subject&&<select aria-label="Resource subject" value={filter} onChange={e=>{setFilter(e.target.value);setLimit(40);}}><option value="all">All subjects</option>{Object.entries(COURSES).map(([id,c])=><option key={id} value={id}>{c.name}</option>)}</select>}<select aria-label="Science branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">All branches</option>{['Biology','Chemistry','Physics'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Resource format" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All formats</option>{['Slides','PDF','Worksheet','Resource'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Resource grade" value={grade} onChange={e=>setGrade(e.target.value)}><option value="8">Grade 8</option><option value="all">Include previous years</option></select></div><p className={s.muted}>{visible.length} resources · {school.resources.length} in the imported catalogue</p><div className={s.resourceList}>{visible.slice(0,limit).map(r=><article className={s.resourceRow} key={r.id}>{r.kind==='Slides'?<Presentation size={21}/>:<FileText size={21}/>}<div><h3>{r.title}</h3><p>{COURSES[r.subject]?.name} · {r.branch?`${r.branch} · `:''}{r.unit} · {r.kind}</p></div>{r.documentId&&school.local?<button className="text-link" onClick={()=>setDoc(r.documentId)}>Read here <BookOpen size={14}/></button>:null}<External className="text-link" href={r.url}>Open original <ArrowUpRight size={13}/></External></article>)}</div>{visible.length>limit&&<Button variant="secondary" onClick={()=>setLimit(n=>n+40)}>Show more resources</Button>}{!visible.length&&<p className={s.empty}>{school.loading?'Loading resources…':'No resources match these filters.'}</p>}{school.coverage?.blocked?.length>0&&<p className={s.muted}>{school.coverage.blocked.length} linked school pages require additional permission. Their contents are not included.</p>}{doc&&<SchoolDocument documentId={doc} onClose={()=>setDoc(null)}/>}</section>;
}
export function UpcomingExams({subject,limit=4}){const {assessments}=useSchool(),{now}=useApp(),upcoming=orderedAssessments(assessments,subject,now).filter(a=>['today','upcoming'].includes(examStatus(a,now))).slice(0,limit);return <section className={s.page}><header className={s.heading}><div><span className={s.eyebrow}>ASSESSMENT CALENDAR</span><h2>Coming up</h2></div><a href={subject?`#/subjects/${subject}?tab=exams`:'#/school?tab=assessments'}>All assessments</a></header><div className={s.grid}>{upcoming.map(a=><a className={`${s.panel} ${s.subjectCard}`} key={a.id} href={`#/subjects/${a.subject}?tab=exams&exam=${a.id}`}><div className={s.examMeta}><span className={s.badge} data-status={examStatus(a,now)}>{examStatus(a,now)==='today'?'Today':new Date(a.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span><span className={s.eyebrow}>{COURSES[a.subject]?.name}</span></div><h3>{a.title}</h3>{a.dateConflict&&<p className={s.muted}>Dates differ: {a.alternateDates.map(d=>d.date).join(", ")} in Schoolbox; {a.date} in Veracross. Open to check.</p>}<p className={s.muted}>{a.topics.length?`${a.topics.length} published topics · Open your practice`:'Date confirmed · Waiting for the specific assessment topics'}</p></a>)}</div>{!upcoming.length&&<p className={s.empty}>No upcoming assessments published in the current import{subject?' for this subject':''}.</p>}</section>;}
