import React,{lazy,Suspense,useState} from 'react';
import {ArrowRight,BookOpen,CalendarDays,Layers3,Pin,Search,Target} from 'lucide-react';
import {useApp} from '../../context.jsx';
import {useSchool} from '../../schoolContext.jsx';
import {COURSES,SUBJECT_ORDER} from '../../study.js';
import {orderedAssessments,examStatus} from '../../schoolSync.js';
import {Button,SubjectIcon,TaskRow,External} from '../UI.jsx';
import {MainTree} from '../neon/MainTree.jsx';
import {SchoolResources,UpcomingExams} from './SchoolConnection.jsx';
import AssessmentPractice from './AssessmentPractice.jsx';
import FullTopicMap from './TopicMaps.jsx';
import s from './ConnectedSchool.module.css';
const RevisionCentre=lazy(()=>import('../revision/RevisionCentre.jsx'));
const Comprehension=lazy(()=>import('../curriculum/Comprehension.jsx'));
export function ConnectedSubjects(){
 const {prefs,route,now}=useApp(),{resources,assessments}=useSchool(),[query,setQuery]=useState(''),[pinned,setPinned]=useState(false),[pathSubject,setPathSubject]=useState('maths');const path=route.query.get('view')==='path';
 const visible=SUBJECT_ORDER.filter(id=>(!pinned||prefs.pinned.includes(id))&&COURSES[id].name.toLowerCase().includes(query.toLowerCase()));
 return <div className={s.page}><header className={s.heading}><div><span className={s.eyebrow}>YOUR ISR CLASSES</span><h1>My subjects</h1><p>Everything for a subject stays together: resources, exam practice, revision and your learning path.</p></div></header><nav className={s.tabs} aria-label="My subjects views"><a href="#/subjects" aria-current={!path?'page':undefined}>Subjects</a><a href="#/subjects?view=path" aria-current={path?'page':undefined}>Learning path</a></nav>{path?<><label className={s.filters}>Subject <select value={pathSubject} onChange={e=>setPathSubject(e.target.value)}>{SUBJECT_ORDER.map(id=><option key={id} value={id}>{COURSES[id].name}</option>)}</select></label><SubjectPath key={pathSubject} subject={pathSubject}/></>:<><div className={s.filters}><label className={s.search}><Search size={17}/><input aria-label="Search subjects" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a subject…"/></label><Button variant="secondary" aria-pressed={pinned} onClick={()=>setPinned(v=>!v)}><Pin size={15}/>{pinned?'Pinned subjects':'All subjects'}</Button></div><div className={s.grid}>{visible.map(id=>{const c=COURSES[id],next=orderedAssessments(assessments,id,now).find(a=>examStatus(a,now)!=='past'),count=resources.filter(r=>r.subject===id).length;return <a key={id} href={'#/subjects/'+id} className={`${s.panel} ${s.subjectCard}`}><SubjectIcon id={id} size={25}/><h2>{c.name}</h2><span className={s.muted}>{count} school resources</span><div className={s.nextExam}>{next?<><CalendarDays size={13}/> {new Date(next.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · {next.title}</>:'No upcoming exam published'}</div><span className={s.muted}>Open subject <ArrowRight size={12}/></span></a>;})}</div>{!visible.length&&<p className={s.empty}>No matching subjects.</p>}</>}</div>;
}
export function ConnectedSubject({id}){
 const {route,prefs,setPrefs,homework,navigate}=useApp(),{resources,subjects}=useSchool(),course=COURSES[id];const tabs=[['overview','Overview'],['exams','Exam practice'],['resources','Resources'],['path','Learning path'],['practice','Quick review'],['revision','Revision centre'],['mindmap','Topic mind maps'],['notes','Notes'],...(id==='english'?[['english','English practice']]:[])];const tab=tabs.some(([key])=>key===route.query.get('tab'))?route.query.get('tab'):'overview';
 if(!course)return <p className={s.empty}>Choose a subject from My subjects.</p>;
 const pinned=prefs.pinned.includes(id),tasks=homework.filter(t=>t.course===id&&!t.done),source=subjects.find(c=>c.id===id)?.url||course.source;
 return <div className={s.page}><a className={s.back} href="#/subjects">← My subjects</a><header className={s.heading}><div><span className={s.eyebrow}>GRADE 8 · {course.code}</span><h1>{course.name}</h1><p>{resources.filter(r=>r.subject===id).length} school resources · {tasks.length} open tasks</p></div><div className={s.actions}><External href={source}>Schoolbox classroom</External><Button variant="secondary" aria-pressed={pinned} onClick={()=>setPrefs(p=>({...p,pinned:pinned?p.pinned.filter(v=>v!==id):[...p.pinned,id]}))}><Pin size={14}/>{pinned?'Pinned':'Pin subject'}</Button></div></header><nav className={s.tabs} aria-label={course.name+' sections'}>{tabs.map(([key,label])=><a key={key} href={`#/subjects/${id}?tab=${key}`} aria-current={key===tab?'page':undefined}>{label}</a>)}</nav><Suspense fallback={<p>Opening {course.name} tools…</p>}>
 {tab==='overview'&&<><UpcomingExams subject={id} limit={2}/><div className={s.grid}>{[['exams','Prepare for your next exam','Use the actual assessment topics and date.'],['resources','From your teacher','Open lesson slides, worksheets and revision guides.'],['mindmap','See the whole topic','Explore how concepts fit together.']].map(([view,title,description])=><a key={view} href={`#/subjects/${id}?tab=${view}`} className={`${s.panel} ${s.subjectCard}`}><h3>{title}</h3><p className={s.muted}>{description}</p><ArrowRight size={17}/></a>)}</div><section><h2>Homework</h2>{tasks.length?<div className="task-list-card">{tasks.map(t=><TaskRow key={t.id} task={t}/>)}</div>:<p className={s.muted}>No open tasks for this subject.</p>}</section></>}
 {tab==='exams'&&<AssessmentPractice key={id} subject={id}/>}{tab==='resources'&&<SchoolResources key={id} subject={id} embedded/>}{tab==='path'&&<SubjectPath key={id} subject={id}/>}{tab==='practice'&&<SubjectQuickReview key={id} subject={id}/>}{tab==='revision'&&<RevisionCentre key={id} subject={id} embedded/>}{tab==='mindmap'&&<FullTopicMap key={id} subject={id}/>}{tab==='english'&&<Comprehension/>}{tab==='notes'&&<><h2>Saved course notes</h2><p className={s.muted}>Learnify reference notes. The assessment topic list determines what to revise for each exam.</p><div className={s.grid}>{course.notes.map(([title,text])=><article className={s.panel} key={title}><h3>{title}</h3><p>{text}</p></article>)}</div>{!course.notes.length&&<p className={s.empty}>Use the teacher resources for this subject’s notes.</p>}</>}
 </Suspense></div>;
}
function SubjectPath({subject}){const{progress,openLesson,navigate}=useApp(),course=COURSES[subject];return <section className={s.page}><div className={s.heading}><div><h2>{course.name} learning path</h2><p>Build recall, practise, match ideas and complete a checkpoint.</p></div><a href={`#/subjects/${subject}?tab=exams`}>Follow your exam revision route</a></div><MainTree course={course} completed={progress.paths?.[subject]||[]} onStart={i=>openLesson(subject,i)} onResources={()=>navigate(`subjects/${subject}?tab=resources`)}/></section>;}
function SubjectQuickReview({subject}){const{setReview,setCards,setMatch}=useApp(),c=COURSES[subject];return <section className={`${s.panel} ${s.page}`}><header><span className={s.eyebrow}>GENERAL SUBJECT PRACTICE</span><h2>{c.name} quick review</h2><p className={s.muted}>Choose a short session, flashcards or concept matching. For a specific exam, use Exam practice.</p></header><div className={s.examTopics}>{[...new Set(c.questions.map(q=>q.topic))].map(t=><span key={t}>{t}</span>)}</div><div className={s.actions}><Button onClick={()=>setReview(subject)}><Target size={16}/>Start quick review</Button><Button variant="secondary" onClick={()=>setCards(subject)}><BookOpen size={16}/>Flashcards</Button><Button variant="secondary" onClick={()=>setMatch(subject)}><Layers3 size={16}/>Match concepts</Button></div></section>;}
