import React,{useEffect,useState} from 'react';
import {Play,Pause,RotateCcw,Plus} from 'lucide-react';
import {EXTRA_LABS,buoyancy,refract,gasPressure,photosynthesisRate,enzymeRate,reactionProduct,diffusionMix} from '../../moreScience.js';
import {storage} from '../../storage.js';
import {readStored} from '../../study.js';
import s from './Science.module.css';

function Plot({fn,maxX=100,maxY=100,xLabel='Time',yLabel='Relative rate',marker}){
 const points=Array.from({length:101},(_,i)=>`${60+i*5.1},${285-Math.max(0,Math.min(maxY,fn(i*maxX/100)))/maxY*215}`).join(' ');
 return <><path d="M60 55V285H580" fill="none" stroke="#7992a5" strokeWidth="2"/>{[0,1,2,3,4].map(i=><g key={i}><path d={`M60 ${285-i*53.75}H575`} stroke="#849cb021"/><text x="49" y={290-i*53.75} textAnchor="end" fontSize="11">{Math.round(maxY*i/4)}</text><text x={60+i*127.5} y="307" textAnchor="middle" fontSize="11">{(maxX*i/4).toFixed(1).replace('.0','')}</text></g>)}<polyline points={points} fill="none" stroke="#528c7b" strokeWidth="4"/><text x="320" y="336" textAnchor="middle" fontSize="12">{xLabel}</text><text x="65" y="35" fontSize="13">{yLabel}</text>{marker!==undefined&&<circle cx={60+marker/maxX*510} cy={285-fn(marker)/maxY*215} r="7" fill="#c2865e" stroke="white" strokeWidth="2"/>}</>;
}
function Visual({id,v,calm}){
 if(id==='photosynthesis')return <Plot fn={x=>photosynthesisRate(x,v.co2,v.temperature)} maxX={300} xLabel="Light intensity (relative units)" yLabel="Photosynthesis rate (%)" marker={v.light}/>;
 if(id==='enzymes')return <Plot fn={x=>enzymeRate(x,v.ph)} maxX={80} xLabel="Temperature (°C)" yLabel="Enzyme activity (%)" marker={v.temperature}/>;
 if(id==='reaction-rate')return <Plot fn={x=>reactionProduct(x,v.concentration,v.temperature,v.surface)} maxX={120} xLabel="Time (s)" yLabel="Product formed (%)" marker={v.seconds}/>;
 if(id==='gas'){const height=v.volume/600*225,top=300-height;return <><rect x="175" y="50" width="250" height="250" fill="#f6fafc" stroke="#7191a5" strokeWidth="3"/><rect x="178" y={top} width="244" height={height} fill="#c7dee6"/><rect x="170" y={top-12} width="260" height="16" rx="4" fill="#809eab"/><path d={`M300 ${top-12}V20`} stroke="#77939e" strokeWidth="12"/>{Array.from({length:25},(_,i)=><circle key={i} cx={195+(i*67%210)} cy={top+12+(i*43%190)/190*Math.max(5,height-24)} r="4" fill="#6c92a4"/>)}<text x="300" y="335" textAnchor="middle" fontSize="18">{gasPressure(v.volume).toFixed(1)} kPa · {v.volume} mL</text></>;}
 if(id==='buoyancy'){const b=buoyancy(v.mass,v.volume,v.liquid),y=b.floats?155-75*(1-b.fraction):b.neutral?175:230;return <><path d="M100 50V310h450V50" fill="none" stroke="#7596aa" strokeWidth="4"/><rect x="102" y="155" width="446" height="152" fill="#badbe7"/><line x1="102" x2="548" y1="155" y2="155" stroke="#70a7b6" strokeWidth="3"/><rect x="260" y={y} width="110" height="75" rx="9" fill="#cfa477" stroke="#9f795b" strokeWidth="2"/><path d={`M315 ${y+28}v40m-8-10 8 10 8-10`} fill="none" stroke="#80543f" strokeWidth="3"/><text x="325" y="45" textAnchor="middle" fontSize="18">{b.floats?'Floating':b.neutral?'Neutrally buoyant':'Sinking'}</text><text x="325" y="338" textAnchor="middle" fontSize="14">Object density: {b.density.toFixed(2)} g/cm³</text></>;}
 if(id==='refraction'){const r=refract(v.angle,v.n1,v.n2),rad=v.angle*Math.PI/180,x=325-Math.sin(rad)*145,y=175-Math.cos(rad)*145,theta=(r.angle||0)*Math.PI/180;return <><rect x="40" y="25" width="570" height="150" fill="#e5eef1"/><rect x="40" y="175" width="570" height="150" fill="#bdd4e3"/><path d="M40 175H610M325 30V325" stroke="#718ca2" strokeDasharray="4 6"/><path d={`M${x} ${y}L325 175L${r.totalInternalReflection?325+Math.sin(rad)*145:325+Math.sin(theta)*145} ${r.totalInternalReflection?y:175+Math.cos(theta)*145}`} fill="none" stroke="#d29b53" strokeWidth="4"/><circle cx="325" cy="175" r="5" fill="#b26e3f"/><text x="60" y="53" fontSize="15">n₁ = {v.n1.toFixed(2)}</text><text x="60" y="308" fontSize="15">n₂ = {v.n2.toFixed(2)}</text><text x="325" y="346" textAnchor="middle" fontSize="14">{r.totalInternalReflection?'Total internal reflection':'Refraction angle: '+r.angle.toFixed(1)+'°'}</text></>;}
 if(id==='waves'){const wave=x=>175-v.amplitude*90*Math.sin(2*Math.PI*(x/v.speed*v.frequency-v.frequency*v.time));return <><path d="M50 175H600M50 50V295" stroke="#7f98a9" strokeDasharray="4 6"/><polyline points={Array.from({length:241},(_,i)=>`${50+i*550/240},${wave(i*12/240)}`).join(' ')} fill="none" stroke="#648f9b" strokeWidth="3"/><circle cx="50" cy={wave(0)} r="7" fill="#c18a62"/>{[0,3,6,9,12].map(x=><text key={x} x={50+x/12*550} y="316" textAnchor="middle" fontSize="12">{x} m</text>)}<text x="325" y="40" textAnchor="middle" fontSize="17">λ = v / f = {(v.speed/v.frequency).toFixed(2)} m</text><text x="325" y="344" textAnchor="middle" fontSize="12">Displacement vs distance · {v.time.toFixed(1)} s</text></>;}
 const mix=diffusionMix(v.seconds,v.temperature);return <><rect x="65" y="55" width="520" height="240" rx="12" fill="#f6fafb" stroke="#8aa4b4" strokeWidth="2"/><path d="M325 55V295" stroke="#a2b6bd" strokeDasharray="5 7" opacity={1-mix}/>{Array.from({length:64},(_,i)=>{const side=i<32?0:1,n=i%32,initial=80+side*260+(n*47%230),target=80+(i*131%490),x=initial*(1-mix)+target*mix,y=75+(i*59%195);return <circle key={i} cx={x} cy={y} r="5" fill={side?'#ae8ba9':'#5d9b98'} className={!calm&&v.seconds>0?s.diffusionParticle:undefined} style={{animationDelay:-i*.1+'s'}}/>;})}<text x="325" y="330" textAnchor="middle" fontSize="16">Mixing progress in this model: {Math.round(mix*100)}%</text></>;
}
function result(id,v){if(id==='photosynthesis')return photosynthesisRate(v.light,v.co2,v.temperature).toFixed(1)+'% relative rate';if(id==='enzymes')return enzymeRate(v.temperature,v.ph).toFixed(1)+'% activity';if(id==='reaction-rate')return reactionProduct(v.seconds,v.concentration,v.temperature,v.surface).toFixed(1)+'% product';if(id==='diffusion')return Math.round(diffusionMix(v.seconds,v.temperature)*100)+'% mixed';if(id==='gas')return gasPressure(v.volume).toFixed(1)+' kPa';if(id==='waves')return (v.speed/v.frequency).toFixed(2)+' m wavelength';if(id==='refraction'){const r=refract(v.angle,v.n1,v.n2);return r.totalInternalReflection?'Total internal reflection':r.angle.toFixed(1)+'° refracted angle';}const b=buoyancy(v.mass,v.volume,v.liquid);return b.floats?Math.round(b.fraction*100)+'% submerged':b.neutral?'Neutrally buoyant':'Sinks';}
export default function MoreScience({id,calm}){
 const lab=EXTRA_LABS.find(l=>l.id===id),[v,setV]=useState(lab.defaults),[running,setRunning]=useState(false),[notes,setNotes]=useState(()=>readStored('aster-lab-notes-v1',{})[id]||''),[trials,setTrials]=useState([]),[error,setError]=useState('');
 const timeKey=id==='waves'?'time':'seconds',animated=['waves','diffusion','reaction-rate'].includes(id),max=lab.sliders.find(a=>a[0]===timeKey)?.[3]||10;
 useEffect(()=>{if(!running||calm)return;const timer=setInterval(()=>setV(old=>({...old,[timeKey]:Math.min(max,Number((old[timeKey]+(id==='waves'?.1:1)).toFixed(1)))})),id==='waves'?100:200);return()=>clearInterval(timer);},[running,calm,id,max,timeKey]);
 useEffect(()=>{if(v[timeKey]>=max)setRunning(false);},[v,timeKey,max]);
 function save(value){setNotes(value);try{storage.setItem('aster-lab-notes-v1',JSON.stringify({...readStored('aster-lab-notes-v1',{}),[id]:value}));setError('');}catch{setError('Notes could not be saved. Copy them before leaving.');}}
 return <><div className={s.experiment}><div className={s.benchColumn}><div className={s.bench}><svg viewBox="0 0 650 360" className={s.circuit} role="img" aria-label={lab.name+': '+result(id,v)} fill="currentColor"><Visual id={id} v={v} calm={calm}/></svg></div><div className={s.benchButtons}>{animated&&<button onClick={()=>{if(calm)setV(old=>({...old,[timeKey]:Math.min(max,old[timeKey]+1)}));else{if(v[timeKey]>=max)setV(old=>({...old,[timeKey]:0}));setRunning(!running);}}}>{running?<Pause size={15}/>:<Play size={15}/>} {calm?'Advance one step':running?'Pause':'Run experiment'}</button>}<button onClick={()=>{setV(lab.defaults);setRunning(false);}}><RotateCcw size={15}/>Reset experiment</button><button onClick={()=>setTrials(old=>[...old,{values:{...v},result:result(id,v)}].slice(-8))}><Plus size={15}/>Record trial</button></div><p className={s.caption}>{lab.note}</p></div><aside className={s.controls}><h3>{lab.name}</h3>{lab.sliders.map(([key,label,min,max,step,unit])=><label key={key} className={s.slider}><span>{label}<output>{v[key]} {unit}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={v[key]} onChange={e=>{setRunning(false);setV(old=>({...old,[key]:Number(e.target.value)}));}}/></label>)}<div className={s.result} aria-live="polite"><span>Model result</span><strong style={{fontSize:26}}>{result(id,v)}</strong></div><p><strong>Try an investigation</strong><br/>{lab.question}</p></aside></div><section className={s.labNotebook}><h3>Predict, test, explain</h3><p>Change one variable at a time, record your trials, and explain the pattern.</p>{trials.length>0&&<div className={s.trialScroll}><table><caption>Latest {trials.length} trials in this session</caption><thead><tr><th>Trial</th>{lab.sliders.map(([key,label])=><th key={key}>{label}</th>)}<th>Result</th></tr></thead><tbody>{trials.map((t,i)=><tr key={i}><th>{i+1}</th>{lab.sliders.map(([key])=><td key={key}>{t.values[key]}</td>)}<td>{t.result}</td></tr>)}</tbody></table></div>}<label>Your prediction and conclusion<textarea aria-label="Experiment notes" maxLength={2500} value={notes} onChange={e=>save(e.target.value)} placeholder="I predict… I changed… I noticed… This happens because…"/></label>{error&&<p role="alert">{error}</p>}</section></>;
}
