import {GAME_TICKET} from '../../economy.js';
import React,{useEffect,useRef,useState} from 'react';import {Car,Orbit,Footprints,Grid2X2,Hash,ArrowLeft,ArrowRight,ArrowUp,ArrowDown,Play,Pause,RotateCcw,Heart,Trophy,Star} from 'lucide-react';
import {useApp} from '../../context.jsx';import {useT} from '../../i18n.jsx';import {COURSES,makeQuiz,readStored} from '../../study.js';import {storage} from '../../storage.js';import {freshGame,stepGame,move2048,spawnTile,canMove2048,SUDOKU_PUZZLE,SUDOKU_SOLUTION,sudokuConflicts,sudokuSolved} from '../../gameLogic.js';import {Modal,Button} from '../UI.jsx';import {ReviewBoundary} from '../neon/ReviewBoundary.jsx';import s from './Games.module.css';
const MODES=[['racer','Neon Drift','Dodge traffic. Collect stars. Own the road.',Car,'#66b8f0'],['space','Orbit Defender','Pilot your ship through a field of falling asteroids.',Orbit,'#b59bea'],['runner','Blue’s Big Run','Jump, collect, and explore a glowing new world.',Footprints,'#75c7ae'],['2048','2048','Slide, combine, and think one move ahead.',Grid2X2,'#e8b576'],['sudoku','Sudoku','A quiet challenge for a sharp mind.',Hash,'#d795b2']];
export function VideoArcade(){const tr=useT();const{coins,transact,notify}=useApp();const[game,setGame]=useState(null),[ticket,setTicket]=useState(null);function openGame(){const result=transact('game');if(result.error){notify(result.error);return;}setGame({id:ticket,key:crypto.randomUUID()});setTicket(null);}return <section className={s.arcade}><div className={s.sectionTitle}><div><span>TAKE A PLAY BREAK</span><h2>{tr('Video games')} & {tr('Logic games')}</h2></div><p>{tr('Real gameplay. Keyboard and touch. Your next high score awaits.')}</p></div><div className={s.gameGrid}>{MODES.map(([id,name,description,Icon,color])=><article className={s.gameCard} key={id} style={{'--game':color}}><div className={s.gameArt+' '+s[id]}><div className={s.artGrid}/><Icon size={54}/>{id==='2048'&&<strong>2048</strong>}<span className={s.artStar}>✦</span></div><div className={s.cardBody}><span>{tr(['2048','sudoku'].includes(id)?'LOGIC & STRATEGY':'ARCADE ORIGINAL')}</span><h3>{name}</h3><p>{tr(description)}</p><Button variant="secondary" onClick={()=>setTicket(id)}><Play size={14}/>{tr('Play game')} · {GAME_TICKET} {tr('coins')}<ArrowRight size={15}/></Button></div></article>)}</div>{ticket&&<Modal title={tr('Open a play session?')} size="small" onClose={()=>setTicket(null)}><div className="dialog-content"><h2>{MODES.find(m=>m[0]===ticket)[1]}</h2><p>{tr('One ticket includes retries until you close the game. Opening it again costs a new ticket.')}</p><p>{tr('Your balance')}: <strong>{coins} {tr('coins')}</strong></p><Button disabled={coins<GAME_TICKET} onClick={openGame}>{tr('Spend')} {GAME_TICKET} {tr('coins & play')}</Button>{coins<GAME_TICKET&&<p>{tr('Finish a review to earn 2 coins per correct answer.')}</p>}</div></Modal>}{game&&<ReviewBoundary onClose={()=>setGame(null)}><Modal title={MODES.find(m=>m[0]===game.id)[1]} size="large" onClose={()=>setGame(null)}><div key={game.key}>{game.id==='2048'?<Game2048/>:game.id==='sudoku'?<Sudoku/>:<CanvasGame kind={game.id}/>}</div></Modal></ReviewBoundary>}</section>}
function draw(ctx,state){
 const W=900,H=500,t=state.time;ctx.clearRect(0,0,W,H);const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,state.kind==='runner'?'#18364e':'#10162d');sky.addColorStop(1,state.kind==='space'?'#342553':'#243c59');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
 for(let i=0;i<38;i++){ctx.fillStyle=i%3?'#b8d8f870':'#e9c990';ctx.beginPath();ctx.arc((i*179)%900,((i*71+t*(state.kind==='space'?35:4))%400),i%4===0?2:1,0,Math.PI*2);ctx.fill();}
 const star=(x,y,r=13)=>{ctx.save();ctx.translate(x,y);ctx.fillStyle='#ffe1a2';ctx.shadowBlur=15;ctx.shadowColor='#ffd778';ctx.beginPath();for(let j=0;j<10;j++){const a=j*Math.PI/5-Math.PI/2,rr=j%2?r*.45:r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.restore()};
 if(state.kind==='racer'){
  ctx.fillStyle='#1b2944';ctx.fillRect(240,0,420,H);ctx.strokeStyle='#7bc9ff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(244,0);ctx.lineTo(244,H);ctx.moveTo(656,0);ctx.lineTo(656,H);ctx.stroke();ctx.strokeStyle='#c3ceef50';ctx.lineWidth=3;ctx.setLineDash([32,35]);ctx.lineDashOffset=-t*210;ctx.beginPath();ctx.moveTo(382.5,0);ctx.lineTo(382.5,H);ctx.moveTo(517.5,0);ctx.lineTo(517.5,H);ctx.stroke();ctx.setLineDash([]);
  for(let i=0;i<8;i++){const y=(i*85+t*240)%620-90;ctx.fillStyle='#315372';ctx.fillRect(145,y,55,50);ctx.fillRect(700,y+30,55,50);ctx.fillStyle='#91bbd755';ctx.fillRect(158,y+9,9,9);ctx.fillRect(175,y+9,9,9);}
  const car=(x,y,fill,player=false)=>{ctx.save();ctx.translate(x,y);ctx.shadowColor=fill;ctx.shadowBlur=player?20:4;ctx.fillStyle='#101421';ctx.fillRect(-27,-25,54,12);ctx.fillRect(-27,20,54,12);ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(-23,-42,46,85,11);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#182942';ctx.beginPath();ctx.roundRect(-16,-22,32,23,5);ctx.fill();ctx.fillRect(-15,13,30,16);ctx.fillStyle='#fff5cd';ctx.fillRect(-18,-37,10,5);ctx.fillRect(8,-37,10,5);ctx.fillStyle='#fff5';ctx.fillRect(-3,-12,6,45);ctx.restore()};
  state.objects.forEach(o=>o.type==='coin'?star(o.x,o.y):car(o.x,o.y,'#d883a5'));if(!state.invulnerable||Math.floor(t*12)%2)car(state.x,410,'#76c9f3',true);
 }else if(state.kind==='space'){
  ctx.strokeStyle='#c5bdff15';for(let i=0;i<8;i++){ctx.beginPath();ctx.ellipse(720,80,30+i*28,15+i*13,-.5,0,Math.PI*2);ctx.stroke();}
  for(const o of state.objects){ctx.fillStyle='#a18eae';ctx.strokeStyle='#d4a8c1';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4+t*.7,r=o.radius*(i%2?.9:1.15);ctx.lineTo(o.x+Math.cos(a)*r,o.y+Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#685c8544';ctx.beginPath();ctx.arc(o.x-5,o.y-5,7,0,Math.PI*2);ctx.fill();}
  ctx.fillStyle='#98eeef';for(const b of state.bullets){ctx.shadowColor='#7afcff';ctx.shadowBlur=14;ctx.fillRect(b.x-3,b.y-13,6,22)}ctx.shadowBlur=0;
  if(!state.invulnerable||Math.floor(t*12)%2){ctx.save();ctx.translate(state.x,438);ctx.fillStyle='#f3ba76';ctx.beginPath();ctx.moveTo(-9,20);ctx.lineTo(0,38+Math.sin(t*35)*7);ctx.lineTo(9,20);ctx.fill();ctx.fillStyle='#a0c5ff';ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(-28,24);ctx.lineTo(0,14);ctx.lineTo(28,24);ctx.closePath();ctx.fill();ctx.fillStyle='#315378';ctx.beginPath();ctx.ellipse(0,-1,6,12,0,0,Math.PI*2);ctx.fill();ctx.restore();}
 }else{
  for(let layer=0;layer<2;layer++){ctx.fillStyle=layer?'#315b67':'#244757';ctx.beginPath();ctx.moveTo(0,450);for(let x=0;x<=960;x+=60)ctx.lineTo(x,320+layer*48+Math.sin(x/170+t*.12+layer*3)*35);ctx.lineTo(900,500);ctx.lineTo(0,500);ctx.fill();}
  ctx.fillStyle='#4d9a98';ctx.fillRect(0,427,900,4);ctx.fillStyle='#182f42';ctx.fillRect(0,431,900,69);ctx.fillStyle='#72b9ad60';for(let i=0;i<18;i++)ctx.fillRect((i*60-t*310%60+900)%960,449+i%3*11,20,3);
  for(const o of state.objects){if(o.type==='coin')star(o.x,300);else{ctx.fillStyle='#d79aad';ctx.beginPath();ctx.moveTo(o.x-o.width/2,427);ctx.lineTo(o.x,375);ctx.lineTo(o.x+o.width/2,427);ctx.fill();ctx.fillStyle='#f2bfca';ctx.beginPath();ctx.moveTo(o.x-6,390);ctx.lineTo(o.x,375);ctx.lineTo(o.x+6,390);ctx.fill();}}
  if(!state.invulnerable||Math.floor(t*12)%2){const x=state.x,y=state.y;ctx.fillStyle='#6dc3eb';ctx.beginPath();ctx.ellipse(x,y-14,23,31,-.25,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.roundRect(x-6,y-62,46,31,12);ctx.fill();ctx.beginPath();ctx.moveTo(x-20,y-10);ctx.lineTo(x-49,y-35);ctx.lineTo(x-36,y+5);ctx.fill();ctx.fillRect(x-16,y+6,12,21);ctx.fillRect(x+6,y+4,12,23);ctx.fillStyle='#1c3e58';ctx.beginPath();ctx.arc(x+25,y-52,3.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a5e5e8';ctx.beginPath();ctx.ellipse(x+4,y-12,11,19,0,0,Math.PI*2);ctx.fill();}
 }
}
function CanvasGame({kind}){
 const tr=useT(),{recordReview,playTone}=useApp();const canvas=useRef(),engine=useRef(freshGame(kind)),keys=useRef({}),pendingInput=useRef({}),lastHud=useRef(0),checkpoint=useRef(20),recorded=useRef(false);const [status,setStatus]=useState('ready'),[hud,setHud]=useState({score:0,lives:3,time:0}),[subject,setSubject]=useState('maths'),[answers,setAnswers]=useState([]),[choice,setChoice]=useState(null),[checked,setChecked]=useState(false);const [questions,setQuestions]=useState(()=>makeQuiz('maths'));const question=questions[answers.length%questions.length];
 function finish(){if(!recorded.current){recorded.current=true;if(answers.length)recordReview(subject,answers.filter(Boolean).length,answers.length,Math.max(1,Math.round(engine.current.time/60)),'arcade');const key='aster-video-best-'+kind;try{storage.setItem(key,String(Math.max(Number(storage.getItem(key))||0,Math.floor(engine.current.time*10+engine.current.score))))}catch{}}setStatus('over')}
 useEffect(()=>{const c=canvas.current,ctx=c.getContext('2d');if(status!=='running'){draw(ctx,engine.current);return;}let frame,last=0;const loop=now=>{if(status==='running'){engine.current=stepGame(engine.current,{...keys.current,...pendingInput.current},last?((now-last)/1000):0);pendingInput.current={};if(now-lastHud.current>100){lastHud.current=now;setHud({score:Math.floor(engine.current.time*10+engine.current.score),lives:engine.current.lives,time:Math.floor(engine.current.time)})}if(engine.current.over)finish();else if(engine.current.time>=checkpoint.current){checkpoint.current+=20;keys.current={};setStatus('checkpoint')}}draw(ctx,engine.current);last=now;frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[status,answers,subject]);
 useEffect(()=>{const mapping={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',' ':'fire',ArrowUp:'fire',w:'fire'};function down(e){if(e.target.matches('input,select,textarea,button'))return;if(mapping[e.key]&&status==='running'){e.preventDefault();keys.current[mapping[e.key]]=true;pendingInput.current[mapping[e.key]]=true}else if(e.key.toLowerCase()==='p'){e.preventDefault();setStatus(v=>v==='running'?'paused':v==='paused'?'running':v)}}function up(e){if(mapping[e.key])keys.current[mapping[e.key]]=false}function blur(){keys.current={};pendingInput.current={};setStatus(v=>v==='running'?'paused':v)}window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur)}},[status]);
 function start(){engine.current=freshGame(kind);keys.current={};pendingInput.current={};checkpoint.current=20;recorded.current=false;setAnswers([]);setChoice(null);setChecked(false);setHud({score:0,lives:3,time:0});setQuestions(makeQuiz(subject));setStatus('running');canvas.current.focus()}
 function touch(key){return{onPointerDown:e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);keys.current[key]=true;pendingInput.current[key]=true;canvas.current.focus()},onPointerUp:()=>keys.current[key]=false,onPointerCancel:()=>keys.current[key]=false,onLostPointerCapture:()=>keys.current[key]=false}}
 return <div className={s.game}><div className={s.hud}><span><Trophy size={16}/>{hud.score}</span><span><Heart size={16}/>{hud.lives} / 3</span><span>{75-hud.time}s</span><button aria-label={tr(status==='paused'?'Resume':'Pause')} disabled={!['running','paused'].includes(status)} onClick={()=>{keys.current={};setStatus(v=>v==='running'?'paused':'running');canvas.current.focus()}}>{status==='paused'?<Play size={17}/>:<Pause size={17}/>}</button></div><div className={s.canvasWrap}><canvas ref={canvas} width="900" height="500" tabIndex={0} aria-label={MODES.find(m=>m[0]===kind)[1]+' game. '+(kind==='runner'?'Press Space to jump.':'Use Left and Right arrows to move.')+(kind==='space'?' Hold Space to shoot.':'')}/>{status==='ready'&&<div className={s.overlay}><span>READY, PLAYER YOU</span><h2>{MODES.find(m=>m[0]===kind)[1]}</h2><p>{tr(kind==='racer'?'Arrow keys or A/D to switch lanes. Dodge cars and collect stars.':kind==='space'?'Move with arrows or A/D. Hold Space to shoot. Stop asteroids before they pass you.':'Press Space, Up, or tap Jump to leap over obstacles. Collect floating stars.')}</p><label>{tr('Course checkpoints')}<select value={subject} onChange={e=>setSubject(e.target.value)}>{Object.entries(COURSES).filter(([,c])=>c.questions.length).map(([id,c])=><option value={id} key={id}>{tr(c.name)}</option>)}</select></label><Button onClick={start}><Play size={17}/>{tr('Play game')}</Button><small>{tr('75 seconds · 3 lives · a learning checkpoint every 20 seconds')}</small></div>}{status==='paused'&&<div className={s.overlay}><h2>{tr('Paused')}</h2><p>{tr('Take your time. Your game is waiting.')}</p><Button onClick={()=>{setStatus('running');canvas.current.focus()}}>{tr('Resume')}<Play size={17}/></Button></div>}{status==='over'&&<div className={s.overlay}><Trophy size={32}/><h2>{tr(engine.current.lives>0?'Run complete!':'Game over')}</h2><strong className={s.finalScore}>{Math.floor(engine.current.time*10+engine.current.score)}</strong><p>{answers.length?answers.filter(Boolean).length+' / '+answers.length+' '+tr('checkpoint answers correct')+' · +'+answers.filter(Boolean).length*2+' '+tr('Coins'):tr('Reach a checkpoint to earn learning coins. Arcade points are your game score.')}</p><Button onClick={start}><RotateCcw size={17}/>{tr('Play again')}</Button></div>}</div>
 {status==='checkpoint'?<div className={s.checkpoint}><span>{tr('LEARNING CHECKPOINT')} · {tr(COURSES[subject].name)}</span><h3>{question.q}</h3><div>{question.choices.map((c,i)=><button key={c.text} disabled={checked} aria-pressed={choice===i} className={checked&&c.correct?s.correct:''} onClick={()=>setChoice(i)}>{c.text}</button>)}</div>{checked&&<p role="status">{question.why}</p>}<Button disabled={choice===null} onClick={()=>{if(!checked){setChecked(true);playTone(question.choices[choice].correct)}else{setAnswers(v=>[...v,question.choices[choice].correct]);setChoice(null);setChecked(false);setStatus('running');canvas.current.focus()}}}>{tr(checked?'Continue':'Check answer')}</Button></div>:<div className={s.controls}>{kind!=='runner'&&<><button disabled={status!=='running'} aria-label="Move left" {...touch('left')}><ArrowLeft/>{tr('Left')}</button><button disabled={status!=='running'} aria-label="Move right" {...touch('right')}><ArrowRight/>{tr('Right')}</button></>}{kind!=='racer'&&<button disabled={status!=='running'} {...touch('fire')}>{kind==='space'?<Star/>:<ArrowUp/>}{tr(kind==='space'?'Fire':'Jump')}</button>}<small>{tr('P to pause · keyboard and touch controls')}</small></div>}</div>;
}
function Game2048(){const tr=useT();const {playSound}=useApp();const [board,setBoard]=useState(()=>spawnTile(spawnTile(Array(16).fill(0)))),[score,setScore]=useState(0),[best,setBest]=useState(()=>Number(readStored('aster-2048-best',0))||0),[won,setWon]=useState(false);const touch=useRef();const boardRef=useRef(board),scoreRef=useRef(score);boardRef.current=board;scoreRef.current=score;const over=!canMove2048(board);
 function move(dir){const result=move2048(boardRef.current,dir);if(!result.moved)return;boardRef.current=spawnTile(result.board);scoreRef.current+=result.score;setBoard(boardRef.current);setScore(scoreRef.current);if(result.board.some(n=>n>=2048)&&!won){setWon(true);playSound('reward')}playSound('click');}
 useEffect(()=>{if(score>best){setBest(score);try{storage.setItem('aster-2048-best',JSON.stringify(score))}catch{}}},[score,best]);
 function fresh(){setBoard(spawnTile(spawnTile(Array(16).fill(0))));setScore(0);setWon(false)}
 return <div className={s.logic}><div className={s.logicHeading}><div><span>SLIDE. COMBINE. THINK AHEAD.</span><h2>2048</h2></div><div className={s.scores}><span>{tr('Score')}<strong>{score}</strong></span><span>{tr('Best score')}<strong>{best}</strong></span></div></div><p>{tr('Use arrow keys or swipe. Equal tiles combine once per move. Reach 2048!')}</p><div className={s.board2048} tabIndex={0} role="application" aria-label="2048 board. Use arrow keys to move tiles." onKeyDown={e=>{const dir={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(dir){e.preventDefault();move(dir)}}} onPointerDown={e=>{touch.current=[e.clientX,e.clientY];e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{if(!touch.current)return;const[ox,oy]=touch.current,dx=e.clientX-ox,dy=e.clientY-oy;touch.current=null;if(Math.max(Math.abs(dx),Math.abs(dy))>20)move(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up')}}>{board.map((n,i)=><div key={i} className={s.tile} data-power={n?Math.min(11,Math.log2(n)):0} aria-label={'Row '+(Math.floor(i/4)+1)+' column '+(i%4+1)+': '+(n||'empty')}>{n||''}</div>)}</div><div className={s.arrowPad}>{[['left',ArrowLeft],['up',ArrowUp],['down',ArrowDown],['right',ArrowRight]].map(([dir,Icon])=><button aria-label={'Move '+dir} key={dir} onClick={()=>move(dir)}><Icon size={21}/></button>)}</div><div role="status" className={s.logicStatus}>{over?tr('Game over'):won?tr('You reached 2048 — keep going!'):tr('Every move is a new possibility.')}</div><Button variant="secondary" onClick={fresh}><RotateCcw size={16}/>{tr('New game')}</Button></div>
}
function Sudoku(){const tr=useT(),{playSound}=useApp();const[board,setBoard]=useState([...SUDOKU_PUZZLE]),[selected,setSelected]=useState(null),[hints,setHints]=useState(0),[message,setMessage]=useState('');const won=sudokuSolved(board);const wasWon=useRef(false);useEffect(()=>{if(won&&!wasWon.current){playSound('reward');wasWon.current=true}},[won]);function put(n){if(selected===null||SUDOKU_PUZZLE[selected]||won)return;setBoard(v=>v.map((x,i)=>i===selected?n:x));setMessage('')}function hint(){if(selected===null||SUDOKU_PUZZLE[selected]){setMessage(tr('Choose an empty or editable cell first.'));return;}setBoard(v=>v.map((x,i)=>i===selected?SUDOKU_SOLUTION[i]:x));setHints(v=>v+1);setMessage(tr('Hint filled the selected cell.'))}
 return <div className={s.logic}><div className={s.logicHeading}><div><span>A LITTLE ORDER IN THE WORLD</span><h2>Sudoku</h2></div><span>{hints} {tr('hints used')}</span></div><p>{tr('Fill each row, column, and 3 × 3 box with 1–9. Select a cell, then type or tap a number.')}</p><div className={s.sudoku} role="group" aria-label="Sudoku board">{board.map((n,i)=><button key={i} className={(SUDOKU_PUZZLE[i]?s.given:'')+' '+(sudokuConflicts(board,i)?s.conflict:'')} aria-label={'Row '+(Math.floor(i/9)+1)+' column '+(i%9+1)+': '+(n||'empty')+(SUDOKU_PUZZLE[i]?' fixed':'')} aria-pressed={selected===i} onClick={()=>setSelected(i)} onKeyDown={e=>{if(/^[1-9]$/.test(e.key)){e.preventDefault();put(Number(e.key))}else if(['Backspace','Delete','0'].includes(e.key)){e.preventDefault();put(0)}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const j=Math.max(0,Math.min(80,i+({ArrowLeft:-1,ArrowRight:1,ArrowUp:-9,ArrowDown:9}[e.key])));setSelected(j);e.currentTarget.parentElement.children[j].focus()}}}>{n||''}</button>)}</div><div className={s.numberPad}>{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} onClick={()=>put(n)}>{n}</button>)}<button onClick={()=>put(0)}>{tr('Erase')}</button></div><p role="status" className={s.logicStatus}>{won?tr('You win!'):message||tr('Conflicting entries are highlighted. Take it one step at a time.')}</p><div className={s.logicActions}><Button variant="secondary" disabled={won} onClick={hint}>{tr('Hint')}</Button><Button variant="secondary" onClick={()=>{setBoard([...SUDOKU_PUZZLE]);setHints(0);setSelected(null);setMessage('');wasWon.current=false}}><RotateCcw size={16}/>{tr('Restart')}</Button></div></div>
}
