import React,{useCallback,useEffect,useRef,useState} from 'react';
import {MessagesSquare,Hash,Send,Reply,Flag,Trash2,Pencil,RefreshCw,X,Users,ArrowUp,ShieldCheck,Check} from 'lucide-react';
import {api,useAuth} from '../../auth.jsx';import {useApp} from '../../context.jsx';import {useT} from '../../i18n.jsx';import {PageHeading,Button,Modal} from '../UI.jsx';
import s from './Community.module.css';
const rooms=[['general','Common room','A place to ask, share, and think together.'],['igcse','IGCSE study','Subjects, exam preparation, and revision partners.'],['ib','IB study','Ideas, coursework questions, and life in the Diploma.'],['homework','Homework help','Explain your approach. Help someone find their next step.']];
export default function Community(){
 const tr=useT(),{user}=useAuth(),{navigate,notify}=useApp();
 const[room,setRoom]=useState('general'),[messages,setMessages]=useState([]),[draft,setDraft]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[reply,setReply]=useState(null),[editing,setEditing]=useState(null),[report,setReport]=useState(null),[reason,setReason]=useState('Unkind or abusive'),[hasOlder,setHasOlder]=useState(false),[reportBusy,setReportBusy]=useState(false),[hidden,setHidden]=useState([]),[connected,setConnected]=useState(false),[olderBusy,setOlderBusy]=useState(false);
 const list=useRef(),input=useRef(),nearBottom=useRef(true),requestId=useRef(crypto.randomUUID()),generation=useRef(0),busy=useRef(false);
 const scrollDown=useCallback(()=>{requestAnimationFrame(()=>list.current?.scrollTo({top:list.current.scrollHeight,behavior:'auto'}));},[]);
 useEffect(()=>{const gen=++generation.current;let alive=true,abort;setMessages([]);setReply(null);setEditing(null);setDraft('');setError('');setLoading(true);setHasOlder(false);nearBottom.current=true;
  async function refresh(){if(!user||document.hidden)return;if(busy.current)return;busy.current=true;abort=new AbortController();try{const data=await api('/community?room='+room,'GET',undefined,abort.signal);if(!alive)return;setMessages(old=>{const freshIds=new Set(data.messages.map(m=>m.id));return [...old.filter(m=>!freshIds.has(m.id)&&Number(m.id)<Number(data.messages[0]?.id||0)),...data.messages];});setHasOlder(v=>v||data.hasOlder);setConnected(true);if(nearBottom.current)scrollDown();}catch(e){if(alive&&e.name!=='AbortError'){setError(e.message);setConnected(false);}}finally{if(alive)setLoading(false);if(generation.current===gen)busy.current=false;}}
  busy.current=false;if(user)refresh();else setLoading(false);const interval=setInterval(refresh,3000);const visible=()=>{if(!document.hidden)refresh();};document.addEventListener('visibilitychange',visible);return()=>{alive=false;abort?.abort();clearInterval(interval);document.removeEventListener('visibilitychange',visible);};
 },[user?.id,room,scrollDown]);
 async function submit(e){e.preventDefault();if(sending||!draft.trim())return;setSending(true);setError('');const currentRoom=room;try{if(editing){await api('/community/'+editing.id,'PATCH',{content:draft});setMessages(v=>v.map(m=>m.id===editing.id?{...m,content:draft.trim(),editedAt:new Date().toISOString()}:m));}else{const data=await api('/community','POST',{room,content:draft,replyId:reply?.id,clientId:requestId.current});setMessages(v=>{const ids=new Set(data.messages.map(m=>m.id));return[...v.filter(m=>!ids.has(m.id)&&Number(m.id)<Number(data.messages[0]?.id||0)),...data.messages];});}if(currentRoom===room){setDraft('');setReply(null);setEditing(null);requestId.current=crypto.randomUUID();nearBottom.current=true;scrollDown();input.current?.focus();}}catch(e){setError(e.message);}finally{setSending(false);}}
 async function remove(m){try{await api('/community/'+m.id,'PATCH',{action:'remove'});setMessages(v=>v.map(i=>i.id===m.id?{...i,content:'',deletedAt:new Date().toISOString()}:i));notify('Message removed.',{label:'Undo',run:async()=>{try{await api('/community/'+m.id,'PATCH',{action:'restore'});setMessages(v=>v.map(i=>i.id===m.id?m:i));}catch(e){notify(e.message);}}});}catch(e){setError(e.message);}}
 async function older(){const gen=generation.current;setOlderBusy(true);const top=list.current?.scrollHeight||0;try{const data=await api('/community?room='+room+'&before='+messages[0].id);if(generation.current!==gen)return;setMessages(v=>[...data.messages,...v]);setHasOlder(data.hasOlder);requestAnimationFrame(()=>{if(list.current)list.current.scrollTop+=list.current.scrollHeight-top;});}catch(e){setError(e.message);}finally{setOlderBusy(false);}}
 async function sendReport(){setReportBusy(true);try{await api('/community/'+report.id+'/report','POST',{reason});setHidden(v=>[...v,report.id]);setReport(null);notify('Report saved for the local server owner. The message is hidden for this visit.');}catch(e){setError(e.message);}finally{setReportBusy(false);}}
 const current=rooms.find(r=>r[0]===room);
 return <><PageHeading eyebrow={tr('THINK BETTER, TOGETHER')} title={tr('The student lounge.')} description={tr('One shared space for questions, conversations, and a little perspective.')} />
 <div className={s.layout}><aside className={s.rooms}><div className={s.roomTitle}><MessagesSquare size={20}/><strong>{tr('Aster community')}</strong></div><span className={s.label}>{tr('DISCUSSION ROOMS')}</span>{rooms.map(([id,title])=><button disabled={sending} key={id} className={room===id?s.active:''} aria-pressed={room===id} onClick={()=>setRoom(id)}><Hash size={17}/>{tr(title)}</button>)}<div className={s.guidelines}><ShieldCheck size={20}/><h3>{tr('Make space for others.')}</h3><p>{tr('Be kind. Explain your reasoning. Share helpful ideas, not private grades or passwords.')}</p><small>{tr('Shared by accounts on this Aster server. No messages are posted to your school portals.')}</small></div></aside>
 <section className={s.conversation} aria-label={tr(current[1])}><header className={s.header}><span className={s.hash}><Hash size={24}/></span><div><h2>{tr(current[1])}</h2><p>{tr(current[2])}</p></div><span className={s.status}><i className={connected?s.online:''}/>{tr(user?(connected?'Connected':'Connecting…'):'Sign in to join')}</span></header>
 {!user?<div className={s.join}><Users size={44}/><h2>{tr('There is a seat for you.')}</h2><p>{tr('Use your Aster account to read and join the conversation.')}</p><Button onClick={()=>navigate('login')}>{tr('Sign in')}</Button><button className="text-link" onClick={()=>navigate('signup')}>{tr('Create an account')}</button></div>:<><div className={s.messages} ref={list} onScroll={()=>{const el=list.current;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<100;}} aria-label={tr('Messages')}>
 {hasOlder&&<button disabled={olderBusy} className={s.older} onClick={older}><ArrowUp size={14}/>{tr(olderBusy?'Loading…':'Earlier messages')}</button>}
 {loading&&<div className={s.loading} role="status">{tr('Loading conversation…')}</div>}{!loading&&!messages.length&&<div className={s.empty}><MessagesSquare size={38}/><h3>{tr('Start a good conversation.')}</h3><p>{tr('No messages here yet. Ask a question or share something useful.')}</p></div>}
 {messages.filter(m=>!hidden.includes(m.id)).map(m=><article key={m.id} className={`${s.message} ${m.userId===user.id?s.own:''}`}><span className={s.avatar}>{m.name.slice(0,1).toUpperCase()}</span><div className={s.messageBody}><div className={s.byline}><strong>{m.name}</strong><span>@{m.username}</span><time dateTime={m.createdAt} title={new Date(m.createdAt).toLocaleString(tr.locale)}>{new Date(m.createdAt).toLocaleTimeString(tr.locale,{hour:'2-digit',minute:'2-digit'})}</time>{m.editedAt&&<small>{tr('edited')}</small>}</div>{m.replyId&&<blockquote>@{m.replyUsername} · {m.replyText}</blockquote>}<p>{m.deletedAt?<em>{tr('Message removed')}</em>:m.content}</p>{!m.deletedAt&&<div className={s.messageActions}><button aria-label={tr('Reply to message')} onClick={()=>{setEditing(null);setReply(m);input.current?.focus();}}><Reply size={13}/>{tr('Reply')}</button>{m.userId===user.id?<><button onClick={()=>{setEditing(m);setReply(null);setDraft(m.content);input.current?.focus();}}><Pencil size={13}/>{tr('Edit')}</button><button onClick={()=>remove(m)}><Trash2 size={13}/>{tr('Remove')}</button></>:<button onClick={()=>setReport(m)}><Flag size={13}/>{tr('Report')}</button>}</div>}</div></article>)}
 </div><form className={s.composer} onSubmit={submit}>{(reply||editing)&&<div className={s.replying}><Reply size={15}/>{tr(editing?'Editing your message':'Replying to')} {!editing&&reply.name}<button type="button" aria-label={tr('Cancel reply or edit')} onClick={()=>{if(editing)setDraft('');setEditing(null);setReply(null);}}><X size={15}/></button></div>}<label className="sr-only" htmlFor="community-message">{tr('Your message')}</label><textarea id="community-message" ref={input} value={draft} onChange={e=>{setDraft(e.target.value);requestId.current=crypto.randomUUID();}} maxLength={2000} rows={3} placeholder={tr('Ask a question. Share an idea.')} disabled={sending} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit(e);}}}/><div><small>{tr('Enter to send · Shift + Enter for a new line')} <span>{draft.length}/2000</span></small><Button type="submit" disabled={sending||!draft.trim()}><Send size={15}/>{tr(sending?'Sending…':editing?'Save edit':'Send')}</Button></div></form></>}
 {error&&<div className={s.error} role="alert">{tr(error)}<button aria-label={tr('Dismiss notification')} onClick={()=>setError('')}><X size={15}/></button></div>}</section></div>
 <p className={s.footnote}>{tr('Messages refresh every few seconds. Reports are saved for the server owner; there is no staffed moderation service.')}</p>
 {report&&<Modal title={tr('Report a message')} onClose={()=>!reportBusy&&setReport(null)}><div className={s.report}><p>{tr('Choose the concern. This also hides the message for this visit.')}</p><label>{tr('Reason')}<select value={reason} onChange={e=>setReason(e.target.value)}>{['Unkind or abusive','Spam','Personal information','Other concern'].map(x=><option key={x} value={x}>{tr(x)}</option>)}</select></label><Button disabled={reportBusy} onClick={sendReport}>{tr(reportBusy?'Saving…':'Save report')}</Button></div></Modal>}</>;
}
