import CharacterCreator from './CharacterCreator.jsx';
import AIChoice,{useAIChoice} from '../AIChoice.jsx';
import TutorText from '../TutorText.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {Coins,Heart,Shirt,Apple,Sparkles,MessageCircle,Send,Trash2,ChevronRight,Crown,Glasses,Flower2,Star,Check} from 'lucide-react';
import {useApp} from '../../context.jsx';import {useT,useLanguage} from '../../i18n.jsx';import {api} from '../../auth.jsx';import {COURSES} from '../../study.js';
import {BUDDIES,SHOP,normalizeBuddy,buyForBuddy} from '../../buddies.js';import {BuddyAvatar} from './BuddyAvatar.jsx';import {PageHeading,Button,Modal} from '../UI.jsx';import s from './Buddy.module.css';
function ItemArt({item}){const Icon={food:Apple,clothes:Shirt,accessories:Sparkles}[item.type];return <div className={s.itemArt} style={{'--item-color':item.color}}>{item.id==='crown'?<Crown/>:item.id==='glasses'?<Glasses/>:item.id==='flower'?<Flower2/>:item.id==='cookie'?<Star/>:<Icon/>}</div>}
export default function BuddyGarden({embedded=false}){
 const tr=useT();const {prefs,setPrefs,coins:balance,transact,notify,playSound,navigate}=useApp();const buddy=normalizeBuddy(prefs.buddy);const [tab,setTab]=useState('food'),[excited,setExcited]=useState(false),[candidate,setCandidate]=useState(buddy.id),[confirm,setConfirm]=useState(false);const timer=useRef();
 const species=BUDDIES.find(b=>b.id===buddy.id),chosen=BUDDIES.find(b=>b.id===candidate);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 function update(data){setPrefs(p=>({...p,buddy:{...normalizeBuddy(p.buddy),...data}}))}
 function buy(item){if(!prefs.proPreview){navigate('pro');return;}const result=transact('buddy',item.id);if(result.error){notify(tr(result.error));return;}playSound('reward');setExcited(true);clearTimeout(timer.current);timer.current=setTimeout(()=>setExcited(false),1300);notify(tr(item.type==='food'?'A happy snack break!':'Added to your wardrobe.'))}
 function adopt(){const result=transact('adopt',candidate);setConfirm(false);if(result.error){notify(tr(result.error));return;}setExcited(true);clearTimeout(timer.current);timer.current=setTimeout(()=>setExcited(false),1300);playSound('reward');notify(tr('Your companion is ready for the journey.'))}
 return <>{!embedded&&<PageHeading eyebrow="A COMPANION FOR EVERY CHAPTER" title={tr('Your buddy, your story.')} description={tr('Choose one companion. Make it unmistakably yours.')}/>}
 {!embedded&&<CharacterCreator/>}<div className={s.gardenGrid}><section className={s.habitat}><div className={s.habitatTop}><span className={s.pill}><Heart size={14}/>{tr(buddy.adopted?'Your companion':'Meet your future companion')}</span><span className={s.coin}><Coins size={17}/>{balance} {tr('Coins')}</span></div><div className={s.skyStars} aria-hidden="true">✦ <span>✧</span> ·</div><div className={s.buddyStage}><BuddyAvatar {...(buddy.adopted?buddy:chosen)} excited={excited}/><div className={s.island}/></div><div className={s.intro}><span>{tr((buddy.adopted?species:chosen).species)} · {tr((buddy.adopted?species:chosen).trait)}</span><h2>{buddy.adopted?buddy.name:chosen.name}</h2><p>{excited?tr('That made my day!'):tr('A little curiosity can take us a long way.')}</p>{buddy.adopted?<Button onClick={()=>navigate('helper')}><MessageCircle size={16}/>{tr('Ask your buddy')}</Button>:<Button onClick={()=>setConfirm(true)}><Heart size={16}/>{tr('Choose this companion')}</Button>}</div><div className={s.careStats}><span><Heart size={15}/>{buddy.fed} {tr('snack breaks')}</span><span><Shirt size={15}/>{buddy.owned.length} {tr('collected items')}</span></div></section>
 <section className={s.customize}>{!buddy.adopted?<><h2>{tr('Ten personalities. One companion.')}</h2><p>{tr('Look around and choose the one that feels like you. Once adopted, your companion stays with your account. Its name, colour, and outfits can always change.')}</p><div className={s.buddyPicker}>{BUDDIES.map(b=><button key={b.id} aria-label={b.name+' · '+b.species} aria-pressed={candidate===b.id} onClick={()=>setCandidate(b.id)}><BuddyAvatar {...b}/><span>{b.name}</span>{candidate===b.id&&<Check size={12}/>}</button>)}</div><div className={s.adoptNote}><Heart size={20}/><p>{tr('No care penalties. Your buddy is always happy to see you, even after a break.')}</p></div></>:<><span className={s.pill}><Check size={13}/>{tr('Your companion, chosen')}</span><h2 className={s.customTitle}>{tr('Make it your own.')}</h2><p>{tr('Same companion, a thousand possibilities. Change your style whenever you like.')}</p><label>{tr('Buddy name')}<input value={buddy.name} maxLength={24} onChange={e=>update({name:e.target.value})}/></label><label>{tr('Color')}<input type="color" value={buddy.color} onChange={e=>update({color:e.target.value})}/></label><div className={s.palette}>{['#63b3ed','#a594eb','#e99ec2','#ef9b69','#96c8a6','#e0bb73'].map(c=><button key={c} style={{background:c}} aria-label={tr('Color')+' '+c} aria-pressed={buddy.color===c} onClick={()=>update({color:c})}/>)}</div><div className={s.earnCard}><Coins size={23}/><div><strong>{tr('Your effort becomes your style.')}</strong><p>{tr('2 coins per correct review answer. 50 coins per recorded percentage exam above 90%, once per exam.')}</p><button className="text-link" onClick={()=>navigate('practice')}>{tr('Earn coins in a review')} →</button></div></div></>}</section></div>
 <div className={s.shopHead}><div><span className={s.kicker}>LITTLE THINGS. BIG PERSONALITY.</span><h2>{tr('Shop')} & {tr('Wardrobe')}</h2><p>{SHOP.length} {tr('things to discover. No real-money coins.')}</p></div><span className={s.coin}><Coins size={20}/>{balance}</span></div>{!prefs.proPreview&&<div className={s.shopLocked}><Sparkles size={19}/><span>{tr('The buddy shop is included with Pro. Preview the collection below.')}</span><Button onClick={()=>navigate('pro')}>{tr('Explore Pro')}</Button></div>}<div className={s.tabs}>{[['food','Food'],['clothes','Clothes'],['accessories','Accessories'],['owned','Wardrobe']].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{tr(name)}</button>)}</div>
 <div className={s.shopGrid}>{SHOP.filter(i=>tab==='owned'?buddy.owned.includes(i.id):i.type===tab).map(item=>{const owned=buddy.owned.includes(item.id),slot=item.type==='clothes'?'clothes':'accessory',equipped=buddy[slot]===item.id;return <article key={item.id} className={s.shopCard}>{item.type==='food'?<ItemArt item={item}/>:<div className={s.outfitPreview} style={{'--item-color':item.color}}><BuddyAvatar {...buddy} {...{[slot]:item.id}}/></div>}<h3>{tr(item.name)}</h3><small>{tr(item.type==='food'?'A snack and a happy dance.':owned?'Owned':'Keep it in your collection.')}</small>{owned?<Button variant="secondary" onClick={()=>update({[slot]:equipped?'':item.id})}>{tr(equipped?'Remove':'Equip')}</Button>:<Button variant="secondary" disabled={prefs.proPreview&&(!buddy.adopted||balance<item.price)} onClick={()=>buy(item)}><Coins size={14}/>{item.price} · {tr(item.type==='food'?'Feed':'Buy')}</Button>}</article>})}</div>{tab==='owned'&&!buddy.owned.length&&<div className={s.empty}><Shirt size={28}/><p>{tr('Your first outfit is waiting in the shop. Finish a review to earn coins.')}</p><Button onClick={()=>navigate('practice')}>{tr('Quick review')}<ChevronRight size={16}/></Button></div>}{confirm&&<Modal title={tr('Choose your one companion?')} onClose={()=>setConfirm(false)} size="small"><div className={s.adoptConfirm}><BuddyAvatar {...chosen}/><h2>{chosen.name}</h2><p>{tr('This is your one companion for this account. You can change its name, colour, and outfits any time, but not its species.')}</p><Button onClick={adopt}>{tr('Adopt')} {chosen.name}<Heart size={16}/></Button><Button variant="secondary" onClick={()=>setConfirm(false)}>{tr('Keep looking')}</Button></div></Modal>}</>;
}
export function BuddyHelper(){
 const choice=useAIChoice();
 const tr=useT();const {language}=useLanguage();const {prefs}=useApp();const buddy=normalizeBuddy(prefs.buddy);
 const [messages,setMessages]=useState([]),[input,setInput]=useState(''),[subject,setSubject]=useState('science'),[busy,setBusy]=useState(false),[ready,setReady]=useState(null),[error,setError]=useState('');const controller=useRef(),end=useRef();
 useEffect(()=>{let live=true;const check=()=>api('/ai/status').then(v=>{if(live)setReady(v.ready)}).catch(()=>{if(live)setReady(false)});check();const t=setInterval(check,15000);return()=>{live=false;clearInterval(t);controller.current?.abort()}},[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:prefs.reduceMotion?'instant':'smooth'})},[messages,busy]);
 async function send(e){e?.preventDefault();const question=input.trim();if(!question||busy||!choice.ready)return;const history=messages.filter(m=>!m.error);setMessages(v=>[...v,{role:'user',content:question}]);setInput('');setBusy(true);setError('');controller.current=new AbortController();try{const result=await api('/ai/chat','POST',{message:question,history,subject,language,buddy:buddy.name,...choice.payload},controller.current.signal);setMessages(v=>[...v,{role:'assistant',content:result.answer,source:result.source}]);}catch(e){if(e.name!=='AbortError')setError(e.message)}finally{setBusy(false)}}
 return <><PageHeading eyebrow="A LITTLE HELP, WHEN YOU NEED IT" title={tr('Ask your buddy')} description={tr('Hints, explanations, and study plans, with your choice of AI.')}/><div className={s.helperGrid}><aside className={s.helperAside}><BuddyAvatar {...buddy}/><h2>{buddy.name}</h2><span className={s.pill}><i className={ready?s.ready:s.notReady}/>{tr(ready?'Local AI ready':ready===false?'Local AI is starting':'Checking local AI…')}</span><AIChoice choice={choice} disabled={busy}/><p>{tr('AI can make mistakes; check important answers against your course materials.')}</p><label>{tr('Subject')}<select value={subject} onChange={e=>setSubject(e.target.value)}>{Object.entries(COURSES).map(([id,c])=><option key={id} value={id}>{tr(c.name)}</option>)}</select></label><button className="text-link" onClick={()=>{controller.current?.abort();setMessages([]);setError('')}}><Trash2 size={14}/>{tr('Clear conversation')}</button></aside><section className={s.chat}><div className={s.chatHead}><span><MessageCircle size={17}/>{tr('Your study conversation')}</span><small>{choice.provider==='openai'?'GPT-6 Astra · OpenAI':'Qwen 3.5 · '+tr('Local AI')}</small></div><div className={s.messages} role="log" aria-live="polite" aria-label={tr('Your study conversation')}>{!messages.length&&<div className={s.chatWelcome}><Sparkles size={30}/><h2>{tr('What are we exploring today?')}</h2><p>{tr('Ask for a hint, a clearer explanation, or a small plan for your next study session.')}</p><div>{['Explain photosynthesis in simple steps.','Help me plan 15 minutes of maths revision.','Quiz me on computer networks.'].map(q=><button key={q} onClick={()=>setInput(tr(q))}>{tr(q)}<ChevronRight size={14}/></button>)}</div></div>}{messages.map((m,i)=><article key={i} className={m.role==='user'?s.userMessage:s.aiMessage}><strong>{m.role==='user'?tr('You'):buddy.name}</strong>{m.role==='assistant'?<TutorText text={m.content}/>:<p>{m.content}</p>}{m.source&&<small>{m.source}</small>}</article>)}{busy&&<div className={s.thinking} role="status"><i/><i/><i/>{tr('Thinking…')}</div>}{error&&<p role="alert" className={s.error}>{tr(error)}</p>}<div ref={end}/></div><form onSubmit={send} className={s.chatInput}><textarea aria-label={tr('Your question')} placeholder={tr('Ask a question, or tell me what feels tricky…')} value={input} maxLength={3000} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><button disabled={!input.trim()||busy||!choice.ready} aria-label={tr('Send')}><Send size={19}/></button></form><small className={s.chatNote}>{tr('Enter to send · Shift + Enter for a new line. Course notes are a snapshot, not live school updates.')}</small></section></div></>;
}

