import RevisionHomeCard from './revision/RevisionHomeCard.jsx';
import React,{useState} from 'react';
import {Search,ArrowRight,Layers3,Sparkles} from 'lucide-react';
import {COURSES,SUBJECT_ORDER} from '../study.js';
import {useApp} from '../context.jsx';
import {useT} from '../i18n.jsx';
import {Button,PageHeading,ColorIcon} from './UI.jsx';
import s from './PracticeSetup.module.css';
export default function PracticeLibrary(){const tr=useT(),{setReview,setCards,setMatch}=useApp(),[query,setQuery]=useState('');const total=Object.values(COURSES).reduce((n,c)=>n+c.questions.length,0);const visible=SUBJECT_ORDER.filter(id=>(COURSES[id].name+' '+COURSES[id].questions.map(q=>q.topic).join(' ')).toLowerCase().includes(query.toLowerCase()));return <><PageHeading eyebrow={tr('BUILD UNDERSTANDING, ONE QUESTION AT A TIME')} title={tr('Your practice library')} description={tr('More questions. More ways to make it click.')}/><section className={s.catalogHero}><div><h2>{tr('A bigger bank. A manageable session.')}</h2><p>{tr('Explore all 13 subjects, choose a topic, and practise in sets of 5, 10, 20, or 30. Get an explanation for every answer and revisit what needs another look.')}</p></div><strong>{total.toLocaleString()}<small>{tr('questions & explanations')}</small></strong></section><RevisionHomeCard/><label className={s.search}><Search size={18}/><input aria-label={tr('Find a subject or topic')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr('Find a subject or topic…')}/></label><div className={s.catalogGrid}>{visible.map(id=>{const c=COURSES[id],topics=[...new Set(c.questions.map(q=>q.topic))];return <article className={s.subject} key={id}><div className={s.subjectHead}><ColorIcon id={id} size={22}/><span>{c.questions.length} {tr('questions')}</span></div><h2>{tr(c.name)}</h2><p>{tr('Recall, explanations, and practical examples to strengthen your understanding.')}</p><div className={s.topics}>{topics.slice(0,4).map(t=><span key={t}>{tr(t)}</span>)}{topics.length>4&&<span>+{topics.length-4} {tr('topics')}</span>}</div><Button onClick={()=>setReview(id)}>{tr('Choose a practice session')}<ArrowRight size={16}/></Button><div className={s.secondary}><button onClick={()=>setCards(id)}><Layers3 size={14}/>{tr('Flashcards')}</button><button onClick={()=>setMatch(id)}><Sparkles size={14}/>{tr('Match concepts')}</button></div></article>})}</div>{!visible.length&&<p role="status">{tr('No subject matches. Try a broader topic.')}</p>}<p className={s.catalogNote}>{tr('Original Aster practice extends beyond your current classroom unit. It is not an official examination bank. Official papers and mark schemes are in the Research desk.')}</p></>}
