import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Coins,Flag,Mic,MicOff,Send,ShieldCheck,Sparkles,Swords,Volume2,VolumeX,X} from 'lucide-react';
import {useApp} from '../../context.jsx';
import {useT} from '../../i18n.jsx';
import {api} from '../../auth.jsx';
import AIChoice,{useAIChoice} from '../AIChoice.jsx';
import SpeakingPartner from './SpeakingPartner.jsx';
import {useVoice} from '../../hooks/useVoice.js';
import TutorText from '../TutorText.jsx';
import s from './Activities.module.css';

const TOPICS={oral:['A place I would love to visit','Describe a book that changed your thinking','Technology in everyday life','Protecting the environment','My plans after school','Practise an IGCSE speaking conversation','Discuss an IB Theory of Knowledge question'],debate:['Schools should start later in the morning','Homework should be optional','AI tools should be allowed in classrooms','Public transport should be free','School uniforms should be compulsory','Social media does more harm than good']};
const LANGUAGES=[['en','English'],['de','Deutsch'],['fr','Français'],['es','Español'],['zh','中文']];
export default function ConversationRoom({kind='oral'}){
  const tr=useT(),{prefs,setPrefs,transact,playSound,notify}=useApp(),choice=useAIChoice(),debate=kind==='debate';
  const [topic,setTopic]=useState(TOPICS[kind][0]),[language,setLanguage]=useState('en'),[level,setLevel]=useState('intermediate'),[side,setSide]=useState('');
  const [session,setSession]=useState(null),[draft,setDraft]=useState(''),[closing,setClosing]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[micConsent,setMicConsent]=useState(false),[restart,setRestart]=useState(false);
  const [autoSpeak,setAutoSpeak]=useState(true),[handsFree,setHandsFree]=useState(false),[rate,setRate]=useState(.95),[voiceURI,setVoiceURI]=useState('');
  const autoSpeakRef=useRef(autoSpeak);autoSpeakRef.current=autoSpeak;
  const abort=useRef(),alive=useRef(true),end=useRef(),busyRef=useRef(false);
  const voice=useVoice(language,text=>setDraft(v=>(v+' '+text).trim().slice(0,1800)),{rate,voiceURI,autoTurn:handsFree,onComplete:text=>{if(session&&!finished&&turns<max&&!busyRef.current)request('turn',[...session.history,{role:'user',content:text}],session.id);},onPlaybackEnd:()=>{if(handsFree&&micConsent&&session&&!finished&&turns<max&&!busyRef.current){setDraft('');voice.start();}}});
  const turns=session?.history.filter(m=>m.role==='user').length||0,max=debate?3:6,finished=!!session?.result;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current?.abort()}},[]);
  useEffect(()=>{end.current?.parentElement?.scrollTo({top:end.current.parentElement.scrollHeight,behavior:prefs.reduceMotion?'instant':'smooth'})},[session?.history.length]);
  async function request(phase,history,id){
    if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');voice.stop();voice.silence();abort.current=new AbortController();
    try{
      const result=await api('/conversation/'+phase,'POST',{kind,topic,language,level,side,history,closing,...choice.payload},abort.current.signal);
      if(!alive.current)return;
      if(phase==='turn'){setSession({id,history:[...history,{role:'assistant',content:result.reply}],hint:result.hint});setDraft('');if(autoSpeakRef.current)voice.speak(result.reply);}
      else{
        let coins=0;if(debate){const reward=transact('activity',{id,kind:'debate',scores:result.scores});if(reward.error)throw new Error(reward.error);coins=reward.coins;playSound('reward')}
        const entry={id,kind,topic,side,language,date:new Date().toISOString(),result,coins};
        setSession(v=>({...v,result,coins}));setPrefs(p=>({...p,conversationHistory:[entry,...(Array.isArray(p.conversationHistory)?p.conversationHistory:[])].slice(0,30)}));
        notify(tr(debate?'Debate feedback saved.':'Speaking feedback saved.'));
      }
    }catch(e){if(alive.current&&e.name!=='AbortError')setError(e.message)}finally{busyRef.current=false;if(alive.current)setBusy(false)}
  }
  function newSession(){setHandsFree(false);voice.cancel();voice.silence();setSession(null);setDraft('');setClosing('');setError('');setRestart(false)}
  const history=(Array.isArray(prefs.conversationHistory)?prefs.conversationHistory:[]).filter(x=>x.kind===kind);
  return <div className={s.page} data-activity={kind}>
    <header className={s.hero}><div><span className={s.eyebrow}><Mic size={17}/> SPEAKING ROOM</span><h1>{debate?'A conversation. Two perspectives.':'Let’s talk.'}</h1><p>{debate?'Practise a real exchange of arguments with your animated AI opponent.':'Speak with Alex, your animated AI partner. Listen, respond, and build confidence one conversation at a time.'}</p><div className={s.chips}><span>{debate?'3 rounds + your closing summary':'2–6 turns · your own pace'}</span><span>Voice or text</span></div></div></header>
    <SpeakingPartner state={voice.speaking?'speaking':voice.listening?'listening':busy?'thinking':finished?'finished':'ready'} caption={busy?'Give me a moment to think about that…':session?.history.filter(m=>m.role==='assistant').at(-1)?.content} voice={voice} autoSpeak={autoSpeak} setAutoSpeak={setAutoSpeak} rate={rate} setRate={setRate} voiceURI={voiceURI} setVoiceURI={setVoiceURI} canListen={!!session&&!finished&&turns<max&&!busy&&voice.supported&&micConsent} onListen={session&&!finished?()=>{if(voice.listening)voice.stop();else{setDraft('');voice.start();}}:null} onPause={()=>{setHandsFree(false);voice.silence();}} onPreview={()=>voice.speak({en:'Hello, I’m Alex, your AI speaking partner. Choose a topic and let’s talk.',de:'Hallo, ich bin Alex, dein KI-Gesprächspartner. Worüber möchtest du sprechen?',fr:'Bonjour, je suis Alex. De quoi aimerais-tu parler ?',es:'Hola, soy Alex. ¿De qué te gustaría hablar?',zh:'你好，我是你的人工智能口语伙伴。我们一起练习吧。'}[language],{resume:false})}/>
    <AIChoice choice={choice} disabled={busy||!!session}/>
    {choice.status&&!choice.ready&&<p className={s.notice} role="status">{tr('Your selected AI is not ready. Start the local model or configure a cloud provider, then try again. This page never invents AI replies.')}</p>}
    {!session?<section className={s.setup}>
      <div><span className={s.eyebrow}>{tr('01 / SET THE SCENE')}</span><h2>{tr(debate?'Which idea will you challenge?':'What shall we talk about?')}</h2><div className={s.topicGrid}>{TOPICS[kind].map(t=><button key={t} aria-pressed={topic===t} onClick={()=>setTopic(t)} disabled={busy}>{tr(t)}<ArrowRight size={16}/></button>)}</div><label>{tr('Or choose your own topic')}<input value={topic} maxLength={300} disabled={busy} onChange={e=>setTopic(e.target.value)}/></label></div>
      <aside className={s.setupAside}><label>{tr('Practice language')}<select value={language} disabled={busy} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>{tr('Level')}<select value={level} disabled={busy} onChange={e=>setLevel(e.target.value)}>{['beginner','intermediate','advanced'].map(l=><option key={l}>{l}</option>)}</select></label>{debate&&<fieldset><legend>{tr('Your side')}</legend><div className={s.sides}>{[['for','For the motion'],['against','Against the motion']].map(([v,l])=><button key={v} disabled={busy} aria-pressed={side===v} onClick={()=>setSide(v)}>{side===v&&<Check size={15}/>} {tr(l)}</button>)}</div></fieldset>}<p className={s.fine}>{tr(debate?'Your AI opponent takes the other side. Scores reward reasoning, evidence, rebuttal and clarity, regardless of which side you choose.':'Your buddy asks questions and models useful phrases. Feedback covers your words and ideas; pronunciation and accent are not graded.')}</p><button className={s.primary} disabled={busy||!choice.ready||topic.trim().length<5||debate&&!side} onClick={()=>request('turn',[],crypto.randomUUID())}>{busy?tr('Preparing your conversation…'):tr(debate?'Enter the arena':'Start a conversation')}<ArrowRight size={17}/></button></aside>
    </section>:<div className={s.sessionLayout}>
      <section className={s.conversation}><header className={s.sessionHead}><div><span className={s.eyebrow}>{tr(debate?'YOUR MOTION':'YOUR TOPIC')}</span><h2>{topic}</h2></div><span>{turns}/{max} {tr('turns')}</span></header><div className={s.transcript} role="log" aria-label={tr('Conversation transcript')}>{session.history.map((m,i)=><article key={i} className={m.role==='user'?s.userMessage:s.aiMessage}><div><strong>{tr(m.role==='user'?'You':debate?'AI opponent':'AI speaking partner')}</strong>{m.role==='assistant'&&voice.canSpeak&&<button aria-label={tr('Listen to reply')+' '+(i+1)} disabled={busy||voice.listening} onClick={()=>voice.speak(m.content,{resume:false})}><Volume2 size={15}/></button>}</div><TutorText text={m.content}/></article>)}<div ref={end}/></div>
      {voice.speaking&&<button className={s.quiet} onClick={voice.silence}><VolumeX size={16}/>{tr('Stop audio')}</button>}
      {!finished&&turns<max&&<form className={s.composer} onSubmit={e=>{e.preventDefault();if(!draft.trim()||busy||voice.listening)return;request('turn',[...session.history,{role:'user',content:draft.trim()}],session.id)}}>
        <label>{tr(debate?'Your next argument':'Your reply')}<textarea value={draft} maxLength={1800} rows={4} disabled={busy||voice.listening} onChange={e=>setDraft(e.target.value)} placeholder={tr('Speak, review the transcript, then send. You can also type.')}/></label>
        {voice.interim&&<p className={s.interim} role="status">{voice.interim}</p>}
        {voice.supported?<label className={s.consent}><input type="checkbox" checked={micConsent} disabled={busy||voice.listening} onChange={e=>setMicConsent(e.target.checked)}/><span>{tr('Enable microphone dictation. My browser may send audio to its speech service, even when the AI is local. Aster sends only the text I submit to the chosen AI.')}</span></label>:<p className={s.fine}>{tr('Voice input is not supported in this browser. Open Aster in Chrome or Edge to try dictation, or type here.')}</p>}
        {voice.supported&&<label className={s.consent}><input type="checkbox" checked={handsFree} disabled={!micConsent||busy||voice.listening} onChange={e=>setHandsFree(e.target.checked)}/><span>Conversation mode: after I pause, send my spoken words automatically. Listen again after Alex finishes. Turn this off to review each transcript before sending.</span></label>}
        <div className={s.row}><button type="button" className={voice.listening?s.recording:s.secondary} disabled={busy||!voice.supported||!micConsent} onClick={voice.listening?voice.stop:()=>{setDraft('');voice.start();}}>{voice.listening?<MicOff size={17}/>:<Mic size={17}/>} {tr(voice.listening?'Stop recording':'Speak')}</button><span className={s.fine}>{voice.listening?tr('Listening · stops after 60 seconds'):draft.length+'/1800'}</span><button className={s.primary} disabled={!draft.trim()||busy||voice.listening||!choice.ready}><Send size={16}/>{tr(debate?'Send argument':'Send reply')}</button></div>
      </form>}
      {!finished&&turns>=(debate?3:2)&&<section className={s.closing}><Flag size={20}/><h3>{tr(debate?'Bring your argument together.':'Ready to reflect?')}</h3>{debate?<label>{tr('Your closing summary')}<textarea rows={4} maxLength={2000} disabled={busy} value={closing} onChange={e=>setClosing(e.target.value)} placeholder={tr('Summarise your case, respond to the strongest objection, and explain your conclusion. At least 40 characters.')}/></label>:<p>{tr('Finish now for feedback, or continue up to six turns.')}</p>}<button className={s.primary} disabled={busy||voice.listening||!choice.ready||debate&&closing.trim().length<40} onClick={()=>request('evaluate',session.history,session.id)}><Sparkles size={16}/>{tr('Finish & get feedback')}</button></section>}
      </section>
      <aside className={s.coach}><span className={s.eyebrow}>{tr('IN YOUR CORNER')}</span><h3>{tr(debate?'Ideas worth defending.':'You have something to say.')}</h3>{debate&&<span className={s.sideBadge}>{tr(side==='for'?'You are for the motion':'You are against the motion')}</span>}<p>{session.hint}</p><ul>{(debate?['Make one clear claim.','Explain why it matters.','Use a real example.','Address the opposing argument.']:['Take your time.','Try a complete sentence.','Give a reason or an example.','Ask a question in return.']).map(t=><li key={t}>{tr(t)}</li>)}</ul><div className={s.fine}><ShieldCheck size={16}/><p>{tr('AI can make mistakes. Sessions stay on this page until you leave. Only completed feedback summaries are saved. No microphone audio is stored by Aster.')}</p></div><button className={s.quiet} disabled={busy} onClick={()=>finished?newSession():setRestart(true)}>{tr('Start a new session')}</button>{restart&&<div className={s.notice}><p>{tr('Leave this unfinished conversation? Its transcript will be lost.')}</p><button onClick={newSession}>{tr('Start new')}</button> <button onClick={()=>setRestart(false)}>{tr('Keep practising')}</button></div>}</aside>
    </div>}
    {busy&&<div className={s.pending} role="status"><span className={s.dots}/>{tr('Your AI partner is thinking…')}<button onClick={()=>abort.current?.abort()}><X size={15}/>{tr('Cancel')}</button></div>}
    {(error||voice.error)&&<p className={s.error} role="alert">{error||voice.error}</p>}
    {finished&&<section className={s.feedback}><header><div><span className={s.eyebrow}>{tr('YOUR SESSION, REFLECTED')}</span><h2>{tr(debate?'A stronger argument starts here.':'Progress you can hear next time.')}</h2></div>{debate&&<span className={s.coinPill}><Coins size={22}/>+{session.coins}</span>}</header><div className={s.scores}>{Object.entries(session.result.scores).map(([key,value])=><div key={key}><strong>{value}<small>/5</small></strong><span>{tr(key)}</span><meter min="0" max="5" value={value}/></div>)}</div><p><strong>{tr('Total score')}: {Object.values(session.result.scores).reduce((n,v)=>n+v,0)}/20</strong></p><TutorText text={session.result.summary}/><div className={s.feedbackGrid}><article><h3>{tr('Keep doing this')}</h3><p>{session.result.strength}</p></article><article><h3>{tr('Try this next')}</h3><p>{session.result.nextStep}</p></article></div><p className={s.fine}>{tr(debate?'Practice score /20. Coins = half the score, rounded down, with a maximum of 10. Daily boosts do not increase debate rewards.':'Feedback is based on your transcript, not pronunciation, fluency timing or accent.')} {tr('This is AI practice feedback, not an official assessment.')}</p></section>}
    {history.length>0&&!session&&<section className={s.history}><h2>{tr('Your recent practice')}</h2>{history.slice(0,5).map(item=><details key={item.id}><summary>{item.topic}<small>{new Date(item.date).toLocaleDateString()} {item.kind==='debate'?'· '+item.coins+' coins':''}</small></summary><p><strong>{tr('Total score')}: {Object.values(item.result.scores).reduce((n,v)=>n+v,0)}/20</strong></p><p>{Object.entries(item.result.scores).map(([key,value])=>tr(key)+': '+value+'/5').join(' · ')}</p><p>{item.result.summary}</p><p>{item.result.strength}</p><p><strong>{tr('Next step')}: </strong>{item.result.nextStep}</p></details>)}</section>}
  </div>;
}
