import {EXTRA_BOOKS} from './bookExpansion.js';
import {MODERN_BOOKS} from './modernBooks.js';
import moreBooks from './libraryExpansion.json' with {type:'json'};
export const BOOKS_KEY='aster-reading-v1';
const open=(id,title,subject,stages,description,topics)=>({id,title,subject,stages,description,topics,author:'OpenStax · Rice University',access:'open',url:`https://openstax.org/details/books/${id}`,source:`https://openstax.org/details/books/${id}`,connection:'Optional preparation',rights:'Read the full book free on the publisher’s site. OpenStax provides an authorized web edition and PDF; see the book’s current licence and attribution terms.',language:'English'});
const classic=(id,title,author,number,subject,stages,description,topics,local)=>({id,title,author,subject,stages,description,topics,access:'public-domain',url:`https://www.gutenberg.org/ebooks/${number}`,source:`https://www.gutenberg.org/ebooks/${number}`,connection:'Optional wider reading',rights:'Public-domain original text. This Project Gutenberg edition includes its licence and source credits. Modern translations, adaptations, or annotated editions may have separate copyrights.',language:'English',local});
export const BOOKS=[
 ...MODERN_BOOKS,
 ...EXTRA_BOOKS,
 ...moreBooks,
 {id:'herz-boxers',title:'Das Herz eines Boxers',author:'Lutz Hübner',subject:'german',stages:['Grade 8'],description:'A modern drama about an unexpected friendship across generations. ISR’s current unit studies the play through Deutschbuch, Chapter 9.',topics:['Drama','Dialogue','Character'],access:'publisher',url:'https://www.westermann.de/artikel/978-3-14-022707-0/EinFach-Deutsch-Textausgaben-Lutz-Huebner-Das-Herz-eines-Boxers',source:'https://lms.isr-school.com/homepage/728',connection:'ISR current unit',school:true,language:'German',rights:'Publisher purchase/information page. No authorized free full text has been verified. The linked standalone edition is not confirmed as the edition your teacher requires; use the class material or ask before buying.'},
 {id:'dorfteich',title:'Der Tote im Dorfteich',subtitle:'In Einfacher Sprache',author:'Franziska Gehm · adapted by Yvette Wagner',subject:'german',stages:['Grade 8'],description:'The simplified edition named in ISR’s Grade 8 German summer-reading unit. This is an earlier unit in the current course outline.',topics:['Reading','Narrative','German'],access:'publisher',url:'https://www.beltz.de/kinder_jugendbuch/produkte/produkt_produktdetails/39396-der_tote_im_dorfteich_in_einfacher_sprache.html',preview:'https://www.beltz.de/fileadmin/beltz/leseproben/978-3-407-74690-0.pdf',source:'https://lms.isr-school.com/homepage/727',connection:'ISR earlier summer reading',school:true,language:'German',rights:'Authorized publisher preview only; the full book requires a legitimate purchase or library copy. Confirm the edition with your teacher.'},
 open('prealgebra-2e','Prealgebra 2e','maths',['Grade 8'],'Revisit arithmetic and early algebra with worked examples. Pick the sections that support your current maths topics.',['Integers','Fractions','Roots','Equations']),
 open('elementary-algebra-2e','Elementary Algebra 2e','maths',['Grade 8','IGCSE'],'Develop fluency with algebraic notation, equations, graphing, and polynomial expressions.',['Equations','Graphs','Polynomials']),
 open('intermediate-algebra-2e','Intermediate Algebra 2e','maths',['IGCSE'],'Extend your algebra with functions, quadratics, and more involved symbolic work. Use alongside your exact course syllabus.',['Functions','Quadratics','Algebra']),
 open('algebra-and-trigonometry-2e','Algebra and Trigonometry 2e','maths',['IGCSE','IB'],'An extensive reference for functions and trigonometry. Choose chapters with your teacher; this is not an exam-board textbook.',['Functions','Trigonometry','Modelling']),
 open('precalculus-2e','Precalculus 2e','maths',['IB'],'Optional preparation in functions and trigonometric ideas before more advanced mathematical study.',['Functions','Sequences','Trigonometry']),
 open('calculus-volume-1','Calculus Volume 1','maths',['IB'],'An advanced reference for selected calculus topics. Match chapters to your IB mathematics route and level.',['Limits','Derivatives','Integrals']),
 open('concepts-biology','Concepts of Biology','science',['Grade 8','IGCSE'],'Explore biological systems, cells, and living processes through an introductory science text.',['Cells','Genetics','Ecology']),
 open('biology-2e','Biology 2e','science',['IB'],'A broad biology reference for deeper reading. Some material goes beyond school requirements.',['Cell biology','Evolution','Organisms']),
 open('chemistry-2e','Chemistry 2e','science',['IB'],'Use selected sections to strengthen chemical explanations and quantitative reasoning.',['Atoms','Bonding','Reactions']),
 open('physics','Physics','science',['IGCSE','IB'],'A high-school physics reference for building explanations and practising quantitative problems.',['Motion','Energy','Waves']),
 open('world-history-volume-2','World History Volume 2, from 1400','social',['IGCSE','IB'],'Compare events and perspectives across the modern world. Follow your course’s particular historical scope.',['World history','Sources','Change']),
 open('writing-guide','Writing Guide with Handbook','english',['IGCSE','IB'],'A reference for developing arguments, considering audience, and revising your writing.',['Argument','Research','Revision']),
 open('introduction-philosophy','Introduction to Philosophy','social',['IB'],'Optional exploration of knowledge, reasoning, and philosophical questions. A companion for curiosity, not an official TOK textbook.',['Knowledge','Logic','Ethics']),
 {id:'think-python',title:'Think Python',subtitle:'Third edition',author:'Allen B. Downey',subject:'computing',stages:['Grade 8','IGCSE','IB'],description:'A free, author-published introduction to Python with explanations, notebooks, and exercises.',topics:['Python','Problem solving','Programming'],access:'open',url:'https://allendowney.github.io/ThinkPython/',source:'https://greenteapress.com/wp/think-python-3rd-edition/',connection:'Optional preparation',language:'English',rights:'Authorized free online book, CC BY-NC-SA 4.0. Copyright Allen B. Downey; retain attribution and licence terms for reuse.'},
 {id:'music-theory',title:'Open Music Theory',subtitle:'Version 2',author:'Mark Gotham and contributing authors',subject:'music',stages:['Grade 8','IGCSE','IB'],description:'Start with the fundamentals and explore rhythm, harmony, and notation. Later material is written for undergraduate study.',topics:['Rhythm','Harmony','Notation'],access:'open',url:'https://viva.pressbooks.pub/openmusictheory/',source:'https://viva.pressbooks.pub/openmusictheory/',connection:'Optional preparation',language:'English',rights:'Authorized open textbook. Creative Commons Attribution-ShareAlike; consult the site for section-specific credits and exceptions.'},
 {id:'acceso',title:'Acceso',author:'University of Kansas',subject:'spanish',stages:['IGCSE','IB'],description:'An open Spanish curriculum exploring language and cultural perspectives. Use selected modules appropriate to your current proficiency.',topics:['Spanish','Culture','Communication'],access:'open',url:'https://acceso.ku.edu/index.shtml',source:'https://acceso.ku.edu/index.shtml',connection:'Optional wider study',language:'Spanish',rights:'Authorized open-access curriculum. Read on the university’s site and check its licensing page for reuse conditions.'},
 classic('carol','A Christmas Carol','Charles Dickens',46,'english',['Grade 8','IGCSE'],'Explore transformation, social responsibility, and Dickens’s use of narrative voice. Optional reading; not confirmed as your ISR set text.',['Character','Theme','Victorian fiction'],'/books/a-christmas-carol.txt'),
 classic('frankenstein','Frankenstein','Mary Wollstonecraft Shelley',84,'english',['IGCSE','IB'],'Consider responsibility, belonging, and narrative perspective in this influential novel.',['Gothic fiction','Narrative','Ethics'],'/books/frankenstein.txt'),
 classic('time-machine','The Time Machine','H. G. Wells',35,'english',['Grade 8','IGCSE'],'Explore speculative fiction and the way imagined futures reflect questions about society.',['Science fiction','Society','Narrative'],'/books/the-time-machine.txt'),
 classic('pride','Pride and Prejudice','Jane Austen',1342,'english',['IGCSE','IB'],'Read for irony, social expectations, character, and the relationship between judgment and evidence.',['Irony','Character','Society']),
 classic('midsummer','A Midsummer Night’s Dream','William Shakespeare',1514,'drama',['Grade 8','IGCSE'],'Explore performance, mistaken identity, and the interplay of different theatrical worlds.',['Comedy','Performance','Language']),
 classic('romeo','Romeo and Juliet','William Shakespeare',1513,'drama',['IGCSE','IB'],'Read or perform scenes to investigate dramatic structure, conflict, and imagery.',['Tragedy','Conflict','Imagery'])
];
export const ACCESS_LABELS={open:'Open full text','public-domain':'Public-domain full text',publisher:'Publisher / library copy'};
export function normalizeReading(input){if(!input||typeof input!=='object')return {};return Object.fromEntries(Object.entries(input).filter(([id,v])=>BOOKS.some(b=>b.id===id)&&v&&typeof v==='object').map(([id,v])=>[id,{saved:v.saved===true,status:['not-started','reading','finished'].includes(v.status)?v.status:'not-started',progress:Number.isFinite(v.progress)?Math.min(100,Math.max(0,Math.round(v.progress))):0,page:Number.isInteger(v.page)&&v.page>=0?Math.min(v.page,1000):0,notes:typeof v.notes==='string'?v.notes.slice(0,2000):''}]));}
export function paginateBook(raw,target=4200){
 const start=raw.indexOf('*** START OF THE PROJECT GUTENBERG EBOOK'),end=raw.indexOf('*** END OF THE PROJECT GUTENBERG EBOOK');
 if(start<0||end<start)throw new Error('The book text could not be verified. Open its original source instead.');
 const body=raw.slice(raw.indexOf('\n',start)+1,end).replace(/\r/g,'').trim();const paragraphs=body.split(/\n\s*\n/).map(p=>p.replace(/\n/g,' ').replace(/ +/g,' ').trim()).filter(Boolean);const pages=[];let page=[],size=0;
 for(const paragraph of paragraphs){if(size+paragraph.length>target&&page.length){pages.push(page);page=[];size=0;}page.push(paragraph);size+=paragraph.length;}if(page.length)pages.push(page);return pages;
}
