export const BUDDIES=[
 ['dino','Blue','Dinosaur','#63b3ed','Curious explorer'],['fox','Ember','Fox','#ef9b69','Creative thinker'],['cat','Luna','Cat','#b49ae8','Quiet problem solver'],['rabbit','Clover','Rabbit','#96c8a6','Patient listener'],['panda','Mochi','Panda','#9bacc5','Calm study partner'],['dragon','Nova','Dragon','#8e9ef4','Big idea collector'],['penguin','Pip','Penguin','#649fc3','Steady adventurer'],['axolotl','Bubbles','Axolotl','#e99ec2','Question enthusiast'],['owl','Atlas','Owl','#b99c75','Thoughtful guide'],['turtle','Sage','Turtle','#78b898','One step at a time']
].map(([id,name,species,color,trait])=>({id,name,species,color,trait}));
export const SHOP=[
 ['berry','Berry bowl','food',6,'#c774a5'],['apple','Crisp apple','food',4,'#82b767'],['cookie','Star biscuit','food',8,'#d5aa61'],['smoothie','Ocean smoothie','food',12,'#67bdd1'],['scarf','Sunset scarf','clothes',25,'#ee9c73'],['hoodie','Explorer hoodie','clothes',45,'#879de2'],['bow','Rose bow tie','clothes',20,'#dc80ac'],['stars','Starlight sweater','clothes',55,'#aaa0e7'],['cap','Adventure cap','accessories',30,'#7bbcb4'],['crown','Little crown','accessories',75,'#ebc571'],['glasses','Round glasses','accessories',35,'#97b5cf'],['flower','Daisy clip','accessories',18,'#e9bd82']
,
 ['ramen','Study-break ramen','food',16,'#dba66e'],['sushi','Sushi picnic','food',14,'#80baa8'],['cocoa','Cosy cocoa','food',10,'#ae9179'],['watermelon','Watermelon slice','food',5,'#df8795'],
 ['denim','Blue denim jacket','clothes',48,'#568ec0'],['blazer','Midnight blazer','clothes',65,'#3b5679'],['labcoat','Discovery lab coat','clothes',60,'#d7e5e9'],['jersey','Varsity jersey','clothes',40,'#7dab87'],['astronaut','Orbital flight suit','clothes',95,'#b3bbd8'],['raincoat','Sunshine raincoat','clothes',42,'#d8b952'],['striped','Coastal knit','clothes',38,'#61989d'],['cosmic','Cosmic hoodie','clothes',85,'#7860b0'],['formal','Evening waistcoat','clothes',70,'#72587c'],['sakura','Sakura jacket','clothes',58,'#d08fa4'],['mintscarf','Aurora scarf','clothes',28,'#72bbaa'],['royalscarf','Royal scarf','clothes',32,'#9f7aba'],
 ['headphones','Studio headphones','accessories',55,'#727fab'],['beanie','Cloud beanie','accessories',32,'#91acc9'],['beret','Artist’s beret','accessories',38,'#b99385'],['tophat','Midnight top hat','accessories',65,'#526781'],['wizard','Stargazer hat','accessories',80,'#8e76bf'],['halo','Golden halo','accessories',90,'#dfc276'],['visor','Future visor','accessories',72,'#74bfca'],['sunglasses','Weekend sunglasses','accessories',40,'#657787'],['headband','Sprint headband','accessories',24,'#d09387'],['leaf','Forest sprout','accessories',22,'#81b59b'],['bowclip','Satin hair bow','accessories',27,'#ce8faf'],['earmuffs','Winter earmuffs','accessories',45,'#bab7d8']
].map(([id,name,type,price,color])=>({id,name,type,price,color}));
export function normalizeBuddy(value={}){value=value&&typeof value==='object'?value:{};const chosen=BUDDIES.find(b=>b.id===value.id)||BUDDIES[0],owned=Array.isArray(value.owned)?[...new Set(value.owned.filter(id=>SHOP.some(i=>i.id===id&&i.type!=='food')))]:[];const count=v=>Number.isFinite(Number(v))?Math.max(0,Math.min(1e9,Math.floor(Number(v)))):0;return{id:chosen.id,adopted:value.adopted===true,name:typeof value.name==='string'&&value.name.trim()?value.name.slice(0,24):chosen.name,color:/^#[0-9a-f]{6}$/i.test(value.color)?value.color:chosen.color,spent:count(value.spent),fed:count(value.fed),owned,clothes:owned.includes(value.clothes)&&SHOP.some(i=>i.id===value.clothes&&i.type==='clothes')?value.clothes:'',accessory:owned.includes(value.accessory)&&SHOP.some(i=>i.id===value.accessory&&i.type==='accessories')?value.accessory:''};}
export function buyForBuddy(value,itemId,earned){const buddy=normalizeBuddy(value),item=SHOP.find(i=>i.id===itemId);if(!item)return{buddy,error:'Item not found.'};if(item.type!=='food'&&buddy.owned.includes(item.id))return{buddy,error:'You already own this item.'};if(Math.max(0,earned-buddy.spent)<item.price)return{buddy,error:'Not enough coins'};const next={...buddy,spent:buddy.spent+item.price};if(item.type==='food')next.fed++;else{next.owned=[...buddy.owned,item.id];next[item.type==='clothes'?'clothes':'accessory']=item.id;}return{buddy:next,item};}
