// Original Learnify passages and questions. These are not Cambridge examination materials.
export const READING_SETS=[
 {id:'station',level:'Secondary 7',title:'The last light at the station',genre:'Fiction',skill:'Retrieval & inference',text:'Mara reached the station just as the ticket office shutter rattled down. Across the platform, a single lamp made a small island in the fog. She checked the clock: seven minutes until the last train. Her brother had promised to meet her, but the bench beneath the lamp was empty.\n\nShe took his letter from her pocket. The paper was soft at the folds; she had opened it on every bus since leaving home. “Wait where we always waited,” he had written. Mara looked again at the bench, then smiled at her mistake. When they were children, they had waited behind the station, where the driver fed a ginger cat.\n\nFrom the lane came a familiar whistle. Mara folded the letter carefully this time.',questions:[
 ['How long remains before the train?',['Five minutes','Seven minutes','Ten minutes','The text does not say'],1,'The clock tells Mara that seven minutes remain.'],
 ['Why is the paper soft at the folds?',['It has been repeatedly opened','It was left in the rain','It is newly printed','The cat damaged it'],0,'She has opened it on every bus, so repeated handling has softened the folds.'],
 ['Why does Mara smile?',['The train is cancelled','She remembers the correct meeting place','She finds a new letter','The clock is wrong'],1,'She realises that “where we always waited” means the lane behind the station.']
 ],written:[['Explain what “a small island in the fog” suggests.','The lamp creates a small, isolated patch of light surrounded by darkness and fog. The comparison makes the station feel quiet and uncertain.'],['How does the ending suggest a change in Mara’s feelings?','The familiar whistle suggests her brother has arrived. Folding the letter carefully contrasts with her repeated, anxious checking earlier, suggesting relief.']]},
 {id:'garden',level:'Secondary 7',title:'A roof with roots',genre:'Non-fiction',skill:'Main ideas & evidence',text:'The roof of Elm Street Library used to be covered in grey gravel. Now it holds twelve raised beds, a rainwater tank, and a path wide enough for a wheelchair. Volunteers grow herbs and vegetables there, but food is only part of the project.\n\nBefore work began, an engineer checked how much weight the roof could support. The beds use lightweight soil, and visitors follow a limit on group size. A teacher brings her class once a month to measure plant growth. The results are sometimes disappointing: last year, strong winds damaged the bean plants. This year, a screen shelters them.\n\nThe library manager calls the garden an experiment, not a finished success. She keeps a notebook of what fails as carefully as a list of what flourishes.',questions:[
 ['Who checked the roof before construction?',['A gardener','An engineer','A pupil','A cook'],1,'The passage explicitly states that an engineer checked the roof’s weight capacity.'],
 ['Why was a screen added?',['To hide the vegetables','To stop all sunlight','To protect plants from wind','To collect books'],2,'Strong winds damaged the beans, so the new screen shelters them.'],
 ['Which best describes the manager’s attitude?',['She hides mistakes','She values learning from failure','She thinks the garden is complete','She cares only about profit'],1,'She records what fails as carefully as what succeeds.']
 ],written:[['Give two details showing that the project considers access or safety.','The wide path accommodates a wheelchair. An engineer checked the roof’s load, lightweight soil is used, and group sizes are limited. Any two supported details are suitable.'],['Summarise why the garden is more than a source of food.','It provides an accessible shared space, a place for students to measure growth, and an ongoing experiment in adapting growing methods.']]},
 {id:'bridge',level:'Secondary 8–9',title:'The bridge between them',genre:'Fiction',skill:'Character & language',text:'When Arun returned to the village, the old wooden bridge was gone. In its place stood a steel span, neat and silent. His grandmother ran her hand along the new rail. “It no longer sings when you cross,” she said. Arun remembered the boards answering every footstep with a different complaint.\n\nHe wanted to tell her about the new bridge’s strength, its smooth path, the hours saved by the workers who could now bring carts across. Instead, he asked whether she missed the old one.\n\n“I miss being quick enough to run over it,” she replied. Then she tapped the steel rail. “This one will do.”\n\nOn the far bank, a child raced past them on a bicycle. Arun stepped aside and watched his grandmother lift her hand in greeting.',questions:[
 ['What replaced the wooden bridge?',['A tunnel','A steel bridge','A ferry','A stone path'],1,'The replacement is described as a steel span.'],
 ['What does “the boards answering” do?',['Gives the boards human-like behaviour','Makes a factual claim about speech','Shows a direct quotation','Uses a numerical comparison'],0,'The boards are personified as answering and complaining through their creaks.'],
 ['What does the grandmother mainly miss?',['Being young and able to run','The workers’ carts','The new rail','The bicycle'],0,'She directly says she misses being quick enough to run over the bridge.']
 ],written:[['How does the dialogue complicate Arun’s assumption?','Arun assumes she misses the old structure and prepares a practical defence of the new one. Her reply reveals a personal longing for youth rather than opposition to better engineering.'],['Explain one effect of the child in the final paragraph.','The moving child contrasts with the grandmother’s remembered youth and shows that the bridge now serves a new generation. Her greeting suggests acceptance rather than resentment.']]},
 {id:'night',level:'Secondary 8–9',title:'When the town dimmed its lights',genre:'Non-fiction',skill:'Argument & evaluation',text:'For one month, Bellford switched off decorative street lighting after midnight. Lights at crossings and on busy walking routes stayed on. Supporters expected lower electricity use and a clearer view of the stars. Critics worried that darker streets would feel less welcoming.\n\nThe council recorded an eighteen per cent fall in electricity used by the public lighting covered by the trial. This was not the town’s total electricity use. A survey attracted two hundred replies, mostly from residents who had attended a meeting about the change. Three quarters supported continuing.\n\nThe local astronomy club called the trial a success. A shop owner asked for a longer test during winter, when evenings are darker and more people walk home after sunset. The council agreed to collect further evidence before deciding.',questions:[
 ['Which lights remained on?',['All decorative lights','Crossings and busy walking routes','No lights','Only shop signs'],1,'The first paragraph distinguishes safety-related routes from decorative lighting.'],
 ['What fell by eighteen per cent?',['The town’s total electricity use','All household bills','Electricity for lighting covered by the trial','The number of residents'],2,'The statistic applies specifically to the public lighting included in the trial.'],
 ['What limits the survey evidence?',['It has no responses','Many respondents came from the same interested group','It asked about a different town','All residents were required to reply'],1,'Meeting attendees are not necessarily representative of all residents.']
 ],written:[['Explain why the shop owner requests a winter test.','Winter has longer dark periods and different walking patterns. Evidence collected then could show effects that a one-month trial in another season missed.'],['Write a balanced two-sentence summary of the evidence.','The trial reduced electricity used by the affected lights, and most survey respondents supported it. However, the respondents may not represent all residents, and the effects in winter remain uncertain.']]},
 {id:'harbour',level:'IGCSE preparation',title:'A harbour before dawn',genre:'Fiction',skill:'Writer’s effects & inference',text:'The harbour lay under a lid of cloud. On the quay, Leila found her father beside the boat, untangling a rope that seemed determined to knot itself again. He did not look up when she set down her suitcase.\n\n“You will miss the bus,” he said.\n\n“There is another.”\n\nBeyond the harbour wall, the water was turning silver. For years, Leila had imagined leaving this place as a door swinging open. Now, with the ticket in her coat, she noticed the chipped blue paint on the boat and the precise way her father laid each loop of rope beside the next.\n\nHe finally straightened and took the suitcase, though it was hardly heavy. Together they walked towards the road. Behind them, a gull broke the silence with a harsh, ordinary cry.',questions:[
 ['Which detail most clearly shows Leila is preparing to leave?',['The cloud','Her ticket and suitcase','The rope','The gull'],1,'The ticket and suitcase are direct evidence of an intended journey.'],
 ['What does the “door swinging open” image suggest?',['New freedom and opportunity','A literal broken door','A wish to remain trapped','A storm approaching'],0,'The metaphor connects departure with access to new possibilities.'],
 ['What does her father carrying the light suitcase most plausibly suggest?',['He dislikes walking','A practical gesture of care','He plans to steal it','The suitcase is dangerous'],1,'His action offers quiet support even though the case does not require his strength.']
 ],written:[['Select two details and explain how the writer makes departure emotionally complicated.','The imagined open door suggests freedom, while Leila’s new attention to the chipped paint and her father’s precise movements conveys attachment to familiar life. The contrast suggests excitement mixed with sadness; support your reading with the chosen details.'],['How does the final “ordinary cry” affect the ending?','The gull interrupts an emotionally significant silence with an everyday sound. The harbour’s routine continues despite Leila’s personal turning point, making the departure feel understated rather than dramatic.']]},
 {id:'repair',level:'IGCSE preparation',title:'The case for a repair room',genre:'Persuasive non-fiction',skill:'Summary & response',text:'Every Friday, our school’s lost-property shelves overflow. Some objects have simply been forgotten; others have been abandoned because a strap snapped or a zip failed. Before buying another replacement, we should ask a different question: could we repair what we already have?\n\nA supervised repair room would offer basic tools and instruction. Students could learn to stitch a seam, replace a button, or diagnose a loose connection in a low-voltage classroom kit. It would not accept mains-powered appliances or unsafe repairs. An adult would decide which tasks were suitable.\n\nThere are costs: equipment, training, storage, and staff time. Nor will every repair succeed. Yet the room could turn a discarded bag into a usable one and a frustrated owner into a more capable maker. A small pilot, with recorded costs and outcomes, would tell us whether the idea deserves to grow.',questions:[
 ['What is the writer proposing?',['Replacing the library','A supervised repair room','A ban on bags','Unsupervised electrical repairs'],1,'The proposal is a supervised room for suitable repairs and instruction.'],
 ['Which task is explicitly excluded?',['Replacing a button','Stitching a seam','Repairing mains-powered appliances','Working on a suitable classroom kit'],2,'The text explicitly excludes mains-powered appliances and unsafe repairs.'],
 ['Why acknowledge the costs and possible failures?',['To make the proposal more balanced and credible','To prove every repair is impossible','To remove the need for supervision','To claim the room is free'],0,'Acknowledging limitations anticipates objections and supports a measured pilot rather than an unsupported promise.']
 ],written:[['Summarise the proposed benefits and safeguards in no more than 60 words.','The room could reduce waste, save usable items, and teach practical skills. Suitable repairs would require adult supervision, instruction, and basic tools. Dangerous tasks and mains-powered appliances would be excluded. A small pilot would record costs and results before expansion.'],['Write a short response as a student representative, evaluating the proposal.','A strong response gives a clear position, develops benefits such as skills and reduced waste, weighs staffing and safety costs, and proposes a practical way to assess the pilot. Different positions can be valid if supported by the passage.']]}
];
