import test from 'node:test';import assert from 'node:assert/strict';
import {CURRICULUM,UNITS,normalizeCurriculum,nextUnit} from './curriculum.js';
import {validateExam,dayBefore,berlinDay,buildMock,markMock,normalizeExams} from './mockExams.js';

test('Every curriculum pathway resolves to real guides with complete checkpoints',()=>{assert.equal(new Set(CURRICULUM.map(c=>c.id)).size,CURRICULUM.length);assert.ok(CURRICULUM.length>130);for(const c of CURRICULUM){assert.match(c.url,/^https:\/\/(www\.cambridgeinternational\.org|ibo\.org)\//);assert.ok(c.units.length);for(const id of c.units){const u=UNITS[id];assert.ok(u.concept.length>80);assert.ok(u.example.length>30);assert.equal(u.options.length,4);assert.ok(Number.isInteger(u.a)&&u.a>=0&&u.a<4);assert.ok(u.why.length>15);}}});
test('Study pathway normalization discards invalid records and preserves actual checkpoints',()=>{assert.deepEqual(normalizeCurriculum(null),{saved:[],records:{},examYear:'2027'});const s=normalizeCurriculum({saved:['ig-0580','bad','ig-0580'],records:{'ig-0580/number':{status:'secure'},'bad/no':{status:'secure'}}});assert.deepEqual(s.saved,['ig-0580']);assert.equal(Object.keys(s.records).length,1);assert.equal(nextUnit(CURRICULUM.find(c=>c.id==='ig-0580'),s.records),'algebra');});
test('Day-before preparation uses calendar arithmetic across month, year and leap boundaries',()=>{assert.equal(dayBefore('2026-10-01'),'2026-09-30');assert.equal(dayBefore('2027-01-01'),'2026-12-31');assert.equal(dayBefore('2028-03-01'),'2028-02-29');assert.throws(()=>dayBefore('2026-02-30'));assert.equal(berlinDay(new Date('2026-09-20T22:30:00Z')),'2026-09-21');});
const plan={title:'Algebra rehearsal',date:'2026-09-21',minutes:30,course:'ig-0580',topics:['algebra','quadratics'],cards:[]};
test('A mock contains only selected study-list topics and distinguishes written marking',()=>{const mock=buildMock(plan);assert.equal(mock.questions.length,4);assert.equal(mock.totalMarks,6);assert.deepEqual([...new Set(mock.questions.map(q=>q.topic))],['Algebra & equations','Quadratics & completing the square']);const result=markMock(mock,{'algebra-check':1,'quadratics-check':0,'algebra-explain':'Use equal operations.'});assert.deepEqual({correct:result.correct,objective:result.objective,written:result.written,answered:result.answered},{correct:1,objective:2,written:2,answered:3});assert.equal(result.review[0],'Quadratics & completing the square');});
test('Imported study sets become written questions without invented distractors',()=>{const mock=buildMock({title:'Networks',date:'2026-09-22',minutes:15,cards:[{question:'What does LAN mean?',answer:'Local Area Network'}]});assert.equal(mock.questions[0].type,'written');assert.equal(mock.questions[0].answer,'Local Area Network');assert.equal(markMock(mock,{'card-0':'Anything'}).correct,0);});
test('Exam validation rejects incompatible topics, impossible dates and empty study lists',()=>{assert.throws(()=>validateExam({...plan,topics:['cells']}));assert.throws(()=>validateExam({...plan,date:'not a date'}));assert.throws(()=>validateExam({...plan,topics:[]}));assert.throws(()=>validateExam({...plan,minutes:0}));assert.throws(()=>validateExam({...plan,cards:[{question:'Q',answer:'A'}]}));assert.deepEqual(normalizeExams([{},null]),[]);});
