import test from 'node:test';
import assert from 'node:assert/strict';
import {coinBalance,rewardExams,purchase,adoptBuddy,normalizeEconomy} from './economy.js';
import {validateGrade} from './grades.js';

const exam=(extra={})=>validateGrade({date:'2026-09-20',subject:'Mathematics',title:'Algebra exam',score:91,max:100,scale:'percent',kind:'exam',...extra});
test('one companion is adopted once; purchases keep its identity and adoption',()=>{const prefs=adoptBuddy({},'fox').prefs;assert.equal(prefs.buddy.adopted,true);assert.equal(prefs.buddy.id,'fox');assert.ok(adoptBuddy(prefs,'cat').error);assert.ok(purchase({}, {gems:100},'buddy','apple').error);const result=purchase(prefs,{gems:100},'buddy','headphones');assert.equal(result.prefs.buddy.id,'fox');assert.equal(result.prefs.buddy.adopted,true);assert.equal(result.prefs.buddy.accessory,'headphones');assert.ok(purchase(result.prefs,{gems:100},'buddy','headphones').error);});
test('shop and arcade share one balance, reject overspend, and charge one ticket',()=>{let prefs=adoptBuddy({},'dino').prefs;const progress={gems:12};prefs=purchase(prefs,progress,'buddy','apple').prefs;assert.equal(coinBalance(progress,prefs),8);prefs=purchase(prefs,progress,'game').prefs;assert.equal(coinBalance(progress,prefs),4);prefs=purchase(prefs,progress,'game').prefs;assert.equal(coinBalance(progress,prefs),0);assert.ok(purchase(prefs,progress,'game').error);assert.ok(purchase(prefs,progress,'buddy','apple').error);assert.equal(prefs.economy.tickets,2);});
test('exam bonuses require above 90, actual exam type, eligible scale and a past date',()=>{const today='2026-09-20';for(const grade of [exam({score:90}),exam({kind:'assessment'}),exam({scale:'ib',score:7,max:7}),exam({date:'2026-09-21'})])assert.equal(coinBalance({gems:0},rewardExams({},[grade],today)),0);assert.equal(coinBalance({gems:0},rewardExams({},[exam({score:19,max:20})],today)),50);});
test('deleting, reimporting, changing case or score cannot reclaim the same exam reward',()=>{const today='2026-09-20';let prefs=rewardExams({},[exam(),exam({id:'duplicate'})],today);assert.equal(prefs.economy.gradeRewards.length,1);prefs=rewardExams(prefs,[],today);prefs=rewardExams(prefs,[exam({subject:' MATHEMATICS ',title:' algebra exam ',score:100,id:'new-id'})],today);assert.equal(coinBalance({gems:10},prefs),60);prefs=rewardExams(prefs,[exam({title:'Geometry exam'})],today);assert.equal(coinBalance({gems:10},prefs),110);});
test('malformed economy data does not create negative spending or nonfinite coins',()=>{assert.equal(normalizeEconomy({gameSpent:-5,tickets:Infinity}).gameSpent,0);assert.equal(coinBalance({gems:NaN},{buddy:{spent:Infinity}}),0);});
