export const examProfileTranslations={
de:{
  'Your profile':'Dein Profil','Customize & settings':'Anpassen & Einstellungen','Information':'Informationen','My avatar':'Mein Avatar','My buddy':'Mein Buddy','Workspace settings':'Arbeitsbereich einstellen','You and your buddy. Always together.':'Du und dein Buddy. Immer zusammen.','Person or monster':'Mensch oder Monster','Body shape':'Körperform','Eyes':'Augen','Hair':'Haare','Outfit':'Kleidung','Extra features':'Besonderheiten','Skin color':'Hautfarbe','Hair color':'Haarfarbe','Outfit color':'Kleidungsfarbe','Your profile picture always shows you and your buddy together.':'Dein Profilbild zeigt immer dich und deinen Buddy zusammen.','Personal information':'Persönliche Informationen','Full name':'Vollständiger Name','Telephone number':'Telefonnummer','School information':'Schulinformationen','Grade / year':'Klassenstufe','Class / form':'Klasse','Save profile':'Profil speichern',
  'Exams':'Prüfungen','Exam sections':'Prüfungsbereiche','Corrections':'Korrekturen','Exam corrections':'Prüfungskorrekturen','Prepare before your exam':'Vor der Prüfung üben','Upload photos & fix mistakes':'Fotos hochladen & Fehler verbessern','Upload your marked exam. Fix missed questions. Practise the skills behind them.':'Lade deine korrigierte Prüfung hoch. Verbessere Fehler und übe gezielt.','Write corrections myself':'Korrekturen selbst schreiben','Correct & practise':'Verbessern & üben','YOUR CORRECTION NOTEBOOK':'DEIN KORREKTURHEFT','Make your next answer better.':'Verbessere deine nächste Antwort.','Add a missed question':'Eine fehlerhafte Aufgabe hinzufügen','Save corrections':'Korrekturen speichern','Question from your exam':'Aufgabe aus deiner Prüfung','Your original answer':'Deine ursprüngliche Antwort','Teacher feedback (if provided)':'Rückmeldung der Lehrkraft (falls vorhanden)','I checked these details against my exam.':'Ich habe diese Angaben mit meiner Prüfung verglichen.','Rewrite your answer and show your working':'Schreibe eine neue Antwort mit Lösungsweg','Get feedback on my correction':'Feedback zu meiner Korrektur erhalten','Reviewing your new answer…':'Deine neue Antwort wird geprüft…','Cancel review':'Prüfung abbrechen','What will you do differently next time?':'Was machst du nächstes Mal anders?','AI: improved':'KI: verbessert','AI: try again':'KI: erneut versuchen','AI: needs context':'KI: Kontext fehlt','Self-reviewed':'Selbst geprüft','Draft':'Entwurf','reviewed':'geprüft','01 · THE ORIGINAL':'01 · DAS ORIGINAL','02 · YOUR NEW ATTEMPT':'02 · DEIN NEUER VERSUCH','03 · FEEDBACK ON YOUR NEW ANSWER':'03 · FEEDBACK ZU DEINER NEUEN ANTWORT','Compare with a suggested solution':'Mit einem Lösungsvorschlag vergleichen','Next step':'Nächster Schritt','I checked my new answer with my teacher or mark scheme.':'Ich habe meine neue Antwort mit der Lehrkraft oder dem Erwartungshorizont geprüft.'
},
zh:{
  'Your profile':'个人资料','Customize & settings':'自定义与设置','Information':'个人信息','My avatar':'我的形象','My buddy':'我的伙伴','Workspace settings':'工作区设置','You and your buddy. Always together.':'你和你的伙伴，始终在一起。','Person or monster':'人物或小怪兽','Body shape':'体型','Eyes':'眼睛','Hair':'发型','Outfit':'服装','Extra features':'特别造型','Skin color':'肤色','Hair color':'发色','Outfit color':'服装颜色','Your profile picture always shows you and your buddy together.':'头像会同时展示你和你的伙伴。','Personal information':'个人信息','Full name':'姓名','Telephone number':'电话号码','School information':'学校信息','Grade / year':'年级','Class / form':'班级','Save profile':'保存资料',
  'Exams':'考试','Exam sections':'考试专区','Corrections':'错题订正','Exam corrections':'试卷订正','Prepare before your exam':'考前练习','Upload photos & fix mistakes':'上传照片，订正错题','Upload your marked exam. Fix missed questions. Practise the skills behind them.':'上传批改后的试卷，订正错题，针对薄弱知识点练习。','Write corrections myself':'自己填写订正','Correct & practise':'订正与练习','YOUR CORRECTION NOTEBOOK':'我的错题本','Make your next answer better.':'让下一次作答更好。','Add a missed question':'添加错题','Save corrections':'保存订正','Question from your exam':'试卷原题','Your original answer':'原来的答案','Teacher feedback (if provided)':'老师评语（如有）','I checked these details against my exam.':'我已对照试卷核实这些内容。','Rewrite your answer and show your working':'重新作答并写出解题过程','Get feedback on my correction':'获取订正反馈','Reviewing your new answer…':'正在查看新答案…','Cancel review':'取消分析','What will you do differently next time?':'下次你会如何改进？','AI: improved':'AI：已改进','AI: try again':'AI：再试一次','AI: needs context':'AI：需要更多信息','Self-reviewed':'已自行核对','Draft':'草稿','reviewed':'已复查','01 · THE ORIGINAL':'01 · 原题与答案','02 · YOUR NEW ATTEMPT':'02 · 重新作答','03 · FEEDBACK ON YOUR NEW ANSWER':'03 · 新答案反馈','Compare with a suggested solution':'查看参考解答','Next step':'下一步','I checked my new answer with my teacher or mark scheme.':'我已请老师或对照评分标准核实新答案。'
}};
