// Original revision exercises. Keys are matched to explicit school assessment guides by the importer.
const science=[
 ['10.1','Define excretion.','Excretion removes metabolic waste, toxic materials and substances in excess of requirements from the body.'],
 ['10.1','How does excretion differ from egestion?','Excretion removes waste produced by metabolism, such as urea. Egestion removes undigested food as faeces; that food was never absorbed into cells.'],
 ['10.1','Name two excretory products and where they are removed.','Carbon dioxide is removed by the lungs. Urea is removed by the kidneys in urine.'],
 ['10.2','Trace the route of urine from its production to leaving the body.','Kidneys → ureters → bladder → urethra. The bladder stores urine; it does not make it.'],
 ['10.2','Why is blood supplied to the kidneys?','Blood carries dissolved waste such as urea and excess water and ions to the kidneys for removal and regulation.'],
 ['10.2','Where is urea made, and where is it removed from the blood?','Urea is made in the liver during the breakdown of excess amino acids. It is removed from the blood by the kidneys.'],
 ['10.3','What is the difference between filtration and selective reabsorption?','Filtration separates small dissolved substances and water from blood; cells and large proteins remain. Selective reabsorption returns useful substances and much of the water to the blood.'],
 ['10.3','A kidney model uses a sieve. Give one useful feature and one limitation.','A sieve models separation by size. It does not model selective reabsorption, living membranes or regulation of water and ion balance.'],
 ['10.3','Why should normal urine contain little or no glucose?','Filtered glucose is normally reabsorbed into the blood, where cells can use it in respiration.'],
 ['10.4','What happens to metabolic waste when kidneys cannot filter effectively?','Waste substances such as urea build up in the blood, and water and ion balance can be disrupted.'],
 ['10.4','Describe the principle of dialysis.','Blood and dialysis fluid are separated by a partially permeable membrane. Small waste solutes can diffuse out of the blood, while blood cells and large proteins remain.'],
 ['10.4','Give one difference between dialysis and a kidney transplant.','Dialysis requires repeated treatment to remove waste. A functioning transplant can filter continuously, but requires a suitable donor and management of rejection risk.'],
 ['10.5','After heavy sweating, how would a healthy body usually change its urine?','It usually conserves water, producing a smaller volume of more concentrated urine.'],
 ['10.5','Why is water regulation important even if the body has enough nutrients?','Cells need a suitable water and ion balance. Large changes can disrupt their normal function.'],
 ['10.5','Predict one adaptation that helps a desert mammal conserve water.','Producing a small volume of concentrated urine reduces water loss. Explain this as water conservation, not as creating water.'],
 ['11.1','Compare sexual and asexual reproduction.','Sexual reproduction involves fusion of gametes and combines genetic information. Asexual reproduction has one parent and no gamete fusion; offspring are usually genetically identical apart from mutations.'],
 ['11.1','Name the male and female gametes in humans.','Sperm and egg cells. Each normally carries one set of chromosomes.'],
 ['11.1','Give two features that help a sperm reach or fertilise an egg.','A tail enables movement; many mitochondria supply energy for movement. Its acrosome contains enzymes involved in entering the egg.'],
 ['11.2','What happens during fertilisation?','The nuclei of a male and female gamete fuse, forming a zygote with genetic material from both parents.'],
 ['11.2','Where do fertilisation and implantation normally occur in humans?','Fertilisation normally occurs in an oviduct. The early embryo later implants in the lining of the uterus.'],
 ['11.2','How does a zygote become a multicellular embryo?','It divides repeatedly by mitosis, increasing the number of cells.'],
 ['11.3','In the standard school XX/XY model, which gametes carry X or Y?','Eggs carry X. Sperm can carry X or Y. This is a simplified chromosome model; human sex development can be more complex.'],
 ['11.3','Use a simple XX × XY cross to calculate the probability of XX.','The combinations are XX, XY, XX and XY: 2 out of 4, or 50%. Each fertilisation is a new event; this does not guarantee a pattern among siblings.'],
 ['11.3','Why is a 50% probability not a promise that exactly half a small family will have XX chromosomes?','Probability describes the chance of each independent event. Small samples can differ from the expected proportion.'],
 ['11.4','Distinguish continuous and discontinuous variation with examples.','Continuous variation has a range of values, such as height. Discontinuous variation has distinct categories, such as ABO blood group.'],
 ['11.4','Give one inherited and one environmental influence on variation.','ABO blood group is inherited. A scar may result from an environmental event. Many characteristics, such as height, have both inherited and environmental influences.'],
 ['11.4','Why can siblings resemble each other without being identical?','They inherit genetic material from the same parents but usually receive different combinations of alleles. Their environments and experiences can differ too.']
];
const spanish=[
 ['Ser y estar','Complete: Mi hermana ___ médica.','es — ser identifies a profession.'],['Ser y estar','Complete: Hoy ___ cansado, pero normalmente soy activo.','estoy — estar describes a current state.'],['Ser y estar','Complete: La biblioteca ___ al lado del colegio.','está — estar locates a place.'],['Ser y estar','Explain: es aburrido / está aburrido.','Es aburrido: he/it is boring. Está aburrido: he is bored. The adjective changes meaning with the verb.'],['Ser y estar','Explain: es listo / está listo.','Es listo: he is clever. Está listo: he is ready.'],['Ser y estar','Complete: Nosotros ___ de Alemania y ahora ___ en España.','somos; estamos — origin uses ser, present location uses estar.'],['Gustar','Complete: A mí me ___ los libros, pero me ___ más el cine.','gustan; gusta — the verb agrees with the thing liked.'],['Encantar','Complete: A Ana le ___ bailar.','encanta — an infinitive takes the singular form.'],['Poder','Complete: Yo no ___ salir, pero mis amigos sí ___.','puedo; pueden — poder changes o → ue in these present-tense forms.'],['Routines','Translate: I have to take the bus at midday.','Tengo que coger el autobús al mediodía.'],['Descriptions','Write two sentences describing a person: one appearance, one personality.','For example: Mi hermano es alto. Es amable y divertido. Use ser with general descriptive characteristics.'],['Introductions','Introduce yourself using origin, home and occupation. Use fictional details if you prefer.','For example: Soy de Alemania. Vivo en Düsseldorf. Soy estudiante.'],['Reading','Lee: «Me llamo Elena. Vivo en un piso cerca del metro. Los sábados quedo con mis amigos a las doce». ¿Dónde vive y cuándo ve a sus amigos?','Vive en un piso cerca del metro. Ve a sus amigos los sábados a las doce.'],['Reading','Lee: «Hoy no puedo ir al partido porque tengo que trabajar en la tienda». ¿Por qué no va al partido?','Porque tiene que trabajar en la tienda.'],['Housing','What does «el piso está bien comunicado» mean?','The flat has good transport connections.'],['Time','Translate: It is late, but I can arrive on time.','Es tarde, pero puedo llegar a tiempo.']
];
const vocab=[['los cristales','the glass panes / windows'],['sucio / limpio','dirty / clean'],['cerrado / abierto','closed / open'],['el coche','the car'],['el violín','the violin'],['el piso','the flat / apartment; also a floor'],['la cocina','the kitchen'],['mi novio / novia','my boyfriend / girlfriend'],['el país','the country'],['estar de buen humor','to be in a good mood'],['estar de mal humor','to be in a bad mood'],['la tienda','the shop'],['estar listo / lista','to be ready'],['el periodismo','journalism'],['caminar','to walk'],['entrar','to enter'],['al mediodía','at midday'],['quedo con mis amigos','I meet up with my friends'],['dar un paseo','to go for a walk'],['el partido de fútbol','the football match'],['llevar a alguien a un lugar','to take someone to a place'],['el camarero','the waiter'],['decimos','we say'],['más o menos','more or less'],['llegar a tiempo','to arrive on time'],['¡Qué suerte!','How lucky!'],['el metro','the underground / metro'],['coger el autobús','to take / catch the bus'],['desde hace dos años','for two years, for a situation still continuing'],['¡Qué grande!','How big!'],['¿No?','Right? / Isn’t that so?'],['al menos','at least'],['tengo que + infinitivo','I have to + verb'],['está bien comunicado','it has good transport connections'],['es tarde / es temprano','it is late / it is early'],['la tarde','the afternoon / evening'],['barato','cheap / inexpensive'],['el nombre','the first name / name'],['los apellidos','the surname(s)'],['la dirección','the address'],['el correo electrónico','the email / email address'],['la fecha de nacimiento','the date of birth'],['el lugar de nacimiento','the place of birth']];
const banks={
 'science-kidneys-genetics':science,
 'spanish-ser-estar':[...spanish,...vocab.map(([a,b])=>['Exam vocabulary',`Translate «${a}» into English.`,b])],
 'music-blues-listening':[['12-bar structure','How are twelve bars grouped into phrases in this assessment?','Three phrases of four bars each.'],['Harmony','In C major, what are the I, IV and V chords?','I = C, IV = F, V = G.'],['Tonic','What is the tonic, and what should you listen for at the end of a cycle?','The tonic is the home note/chord. Listen for a sense of return to that home harmony as the next cycle starts.'],['Call and response','Describe how you could identify call-and-response in a blues excerpt.','Listen for an opening musical or vocal phrase answered by a second phrase, often in another voice or instrument.'],['Listening','Play the blues example. Count the bars and mark the first change away from the tonic.','In this original example, the first move to IV occurs at bar 5. The progression is I I I I / IV IV I I / V IV I V. Real blues recordings can use variations.']],
 'music-blues-writing':[['Blues lyrics','Choose a topic and draft three verses of blues lyrics.','Check that there are three verses, a consistent theme and the blues structure taught in class. One common structure is AAB: a line, its repetition, then a response. Check the teacher’s rubric for the required version.'],['Editing','Read your lyrics aloud. Where do the words fit the musical phrases, and what would you revise?','Identify a specific line, describe a rhythm or meaning problem, then rewrite it. Keep the intended theme and phrase structure.']],
 'german-scene':[['Einleitung','Welche Angaben gehören in die Einleitung einer Szenenanalyse?','Szene, Textsorte, Autor, Titel und Thema des Auszugs.'],['Einordnung','Wie unterscheidet sich die Einordnung von der Inhaltsangabe?','Die Einordnung erklärt die Position im Handlungsverlauf. Die Inhaltsangabe fasst das Geschehen des Auszugs in eigenen Worten zusammen.'],['Gesprächsverhalten','Untersuche eine Aussage aus deiner eigenen Textausgabe: Was tut die Figur, wie und warum?','Benenne die Handlung, beschreibe die sprachliche Art (z. B. höflich, schroff, ironisch) und begründe mögliche Gefühle oder Absichten mit Textbelegen.'],['Zitate','Wie belegst du eine Deutung überprüfbar?','Nutze ein wörtliches oder indirektes Zitat mit exakter Zeilenangabe und erkläre, wie der Beleg deine Deutung stützt. Erfinde keine Zitate.'],['Schluss','Was soll der Schluss leisten?','Er zieht ein Fazit und erläutert die Bedeutung der Szene. Er wiederholt nicht nur die Inhaltsangabe.']],
 'social-population':[['Density','A region has 900,000 people and an area of 3,000 km². Calculate its population density.','300 people per km²: population ÷ area.'],['Distribution','How is population distribution different from density?','Distribution describes where people live and how they are spread. Density measures people per unit area.'],['Population change','A country has 28 births and 9 deaths per 1,000 people per year. Calculate natural increase.','19 per 1,000 per year, or 1.9%, before migration.'],['Megacities','What is a megacity?','An urban area with a population of at least ten million people.'],['Graphs','What might a broad base on a population pyramid suggest?','A relatively large young population and often a high birth rate. Use the actual ages, scale and data to support the interpretation.'],['PEEL','Plan a PEEL paragraph comparing a youthful and an ageing population.','Point: identify a difference. Evidence: quote actual figures from the provided graphs. Explain: connect age structure to needs such as schools, jobs or care. Link: return to the comparison. Do not invent country statistics.'],['Command words','How does “explain” differ from “describe” in a short answer?','Describe sets out what the pattern or feature is. Explain gives reasons or shows how or why it happens. Use connected sentences.']],
 'english-reading':[['TAPS','Read: “Students can borrow a bicycle free of charge this Friday. Bring your school card to reception.” Identify the text type, audience and purpose.','A short notice; students; to inform them about borrowing bicycles and explain what to bring.'],['Simile','Identify and explain the simile: “The queue wound like a ribbon around the square.”','“Like a ribbon” compares the long, curving queue to a ribbon, making its shape easier to picture.'],['Metaphor','Explain: “The library was an island of quiet.”','The metaphor presents the library as a separate, sheltered place of quiet within a busy setting.'],['Alliteration','Identify the alliteration: “Bright banners billowed above the bridge.”','The repeated initial /b/ sound in bright, banners, billowed and bridge. Explain the effect in context rather than simply naming it.'],['Word choice','What is the effect of “trudged” compared with “walked”?','“Trudged” suggests slow, heavy or tired movement. Connect that implication to the person or scene.']],
 'drama-reflection':[['Movement','Tell a short story without dialogue using three contrasting gestures.','Check that an audience can identify the situation and change. Use clear posture, facial expression, pace and focus. Explain why you chose each gesture.'],['Reflection','Write a journal entry about one rehearsal decision.','Describe the choice, explain why and how it affected the scene, connect it to a drama technique and identify a specific next improvement.'],['Vocabulary','Explain blocking and focus using examples from your own rehearsal.','Blocking is the planned positioning and movement of performers. Focus directs the audience’s attention. Use a specific example of each.'],['Ensemble','How can a group make a movement sequence clear and coordinated?','Agree a shared intention, use cues and timing, rehearse transitions and observe what the audience can understand. Support your answer with an example.']]
};
function maths(seed=0){const list=[];for(let i=0;i<8;i++){const n=2+(seed+i)%8,a=2+i%4,b=1+(i+seed)%3;list.push(['Indices',`Simplify x^${a} × x^${b}.`,`x^${a+b}. When multiplying powers of the same base, add their indices.`],['Indices',`Simplify (y^${a})^${b+1}.`,`y^${a*(b+1)}. Multiply the indices when raising a power to another power.`],['Roots',`Calculate √${n*n} + ∛${n*n*n}.`,`${2*n}. Both roots are ${n}.`],['BIDMAS',`Calculate ${n} + ${a} × (${n+2} − 2).`,`${n+a*n}. Brackets first give ${n}; multiply by ${a}, then add ${n}.`]);}list.push(['Number types','Is √2 rational or irrational? What about √49?','√2 is irrational. √49 = 7 is an integer and rational.'],['Bounds','A length rounds to 8.4 cm to the nearest 0.1 cm. Give its error interval.','8.35 cm ≤ length < 8.45 cm. Half of the rounding unit is 0.05 cm.'],['Rounding','Round 0.006847 to three significant figures.','0.00685. The first significant digit is 6; the next digit after 684 is 7, so round up.']);return list;}
export function examQuestions(exam,seed=0){
 const rows=exam.practiceKey==='maths-number'?maths(seed):banks[exam.practiceKey];
 if(rows)return rows.map(([topic,question,answer],i)=>({id:`${exam.id}-${exam.practiceKey}-${i}${exam.practiceKey==='maths-number'?'-'+seed:''}`,topic,question,answer,guided:false}));
 return (exam.topics||[]).flatMap((topic,i)=>[{id:exam.id+'-explain-'+i,topic,question:`Explain ${topic} in your own words, then give one example.`,answer:'Check your explanation against the linked teacher material. Identify a missing idea or an example you need to improve.',guided:true},{id:exam.id+'-apply-'+i,topic,question:`Find a question about ${topic} in your class material. Attempt it without notes and explain each step.`,answer:'Compare your work with the teacher’s solution or rubric. Record the exact step you would change. This guided task has no automatic mark.',guided:true}]);
}
export function studyProgressKey(exam){return exam.id+'-'+(exam.practiceKey||'guided')+'-'+(exam.topics||[]).join('|');}
