export function buoyancy(mass,volume,liquid=1){const density=mass/volume;return {density,fraction:Math.min(1,density/liquid),floats:density<liquid,neutral:density===liquid};}
export function refract(angle,n1,n2){const ratio=n1*Math.sin(angle*Math.PI/180)/n2;return {totalInternalReflection:ratio>1,angle:ratio>1?null:Math.asin(Math.min(1,ratio))*180/Math.PI};}
export function gasPressure(volume){return 100*300/volume;}
// Teaching models: relative outputs illustrate trends, not fitted experimental data.
export function photosynthesisRate(light,co2,temperature){return 100*Math.min(light/200,co2/.06,1)*Math.exp(-(((temperature-25)/18)**2));}
export function enzymeRate(temperature,ph){return temperature>=65?0:100*Math.exp(-(((temperature-37)/21)**2))*Math.exp(-(((ph-7)/2)**2))*Math.min(1,(65-temperature)/20);}
export function reactionProduct(seconds,concentration,temperature,surface){const k=.025*concentration*surface*2**((temperature-20)/10);return 100*(1-Math.exp(-k*seconds));}
export function diffusionMix(seconds,temperature){return 1-Math.exp(-seconds*.045*(temperature+273.15)/293.15);}
export const EXTRA_LABS=[
 {id:'photosynthesis',name:'Limiting photosynthesis',branch:'Biology',defaults:{light:120,co2:.04,temperature:25},sliders:[['light','Light intensity',0,300,10,'relative units'],['co2','Carbon dioxide',.01,.1,.01,'%'],['temperature','Temperature',0,50,1,'°C']],question:'When increasing light no longer helps, which other factor limits the rate?',note:'A simplified relative-rate model. Its chosen optimum and response curve do not describe a specific plant or measured oxygen production.'},
 {id:'enzymes',name:'Enzyme activity',branch:'Biology',defaults:{temperature:37,ph:7},sliders:[['temperature','Temperature',0,80,1,'°C'],['ph','pH',1,14,.5,'']],question:'Change pH while holding temperature constant. Where is the highest activity?',note:'A fictional enzyme with an optimum near pH 7 and 37°C. Each setting is a fresh sample. Heating a real enzyme enough to denature it may be irreversible; cooling does not repair it.'},
 {id:'reaction-rate',name:'Speed of a reaction',branch:'Chemistry',defaults:{concentration:1,temperature:20,surface:1,seconds:30},sliders:[['concentration','Relative concentration',.25,3,.25,'×'],['temperature','Temperature',10,50,1,'°C'],['surface','Relative surface area',1,5,1,'×'],['seconds','Time',0,120,1,'s']],question:'Which variable changes how quickly the curve approaches the same final product amount?',note:'A generic pseudo-first-order teaching model. Product is a percentage of a fixed limiting reactant. The assumed temperature doubling rule illustrates a trend and is not universal.'},
 {id:'diffusion',name:'Particles spreading out',branch:'Chemistry',defaults:{temperature:20,seconds:0},sliders:[['temperature','Temperature',0,80,1,'°C'],['seconds','Time',0,100,1,'model s']],question:'How does temperature affect the time taken to reach a well-mixed distribution?',note:'A qualitative, two-dimensional illustration of two gases. Particle positions illustrate mixing; they are not a molecular dynamics calculation. Particles continue moving at equilibrium.'},
 {id:'buoyancy',name:'Float or sink',branch:'Physics',defaults:{mass:300,volume:500,liquid:1},sliders:[['mass','Object mass',50,1000,25,'g'],['volume','Object volume',50,1000,25,'cm³'],['liquid','Liquid density',.6,1.4,.1,'g/cm³']],question:'Keep mass fixed and increase volume. What happens to density and the submerged fraction?',note:'A rigid, watertight object in a uniform liquid. At floating equilibrium, submerged fraction = object density ÷ liquid density. Surface tension and fluid motion are ignored.'},
 {id:'refraction',name:'Bending light',branch:'Physics',defaults:{angle:35,n1:1,n2:1.5},sliders:[['angle','Incident angle',0,85,1,'°'],['n1','First medium index',1,2,.01,''],['n2','Second medium index',1,2,.01,'']],question:'Send light from glass (1.50) to air (1.00). Find the angle at which refraction becomes total internal reflection.',note:'Snell’s law for a single wavelength and ideal flat boundary. Angles are measured from the normal. The diagram omits partial reflection when refraction occurs.'},
 {id:'waves',name:'Wavelength and frequency',branch:'Physics',defaults:{frequency:2,speed:4,amplitude:.5,time:0},sliders:[['frequency','Frequency',.5,5,.5,'Hz'],['speed','Wave speed',1,10,.5,'m/s'],['amplitude','Amplitude',.1,1,.1,'m'],['time','Time',0,10,.1,'s']],question:'Keep wave speed constant. What happens to wavelength when you double the frequency?',note:'An ideal sinusoidal travelling wave with no damping. The dots on the vertical axis oscillate; the wave pattern travels to the right.'},
 {id:'gas',name:'Compressing a gas',branch:'Physics',defaults:{volume:300},sliders:[['volume','Gas volume',100,600,10,'mL']],question:'Halve the volume. How does pressure change? Compare pressure × volume in each trial.',note:'Boyle’s law for a fixed amount of ideal gas at constant temperature. The starting state is 100 kPa at 300 mL; compression is slow enough for temperature to remain unchanged.'}
];
