// Original application questions: topic | question | answer | three distractors | explanation.
export const APPLICATIONS = {
science: `Investigation|A student changes light intensity and measures oxygen production by a plant. What is the dependent variable?|Oxygen production|Light intensity|The lamp brand|The original prediction|Oxygen production is the response being measured; light intensity is deliberately changed.
Investigation|Repeated readings are 4.1, 4.2, 4.1, and 9.8 seconds. What should happen next?|Check the unusual result and repeat the measurement|Delete 9.8 without investigation|Change all readings to 4.1|Conclude the equipment is perfect|The unusual reading needs investigation. Repeats and checking the method are more defensible than silently deleting it.
Investigation|A thermometer consistently reads 2°C above the accepted value. What kind of problem is this?|A systematic measurement error|A correct control variable|Evidence of zero uncertainty|A random change of exactly zero|A consistent offset biases readings in one direction; repeating alone will not remove that offset.
Biology|A plant cell loses water in a concentrated sugar solution. Which process explains this?|Osmosis|Photosynthesis|Protein synthesis|Mitosis|Water moves through the partially permeable membrane toward the lower water potential outside the cell.
Biology|In grass → rabbit → fox, which organism is the primary consumer?|Rabbit|Grass|Fox|All three|The rabbit eats the producer, so it occupies the primary-consumer level.
Biology|Which substances supply the carbon and water needed for photosynthesis?|Carbon dioxide and water|Oxygen and glucose|Nitrogen and oxygen|Glucose and starch|Photosynthesis uses carbon dioxide and water to produce glucose, using light energy.
Chemistry|An atom has 6 protons and 8 neutrons. What is its mass number?|14|6|8|2|Mass number counts protons plus neutrons: 6 + 8 = 14.
Chemistry|Which method is suitable for separating sand from water?|Filtration|Adding more sand|Freezing both together|Using a magnet for all sand|Insoluble sand is trapped by filter paper while water passes through.
Chemistry|A sealed reaction vessel has mass 120 g before a reaction. No material enters or leaves. What is its mass afterwards?|120 g|0 g|More than 120 g in every reaction|Less than 120 g in every reaction|Mass is conserved in a closed system; the atoms are rearranged rather than lost.
Physics|A runner travels 150 m in 30 s. What is the average speed?|5 m/s|180 m/s|0.2 m/s|4500 m/s|Average speed is distance divided by time: 150 ÷ 30 = 5 m/s.
Physics|A 3 kg object has a resultant force of 12 N. What is its acceleration?|4 m/s²|36 m/s²|9 m/s²|0.25 m/s²|Using F = ma gives a = F/m = 12/3 = 4 m/s².
Physics|A component has 6 V across it and 2 A through it. What is its resistance?|3 Ω|12 Ω|8 Ω|0.33 Ω|Resistance R = V/I = 6/2 = 3 Ω.`,
english: `Language|“The wind whispered through the doorway.” Which technique is most clearly used?|Personification|A statistic|Direct speech|A rhetorical question|Whispering is a human action attributed to the wind, which is non-human.
Language|“The street was a ribbon of silver.” Which technique is most clearly used?|Metaphor|Simile using like|Onomatopoeia|A factual measurement|The street is described as a ribbon, suggesting its long, shining appearance without using like or as.
Reading|“Mara folded the unopened letter and pushed it under a book.” Which inference is best supported?|Mara may be avoiding what the letter contains|Mara has certainly read every word|Mara wrote the letter herself|Mara cannot read at all|Hiding an unopened letter can suggest avoidance, but does not establish the other claims.
Reading|A writer describes “cracked windows, peeling paint, and empty rooms.” What impression is best supported?|Neglect and abandonment|A freshly renovated home|A busy celebration|A precise construction date|The accumulated details of damage and emptiness support neglect, without proving a specific date or history.
Writing|Which sentence analyses the effect of a quotation?|“Clutched” suggests anxiety because it implies a tight, tense grip.|The text uses the word “clutched.”|The quotation contains one verb.|I chose this quotation because it is short.|Analysis connects the writer's choice to a supported meaning or effect, rather than only identifying the word.
Writing|Which is the most concise summary of “The bus arrived late, so Noor missed the first ten minutes of rehearsal”?|A delayed bus made Noor late for rehearsal.|Noor dislikes all rehearsals.|The bus never arrived.|Rehearsal lasted ten minutes in total.|The summary preserves the stated cause and consequence without adding unsupported information.
Writing|Which source detail must be acknowledged when paraphrasing an author's idea?|The source of the idea|Only the font used|Only the number of words changed|Nothing if all words are different|Changing wording does not make the underlying idea yours; cite its source as required by the task.
Writing|Which revision suits a formal email requesting clarification from a teacher?|Could you clarify which chapters the assessment covers?|Hey, send stuff now.|You obviously forgot everything.|Whatever, explain it.|The polite, specific request uses an appropriate register and makes the needed clarification clear.`,
computing: `Algorithms|What is x after x = 3, followed by x = x + 4?|7|3|4|12|The assignment adds 4 to the current value 3 and stores 7 in x.
Algorithms|A loop adds 2 to total three times, starting at total = 0. What is the final total?|6|2|3|8|Three additions of 2 give 0 + 2 + 2 + 2 = 6.
Algorithms|A condition is “score >= 50”. Which score makes it false?|49|50|51|100|The operator >= includes 50 and all larger values; 49 is below the threshold.
Algorithms|A program must repeat until the user enters a valid choice. Which construct is needed?|Iteration|A one-time comment|A constant file name|Only an output label|Repeating a check and input step is iteration; the exit condition is a valid choice.
Data|An integer input must be from 1 to 10 inclusive. Which input passes both type and range checks?|7|11|0|seven|7 is an integer within the permitted range. The word seven fails the stated integer representation check.
Data|A database needs a unique student identifier. Which property is essential?|No two records share the chosen key value|Every student has the same first name|The field contains an essay|The field is always empty|A primary key identifies each record uniquely; names may be shared and are not necessarily suitable keys.
Networks|A device can reach a site by IP address but cannot resolve its domain name. Which service should be investigated first?|DNS|Keyboard input|Screen brightness|The image editor|DNS resolves names to addresses. This symptom points to name resolution, though further checks are still needed.
Security|An unexpected message asks you to log in through an unfamiliar link. What is a sensible first action?|Open the service through its known address and check there|Send your password in reply|Disable all security checks|Forward your login code to the sender|Independently reaching the known service avoids relying on the suspicious link or sharing credentials.`,
music: `Rhythm|A metronome changes from 60 to 120 beats per minute. What happens to the beat rate?|It doubles|It halves|It stays unchanged|It becomes four times slower|120 is twice 60, so there are twice as many beats per minute.
Rhythm|In common time, a bar contains how many crotchet (quarter-note) beats?|4|2|3|8|Common time is 4/4: four quarter-note beats in a bar.
Rhythm|Which beats would you clap for a conventional 4/4 backbeat?|2 and 4|1 only|1 and 3|Every half-beat except 4|The typical backbeat places emphasis on beats 2 and 4.
Pitch|A note vibrates at 220 Hz. What frequency is one octave higher?|440 Hz|110 Hz|221 Hz|330 Hz|An octave higher has twice the frequency: 220 × 2 = 440 Hz.
Harmony|In C major, what is the root of the dominant chord?|G|C|D|F|The dominant is scale degree five: C, D, E, F, G.
Blues|A blues verse repeats its first line and then adds a contrasting line. Which pattern is this?|AAB|ABC|ABB|AAA|The repeated first line gives AA; the contrasting third line gives B.
Expression|A score asks the performer to get gradually softer. Which instruction fits?|Diminuendo|Crescendo|Accelerando|Fortissimo|Diminuendo means gradually softer; crescendo means gradually louder.
Expression|Two instruments play the same pitch at similar loudness but still sound different. What most directly distinguishes them?|Timbre|The written page number|The bar count alone|The rehearsal date|Different overtone patterns and sound envelopes contribute to each instrument's timbre.`,
german: `Grammatik|Welche Form ergänzt: „Du ___ heute Zeit“?|hast|hat|haben|habe|Zum Personalpronomen du gehört im Präsens die Form hast.
Grammatik|Welche Form ergänzt: „Wir ___ morgen ins Museum“?|gehen|geht|gehst|gehe|Zum Subjekt wir gehört die Pluralform gehen.
Grammatik|Welches Satzglied ist „den Ball“ in „Lena wirft den Ball“?|Akkusativobjekt|Subjekt|Dativobjekt|Prädikat|Man fragt: Wen oder was wirft Lena? Den Ball.
Grammatik|Welche Ergänzung ist korrekt: „Ich helfe ___ Freund“?|dem|den|der|das|Das Verb helfen verlangt hier den Dativ: dem Freund.
Rede|Welche Form passt zur formellen indirekten Rede: „Er sagt, er ___ müde“?|sei|seid|seien|seist|Für er lautet der Konjunktiv I von sein: sei.
Analyse|„Ihre Worte waren Eis.“ Welches Stilmittel steht im Vordergrund?|Metapher|Vergleich mit wie|Aufzählung|Sachliche Temperaturmessung|Worte werden bildlich als Eis bezeichnet; gemeint sein kann emotionale Kälte.
Drama|Eine Figur sagt „Mir geht es gut“, vermeidet aber Blickkontakt. Was ist eine sinnvolle Deutung?|Worte und Verhalten können einander widersprechen|Die Figur ist nachweislich immer ehrlich|Blickkontakt ist im Drama bedeutungslos|Die Regieanweisung ersetzt alle Worte|Der Gegensatz kann Unsicherheit oder Verbergen andeuten; die Deutung muss im Kontext geprüft werden.
Analyse|Was verbessert eine Figurenanalyse am stärksten?|Eine passende Textstelle erklären und mit der Aussage verbinden|Nur die Schrift vergrößern|Ein langes Zitat ohne Kommentar einfügen|Die Aussage öfter wiederholen|Textbeleg und Erklärung zeigen nachvollziehbar, worauf die Deutung beruht.`,
spanish: `Introductions|Complete: “Nosotros ___ estudiantes.”|somos|soy|eres|es|The present-tense form of ser for nosotros is somos.
Introductions|Complete: “Ella ___ quince años.”|tiene|es|está|soy|Spanish uses tener for age; ella takes tiene.
Description|Choose the adjective that agrees: “Las casas son ___.”|blancas|blanco|blancos|blanca|Casas is feminine plural, so the adjective is blancas.
Description|Complete: “Hoy estoy muy ___” to say that you feel tired.|cansado|alto|quince|biblioteca|Cansado describes feeling tired; estar is used here for a state.
School|Complete: “El libro ___ en la mochila.”|está|es|soy|tengo|Estar expresses the location of the book: está en la mochila.
School|How do you ask “What time is it?”|¿Qué hora es?|¿Cuántos años tienes?|¿Cómo te llamas?|¿De dónde eres?|¿Qué hora es? asks for the current time; the other questions ask age, name, or origin.
Everyday phrases|Complete: “Me ___ las matemáticas.”|gustan|gusta|gusto|gustas|With gustar, the thing liked is the grammatical subject. Las matemáticas takes the plural form gustan.
Everyday phrases|What does “No tengo hermanos” mean?|I do not have any siblings.|I have nine siblings.|My siblings are not here.|I do not like my siblings.|No negates tengo: the speaker says they have no brothers or sisters.`,
social: `Population|A town has 24,000 people and covers 60 km². What is its population density?|400 people/km²|1440000 people/km²|24060 people/km²|40 people/km²|Density = population ÷ area = 24,000 ÷ 60 = 400 people per square kilometre.
Population|There are 800 births and 500 deaths in a year. What is the natural increase?|300 people|1300 people|500 people|−300 people|Natural increase = births − deaths = 800 − 500 = 300, before migration is considered.
Migration|There are 200 immigrants and 350 emigrants. What is net migration?|−150 people|150 people|550 people|70000 people|Net migration = immigration − emigration = 200 − 350 = −150.
Population|A population pyramid has a very wide base. What does this directly show?|A large share of the population is in younger age groups|Everyone will live beyond 90|The country has no migration|The climate must be tropical|The base represents young ages. Wider bars indicate more people in those age groups, without proving the other claims.
Geography|On a map, 1 cm represents 2 km. How far apart are places 3.5 cm apart on the map?|7 km|1.75 km|5.5 km|35 km|Multiply map distance by distance per centimetre: 3.5 × 2 = 7 km.
Geography|Contour lines are close together on a map. What does that usually indicate?|A steep slope|Completely flat land|A political boundary|A river flowing uphill|A large change in height over a short horizontal distance means the slope is steep.
Evidence|Ice cream sales and swimming incidents both rise in summer. What can this alone establish?|An association, but not that ice cream causes incidents|Ice cream directly causes every incident|Swimming causes every ice cream purchase|There is no possible third factor|A common factor such as warm weather may influence both; correlation alone does not establish causation.
Evidence|Two accounts disagree about an event. What is the strongest next step?|Compare their evidence, context, and independent sources|Accept whichever is longer|Discard both without reading|Choose the account with more colourful text|Evaluating provenance and corroborating details is stronger than judging presentation alone.`,
art: `Elements|An artist leaves a white gap between two dark shapes. What is that gap an example of?|Negative space|Cross-hatching|A vanishing point|A primary pigment|Negative space is the area around or between the main forms and can be deliberately composed.
Colour|In traditional red-yellow-blue paint mixing, red and yellow make which secondary colour?|Orange|Green|Violet|Blue|Red and yellow pigments are conventionally mixed to make orange in the traditional RYB model.
Colour|Adding white paint to blue creates what?|A tint of blue|A darker shade of blue|A complementary colour pair|A new vanishing point|White lightens the colour to make a tint; adding black would darken it.
Composition|One bright red shape sits among many dull grey shapes. Which principle makes it stand out?|Contrast|Identical saturation|Uniformity of colour|Absence of emphasis|The difference in hue and saturation creates contrast and can establish a focal point.
Composition|An artist repeats a curved shape at regular intervals. Which principle is most directly demonstrated?|Pattern|Perspective convergence|Random omission|Literal texture only|A repeated arrangement establishes a pattern; its spacing can also create rhythm.
Drawing|Parallel railway tracks appear to meet in the distance in a drawing. What point are they approaching?|A vanishing point|The light source in every case|The centre of every object|The nearest corner|Linear perspective represents receding parallel lines converging toward a vanishing point.
Drawing|Which technique makes a hatched area darker without changing the pencil?|Add closer or overlapping lines|Remove every line|Leave wider empty gaps|Use only one faint line|Denser line coverage creates a darker perceived tone, especially with cross-hatching.
Composition|Why make several thumbnail sketches before a final piece?|To compare composition options quickly|To prove only one composition is possible|To avoid making any decisions|To replace all observation|Small sketches allow inexpensive experimentation with placement, balance, and focal points.`,
drama: `Physical theatre|Two characters stand far apart and turn away from each other. Which choice most directly communicates distance in their relationship?|Proxemics and orientation|The programme's font|The ticket price|The date of rehearsal|Physical distance and facing direction can suggest disconnection, depending on the scene's context.
Physical theatre|A group freezes at the moment a secret is revealed. What technique are they using?|Tableau|A costume change|A voice-over only|A written review|A tableau freezes performers into a still image that conveys a significant moment.
Voice|An important line is being rushed and is hard to understand. What adjustment is most relevant?|Slow the pace and articulate clearly|Speak even faster|Turn away and mumble|Ignore the words entirely|Pace and articulation affect intelligibility; volume alone cannot solve every clarity problem.
Voice|A performer pauses before answering “Yes.” What might the pause suggest?|Hesitation or thought, depending on context|Only happiness in every scene|That the script contains no dialogue|A guaranteed change of setting|Pauses can create subtext or tension, but their meaning depends on the surrounding action.
Performance|A character wants another character to stay. What is “persuade them to stay” in the scene?|An objective|A lighting cue|A costume fabric|A rehearsal date|An objective is what the character is trying to achieve; actions can be chosen to pursue it.
Performance|A doorbell sound signals an actor to enter. What is the sound functioning as?|A cue|A synopsis|An audience review|A programme note|A cue signals a specific performance or technical action.
Structure|A group invents a scene together from a photograph. What process is this?|Devising|Only proofreading|Printing a script|Selling tickets|Creating original material collaboratively from a stimulus is devising.
Performance|A physical scene makes a partner uncomfortable. What should the group do?|Pause and agree a safe, comfortable alternative|Continue because discomfort never matters|Add more surprise contact|Ignore the partner's response|Physical work requires communication and agreed boundaries; adjust the action before continuing.`,
pe: `Team play|A teammate with the ball has no clear passing option. Which action can help?|Move into available space and communicate|Stand directly behind an opponent|Run into the teammate|Stop paying attention|Support play creates a reachable passing option and helps the team retain possession.
Tactics|Your team loses possession. Which change of role is needed?|Transition from attack to defence|Continue acting as if you have the ball|Leave the playing area|Ignore the opposition|A turnover changes the immediate task from creating chances to preventing them.
Tactics|A defence is crowded in the centre. What tactical option may create space?|Spread play to use width|Crowd even more players into the same spot|Stop communicating|Give every player the same position|Using width can stretch a defence and create space, depending on the game's rules and situation.
Practice|A learner completes a passing drill accurately at a short distance. What is a reasonable next progression?|Increase the distance slightly while maintaining control|Immediately use the hardest possible drill|Remove all feedback|Change every condition at once|A manageable change increases challenge while preserving the chance to practise the intended technique.
Practice|Which feedback is most useful after an inaccurate pass?|Aim toward the target and review the direction of your follow-through.|You are always bad at this.|Nothing could ever improve.|Everyone must copy my body exactly.|Useful feedback is specific and actionable, allowing the learner to test a change.
Team play|An official makes a decision you disagree with. What demonstrates sportsmanship?|Respond respectfully and use the agreed process for questions|Insult the official|Refuse to let anyone continue|Retaliate against an opponent|Respectful communication and following the agreed process preserve fair participation.
Movement|A drill requires changing direction around markers under control. Which skill is it mainly practising?|Agility|Only handwriting|Only memory for dates|Only voice projection|Controlled direction changes are a central feature of agility.
Practice|Why compare several attempts rather than only one?|To see consistency and patterns in performance|Because one attempt proves all future results|To hide every mistake|To avoid any feedback|A series of attempts gives more useful evidence about repeatability and areas for improvement.`,
advising: `Learning|You reread a page and then close it to explain the idea from memory. Which part is retrieval practice?|Explaining without looking|Only looking at the heading|Changing the font|Counting the pages|Retrieval requires bringing information to mind rather than having the answer in view.
Learning|Which plan uses spacing?|Three short reviews on separate days|All reviews in one uninterrupted sitting|Never revisiting the idea|Only decorating notes|Spacing distributes practice across time, creating opportunities to retrieve after a delay.
Planning|A report is due Friday and depends on a group interview Wednesday. What should be planned first?|The interview and preparation needed before it|The final printout before collecting information|Only the cover colour|Nothing until Friday night|The interview is a dependency; scheduling it and its preparation protects later writing time.
Planning|Which goal gives the clearest completion check?|Solve six linear equations and explain two corrections.|Get better at everything.|Study sometime.|Be perfect today.|The specific task and evidence of completion make it possible to tell when this session is finished.
Reflection|You were very confident but answered incorrectly. What is a useful next step?|Examine the misconception and try a related question|Ignore the answer because confidence proves accuracy|Avoid the topic forever|Copy the same answer again unchanged|Comparing confidence with correctness can reveal a misconception that deserves focused practice.
Reflection|A teacher says your evidence is relevant but not explained. What should you revise?|Explain how the evidence supports your point|Only enlarge the quotation|Delete all evidence|Add an unrelated example|The feedback identifies the missing connection between evidence and argument.
Integrity|You use a source's idea but rewrite every sentence. What is still needed?|Acknowledge the source according to the task's requirements|Claim the idea is entirely original|Remove the source from your notes|Use a different font only|Paraphrasing changes wording, not the origin of the idea.
Integrity|Which request makes it easiest for a teacher to help?|I can expand the brackets, but I get stuck collecting the x terms; can we check this line?|I understand absolutely nothing and have no example.|Please do all my work.|Tell me the final answer only.|Showing the step you can do and the point of difficulty makes the support request specific.`,
homeroom: `Organisation|A meeting agrees that Sam will book a room by Tuesday. Where should this go?|In the action list with owner and deadline|Only in an unrelated sketch|Nowhere because everyone will remember|In a private password field|An action item is clearer when it records the task, responsible person, and due date.
Organisation|Two events appear to overlap in your calendar. What is a useful next step?|Check their times and confirm priorities with the organiser|Assume you can attend both fully|Delete every event|Ignore the conflict until it ends|Checking the actual times and responsibilities helps resolve a real scheduling conflict.
Teamwork|One member has not spoken during a group discussion. What supports inclusion?|Invite their contribution without pressuring them|Assume they have no ideas|Interrupt them when they begin|Give them all the work without asking|An open invitation creates an opportunity to contribute while respecting the person.
Teamwork|Which response shows active listening?|So your main concern is the deadline; have I understood?|I did not listen, but here is my answer.|Your point cannot matter.|Let me interrupt before you finish.|Restating and checking the meaning helps confirm understanding before responding.
Communication|A message says “Bring it tomorrow” with no context. What should you ask?|Which item do you mean, and when is it needed?|Why are all messages useless?|Can I ignore every task?|What is the sender's password?|A focused clarification identifies the missing item and timing.
Digital citizenship|A classmate appears in a photo you want to share publicly. What should you do first?|Ask for their agreement and follow the applicable school rules|Post it without asking|Add their personal contact details|Assume being photographed means agreeing to any use|Agreement to being in a photo is not automatically agreement to public sharing; check before posting.
Digital citizenship|A dramatic school announcement appears in an unofficial group chat. What is a sensible next step?|Check the official school channel or responsible staff member|Forward it as certain fact immediately|Add an invented detail|Share classmates' private information to investigate|Verification through an appropriate source helps prevent spreading an unconfirmed claim.
Digital citizenship|You use an image with a licence requiring credit. What should you include?|The required creator and licence attribution|Only your own name as creator|A claim that all online images are unrestricted|No credit because the image was easy to find|Follow the licence's attribution conditions and check that the proposed use is permitted.`
};
