export const ROADMAP_KEY='aster-roadmap-v1';
export const ROADMAP_SOURCES={isr:'https://www.isr-school.de/upper-school-curriculum/',cambridge:'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-upper-secondary/cambridge-igcse/',ib:'https://www.ibo.org/programmes/diploma-programme/',selection:'https://ibo.org/university-admission/support-students-transition-to-higher-education/course-selection-guidance/'};
export const ROADMAP=[
 {id:'g8',grade:'GRADE 8',title:'Build your foundation.',subtitle:'Where you are now',color:'#aa8aff',description:'Make your current courses feel manageable. Use short recall sessions, keep a realistic plan, and identify the ideas that need another pass.',milestones:[['g8-plan','Build a weekly study routine','Choose two repeatable revision blocks and keep space for rest.'],['g8-recall','Try recall across your core subjects','Answer from memory, check the explanation, and revisit gaps.'],['g8-questions','Keep a questions list','Bring unclear concepts to your next lesson.']],source:null},
 {id:'g9-10',grade:'GRADES 9–10',title:'Develop your IGCSE skills.',subtitle:'ISR’s confirmed course stage',color:'#67dbe1',description:'ISR identifies Grades 9 and 10 as its IGCSE course years. Your teachers and counsellor will confirm the actual subjects, syllabuses, and examination arrangements for your cohort.',milestones:[['igcse-subjects','Confirm your subjects and syllabus versions','Use the course codes and examination year supplied by your school.'],['igcse-practice','Practise exam-style questions with feedback','Use resources for your exact syllabus, then review what the mark scheme rewards.'],['igcse-reflect','Track recurring mistakes','Turn feedback into specific revision goals rather than only recording a score.']],source:'isr'},
 {id:'transition',grade:'PLANNING AHEAD',title:'Choose your next direction.',subtitle:'Start the conversation in Grade 9',color:'#f2ad80',description:'ISR says Grade 9 students meet with their University Counsellor and Academic Head to consider future pathways. Revisit these conversations as your interests and options develop.',milestones:[['plan-interests','Explore the subjects you enjoy','Notice which kinds of work keep you interested: reading, making, experimenting, solving, or discussing.'],['plan-counsellor','Discuss course options with your counsellor','Check university prerequisites before committing to a subject combination.'],['plan-options','Record your questions and next steps','Ask about workload, level choices, support, and alternatives that suit your goals.']],source:'isr'},
 {id:'ib',grade:'GRADES 11–12',title:'Think independently. Connect ideas.',subtitle:'The two-year IB Diploma pathway',color:'#d78afa',description:'ISR states that most students begin the two-year IB Diploma Programme in Grade 11. The DP combines six subject groups with Theory of Knowledge, the Extended Essay, and Creativity, Activity, Service. Confirm your own route with ISR.',milestones:[['ib-subjects','Confirm your subject and level choices','Your school determines available combinations; official IB guidance is a starting point.'],['ib-research','Practise research and source evaluation','Build careful notes, citations, and an evidence-based argument.'],['ib-core','Understand the DP core','Learn what TOK, the Extended Essay, and CAS each involve with your school’s guidance.']],source:'ib'}
];
export const ROADMAP_IDS=new Set(ROADMAP.flatMap(s=>s.milestones.map(m=>m[0])));
export function normalizeRoadmap(value){return Array.isArray(value)?[...new Set(value.filter(id=>ROADMAP_IDS.has(id)))]:[];}
