// A manually verified Schoolbox snapshot. No credentials or live API connection.
export const SCHOOL = { name: 'ISR International School on the Rhine', student: 'Anton', term: 'Term 1 · 2026–2027', checkedAt: '2026-09-19T13:22:23Z', url: 'https://lms.isr-school.com/news', classesUrl: 'https://lms.isr-school.com/learning/classes' };
const page = id => `https://lms.isr-school.com/homepage/${id}`;
const task = id => `https://lms.isr-school.com/learning/assessments/${id}/570`;
const resource = (title, url, type = 'Schoolbox material') => ({ title, url, type });
const question = (q, options, a, why) => ({ q, options, a, why });

export const COURSES = {
  music: {
    name:'Music', code:'Mu8.B', icon:'Music2', source:page(5344), unitSource:page(789), title:'Feeling the Blues', description:'Find the rhythm. Hear the pattern. Make it your own.',
    topics:['The roots of blues','Feel the backbeat','The 12-bar pattern','Blues lyrics','Ready for the quiz'],
    notes:[['The roots of blues','Blues developed in African American communities in the United States. Its lyrics express experiences and feelings. Your unit explores its history, social context, musical features, and performance.'],['Feel the backbeat','In common 4/4 blues grooves, the backbeat emphasizes beats 2 and 4. Count “1, 2, 3, 4” steadily, then clap on 2 and 4.'],['The 12-bar pattern','A common 12-bar blues uses the I, IV, and V chords over twelve bars. One basic version is I–I–I–I / IV–IV–I–I / V–IV–I–I. Other versions use variations.'],['Blues lyrics','An AAB verse repeats its first line, then answers or develops it with a different third line. For your lyric-writing assessment, follow the instructions and table in your class worksheets.']],
    resources:[resource('Feeling the Blues · unit overview & worksheets',page(789)),resource('Assessment 1: Mid Unit Quiz',task(9464),'Assessment'),resource('Listening Recognition · 12-bar blues',task(9467),'Assessment'),resource('Blues Lyric Writing · instructions & rubric',task(9471),'Assessment')],
    questions:[question('Which beats does the backbeat usually emphasize in 4/4?', ['1 and 3','2 and 4','Only beat 1','All beats equally'],1,'The backbeat emphasizes beats 2 and 4.'),question('How many bars are in a 12-bar blues cycle?',['4','8','12','16'],2,'One complete cycle has twelve bars.'),question('Which chords are commonly used in a basic blues sequence?',['I, IV, and V','II, III, and VI','Only I','Only V'],0,'The I, IV, and V chords form the basis of a common blues pattern.'),question('What does AAB mean in a blues verse?',['Three identical lines','A chorus with no verses','A different line every time','A line, its repeat, then a new line'],3,'The first line repeats, followed by a contrasting or answering third line.'),question('Blues developed primarily in which communities?',['Medieval European courts','African American communities','Ancient Roman armies','Arctic research stations'],1,'Blues grew from African American musical traditions and experiences.')]
  },
  maths:{name:'Mathematics',code:'M8.C',icon:'Calculator',source:page(5322),unitSource:page(5607),title:'Numbers, roots & indices',description:'Small steps through some powerful numbers.',topics:['Types of numbers','Rational or irrational?','Roots & powers','BIDMAS','Laws of indices'],
    notes:[['Types of numbers','Integers are whole numbers, including negatives and zero. A rational number can be written as a fraction of two integers with a non-zero denominator.'],['Rational or irrational?','Terminating and recurring decimals are rational. Irrational numbers, such as √2 and π, cannot be expressed as a ratio of two integers.'],['Roots & powers','Squaring means multiplying a number by itself. The principal square root reverses squaring and is non-negative. For example, √81 = 9 and ∛27 = 3.'],['BIDMAS & indices','Calculate brackets, then indices, then multiplication and division from left to right, then addition and subtraction from left to right. For the same base, aᵐ × aⁿ = aᵐ⁺ⁿ.']],
    resources:[resource('Types of Numbers & Rational or Irrational worksheets',page(5607),'Worksheet folder'),resource('Square and Cube Roots · worksheets 1 & 2',page(5607),'Worksheet folder'),resource('BIDMAS & Laws of Indices worksheets',page(5607),'Worksheet folder'),resource('Term 1 Exam Guide & Chapter 1 Revision Pack',page(5607),'Revision folder')],
    questions:[question('Which number is irrational?',['0.25','√2','−3','1/2'],1,'√2 cannot be written as a fraction of two integers.'),question('What is the principal square root of 81?',['8','18','9','40.5'],2,'9 × 9 = 81, so √81 = 9.'),question('Calculate 3 + 4 × 2.',['11','14','10','9'],0,'Multiplication comes first: 4 × 2 = 8, then 3 + 8 = 11.'),question('Simplify 2³ × 2⁴.',['2¹²','4⁷','2¹','2⁷'],3,'When multiplying powers with the same base, add the indices: 3 + 4 = 7.'),question('What is the cube root of 27?',['9','3','6','81'],1,'3 × 3 × 3 = 27, so ∛27 = 3.')]
  },
  computing:{name:'Computing',code:'Co8.B',icon:'Monitor',source:page(5161),unitSource:page(707),title:'Building networks',description:'Explore how devices connect and stay secure.',topics:['What is a network?','LANs & WANs','Network devices','Staying secure','Network review'],
    notes:[['What is a network?','A computer network connects devices so they can exchange data and share resources, such as printers or files.'],['LANs & WANs','A LAN covers a limited area, such as a school building. A WAN connects across much larger areas and can connect multiple LANs.'],['Network devices','A switch connects devices within a network. A router forwards data between networks. A wireless access point lets devices join a network using Wi-Fi.'],['Staying secure','Use unique passwords and multi-factor authentication. Be cautious with unexpected links, keep software updated, and never share your password.']],
    resources:[resource('Network Structure and Security · unit',page(707)),resource('8.1 Worksheet 1',task(9154),'Submitted coursework'),resource('8.1 worksheet 2',task(10063),'Submitted coursework'),resource('8.1 worksheet 3',task(10185),'Submitted coursework')],
    questions:[question('What does a computer network allow devices to do?',['Only charge batteries','Exchange data and share resources','Work without any software','Print without a printer'],1,'Networks let connected devices communicate and share resources.'),question('Which network usually covers one school building?',['The whole internet','A WAN only','A LAN','A satellite orbit'],2,'A local area network covers a relatively small area.'),question('Which device forwards data between networks?',['A router','A keyboard','A monitor','A microphone'],0,'Routers connect networks and forward data between them.'),question('Which is a safer account practice?',['Reuse one password','Share your login','Ignore updates','Use multi-factor authentication'],3,'Multi-factor authentication adds another way to verify your identity.'),question('What does WAN stand for?',['Wireless Access Name','Wide Area Network','Web Address Number','Wired Audio Node'],1,'WAN stands for Wide Area Network.')]
  },
  science:{name:'Science',code:'S8.B',icon:'FlaskConical',source:page(5382),unitSource:page(800),title:'Think like a scientist',description:'Ask questions, test ideas, and follow the evidence.',topics:['Ask a question','Plan an investigation','Choose your variables','Read the evidence','Science check-in'],
    notes:[['Ask a question','A testable scientific question can be investigated through observations or measurements. A prediction describes what you expect to happen.'],['Plan an investigation','Plan what you will change, measure, and keep the same. Repeat measurements and follow your teacher’s laboratory safety instructions.'],['Choose your variables','The independent variable is what you change. The dependent variable is what you measure. Control variables are kept the same to make comparisons fair.'],['Read the evidence','Look for patterns, unusual results, and limits in your data. Support your conclusion with evidence, and explain whether the results support your prediction.']],
    resources:[resource('Grade 8 Science · course overview',page(800)),resource('Science class · kidney & excretory-system model',page(5382)),resource('Science fair',page(4414))],
    questions:[question('What is the independent variable?',['What you measure','What you deliberately change','Every result','A conclusion'],1,'You deliberately change the independent variable.'),question('What is the dependent variable?',['The equipment brand','The safety rules','What you measure','The title'],2,'The dependent variable is the response you measure.'),question('Why keep control variables the same?',['To make the comparison fair','To guarantee your prediction','To avoid collecting data','To change all conditions'],0,'Keeping other conditions constant helps isolate the effect of your change.'),question('What should support a scientific conclusion?',['A guess only','The most popular answer','The title of the experiment','Evidence from the results'],3,'A conclusion should be grounded in the evidence you collected.'),question('Why repeat measurements?',['To hide unusual results','To check consistency and improve reliability','To change the hypothesis every time','To stop using units'],1,'Repeats help you assess how consistent your results are.')]
  },
  english:{name:'English',code:'E8.A',icon:'BookOpen',source:page(5245),unitSource:page(714),title:'A Place Called Home',description:'Explore belonging through language and literature.',topics:['Home & belonging','Finding evidence','Language choices','Build a paragraph','English review'],
    notes:[['Home & belonging','When reading about home, consider how a writer presents belonging, identity, and place. Distinguish what the text says directly from what you infer.'],['Finding evidence','Choose a short, relevant quotation to support your point. Explain how its words support your interpretation.'],['Language choices','Imagery appeals to the senses. A simile compares using “like” or “as”; a metaphor describes something as something else.'],['Build a paragraph','Make a clear point, give evidence, and explain its significance. Link your explanation back to the question rather than only retelling events.']],
    resources:[resource('Unit 1: A Place Called Home',page(714)),resource('Week One · lesson presentation',task(9732),'Lesson materials'),resource('Week 2 · lesson materials',task(10235),'Lesson materials')],
    questions:[question('What makes an interpretation convincing?',['Repeating the title','Relevant evidence and explanation','Only a personal opinion','A longer sentence'],1,'Use details from the text and explain how they support your point.'),question('“The room was like a warm blanket” is a…',['Fact','Rhyme','Simile','Stage direction'],2,'A simile compares things using “like” or “as”.'),question('What does imagery appeal to?',['The senses','Only numbers','A bibliography','Punctuation alone'],0,'Imagery evokes sight, sound, smell, taste, or touch.'),question('What should follow a quotation in an analytical paragraph?',['An unrelated fact','A new title','Nothing','An explanation of its effect'],3,'Explain how the quotation helps answer the question.'),question('Which topic closely connects with belonging?',['Page numbering','Identity','Font size','Alphabetical order'],1,'Identity and belonging explore who people are and where they feel connected.')]
  },
  german:{name:'German',code:'D8.B',icon:'Languages',source:page(5196),unitSource:page(728),title:'Das Herz eines Boxers',description:'Read, discuss, and bring a modern drama to life.',topics:['Ein Drama lesen','Figuren verstehen','Dialog & Wirkung','Redewiedergabe','Deutsch wiederholen'],
    notes:[['Ein Drama lesen','Ein Drama ist für die Aufführung geschrieben. Dialoge und Regieanweisungen zeigen, was Figuren sagen und wie eine Szene gestaltet werden kann.'],['Figuren verstehen','Untersuche, was eine Figur sagt und tut. Begründe Aussagen über ihre Eigenschaften mit passenden Textstellen.'],['Dialog & Wirkung','Wortwahl, Pausen und Sprechweise können Beziehungen und Konflikte deutlich machen. Achte darauf, wie Figuren aufeinander reagieren.'],['Redewiedergabe','Direkte Rede gibt Worte unmittelbar wieder, meist mit Anführungszeichen. Indirekte Rede berichtet über das Gesagte; in formellen Texten wird dafür oft Konjunktiv I verwendet.']],
    resources:[resource('Das Herz eines Boxers · Deutschbuch Kapitel 9',page(728)),resource('Formen der Redewiedergabe',page(5476)),resource('Der Tote im Dorfteich · Sommerlektüre',page(727),'Earlier unit')],
    questions:[question('Wozu dienen Regieanweisungen?',['Zum Rechnen','Sie geben Hinweise zur Aufführung','Sie ersetzen alle Dialoge','Sie nennen nur den Titel'],1,'Regieanweisungen beschreiben zum Beispiel Bewegungen oder Sprechweisen.'),question('Wie begründest du eine Aussage über eine Figur?',['Nur mit einer Vermutung','Mit der Seitenzahl allein','Mit einer passenden Textstelle','Mit der Schriftgröße'],2,'Eine passende Textstelle liefert einen Beleg für deine Deutung.'),question('Was ist direkte Rede?',['Die unmittelbare Wiedergabe von Worten','Eine Inhaltsangabe ohne Zitate','Eine Personenliste','Eine Kapitelüberschrift'],0,'Direkte Rede gibt das Gesagte unmittelbar wieder.'),question('Was kann ein Dialog zeigen?',['Nur Rechtschreibregeln','Nur das Datum','Nur die Seitenzahl','Beziehungen und Konflikte'],3,'Die Reaktionen und Äußerungen der Figuren zeigen ihre Beziehungen.'),question('Welche Form wird häufig in formeller indirekter Rede verwendet?',['Imperativ','Konjunktiv I','Nur Infinitiv','Nur Futur II'],1,'Konjunktiv I kennzeichnet häufig die Wiedergabe fremder Aussagen.')]
  },
  social:{name:'Social Studies',code:'SSt8.B',icon:'Globe2',source:page(5413),unitSource:page(816),title:'People, places & population',description:'Understand the patterns that shape our world.',topics:['Population patterns','Population density','Births & deaths','Population pyramids','Migration'],
    notes:[['Population patterns','Population distribution describes where people live. Physical and human factors can influence whether an area is densely or sparsely populated.'],['Population density','Population density is the number of people per unit of area. Divide the total population by the area, using consistent units.'],['Births & deaths','Natural increase is births minus deaths over a period. Migration also changes population size, so total population change includes both.'],['Population pyramids & migration','A population pyramid displays age and sex structure. Migration is movement to live in another place. Push factors encourage people to leave; pull factors attract them elsewhere.']],
    resources:[resource('Population Patterns & Population Density',page(816)),resource('Measuring Population · Birth and Death',task(10106)),resource('Population Pyramids',task(10109)),resource('Term 1 Exam 1 Revision Guide',task(10243),'Revision guide'),resource('Migration',task(10605)),resource('Refugees Across Time & Case Study Homework',task(10609),'Confirm class deadline')],
    questions:[question('How do you calculate population density?',['Area ÷ population','Population ÷ area','Population × area','Births + deaths'],1,'Divide population by area, such as people per square kilometre.'),question('A town has 10,000 people in 20 km². Its density is…',['200 people/km²','2,000 people/km²','500 people/km²','20 people/km²'],2,'10,000 ÷ 20 = 500 people per square kilometre.'),question('What is natural increase?',['Births minus deaths','Immigration only','Area minus population','Deaths plus emigration'],0,'Natural increase excludes migration and compares births with deaths.'),question('What does a population pyramid show?',['Daily weather','Only a country’s area','Road networks','Age and sex structure'],3,'A population pyramid displays how population is distributed by age and sex.'),question('Which is an example of a pull factor?',['Conflict at home','Better job opportunities elsewhere','A natural disaster at home','Lack of services at home'],1,'A pull factor attracts someone toward a destination.')]
  },
  spanish:{name:'Spanish DELE A1',code:'Sp83.A',icon:'MessageCircle',source:page(5399),unitSource:page(863),title:'¡Vamos a practicar!',description:'A little Spanish, a little more confidence.',topics:['Presentarte','Describir personas','Ser y estar','Rellenar un formulario','Repaso de vocabulario'],
    notes:[['Presentarte','Use “Me llamo…” for your name and “Tengo … años” for your age. “Soy de…” says where you are from.'],['Describir personas','Adjectives generally agree with the person or noun they describe. For example, “alto” and “alta” change with grammatical gender.'],['Ser y estar','Use ser for identity or characteristics: “Soy estudiante.” Use estar for location or a state: “Estoy en clase.” These are useful starting patterns, with more detail to learn later.'],['Rellenar un formulario','Nombre means first name; apellidos means surname(s); fecha de nacimiento means date of birth. Read each field carefully.']],
    resources:[resource('Semana 4 · Descripciones de personas',task(10592)),resource('Week 5 · SER y ESTAR',task(10594)),resource('Assessment 1 · vocabulary and form-filling revision',page(5559),'Revision folder'),resource('DELE escolar · course structure',page(863))],
    questions:[question('How do you say “My name is Anton”?',['Tengo Anton','Me llamo Anton','Estoy Anton','Hay Anton'],1,'“Me llamo…” is used to introduce your name.'),question('Complete: “Yo ___ estudiante.”',['estoy','tengo','soy','hay'],2,'Use ser for identity: “Yo soy estudiante.”'),question('Complete: “El libro ___ en la mesa.”',['está','es','tiene','soy'],0,'Use estar for the location of an object.'),question('What does “fecha de nacimiento” mean?',['Home address','First name','School subject','Date of birth'],3,'“Fecha de nacimiento” is the date you were born.'),question('How do you say “I am thirteen years old”?',['Soy trece años','Tengo trece años','Estoy trece años','Hay trece años'],1,'Spanish uses tener for age: “Tengo trece años.”')]
  },
  drama:{name:'Drama',code:'Dr8.B',icon:'Drama',source:page(5213),unitSource:page(5471),title:'Body as Prop',description:'Turn movement, imagination, and teamwork into theatre.',topics:['Physical storytelling','Shape & space','Working together','A clear tableau','Performance review'],
    notes:[['Physical storytelling','In physical theatre, movement and body shape help communicate meaning. Make your choices clear enough for an audience to interpret.'],['Shape & space','Explore levels, direction, and relationships in space. Change one element at a time and notice how the image changes.'],['Working together','Agree on a shared idea, listen to partners, and rehearse transitions. Stay aware of personal space and follow classroom safety instructions.'],['A clear tableau','A tableau is a still image created by performers. Body position, facial expression, and focus help communicate the scene.']],
    resources:[resource('Body as Prop · unit',page(5471)),resource('Week 1 PPT',task(9768),'Lesson materials'),resource('Week 2 PPT',task(9769),'Lesson materials'),resource('Week 3 PPT',task(10158),'Lesson materials'),resource('Week 4 PPT',task(10407),'Lesson materials')],
    questions:[question('What is a tableau?',['A spoken monologue','A still image created by performers','A costume list','A sound effect'],1,'A tableau is a frozen image that communicates a scene or idea.'),question('Which can communicate meaning without words?',['Only the script','Only a title','Body shape and facial expression','Only a microphone'],2,'Physical choices can tell a story without spoken language.'),question('What does changing levels mean?',['Using different heights','Changing the audience’s seats','Changing the lesson date','Speaking in another language'],0,'Performers can use low, middle, and high body positions.'),question('What helps group physical theatre work well?',['Ignoring partners','Unplanned pushing','Avoiding rehearsal','Shared focus and communication'],3,'A shared idea and clear communication help a group perform safely and coherently.'),question('When creating a physical image, what comes first?',['Speed at any cost','Safety and awareness of others','The loudest voice','A complicated costume'],1,'Work safely and respect the space and comfort of your partners.')]
  },
  art:{name:'Art',code:'Ar8.B',icon:'Palette',source:page(5109),title:'Your art studio',description:'Your class page, materials, and personal reminders.',topics:[],notes:[],questions:[],resources:[resource('G8 Art · class page',page(5109))]},
  pe:{name:'Physical Education',code:'PE8.B',icon:'Activity',source:page(5372),title:'Move, learn, grow',description:'Keep your PE class and reminders in one place.',topics:[],notes:[],questions:[],resources:[resource('G8 Physical Education · class page',page(5372))]},
  advising:{name:'Advising',code:'Ad8.B',icon:'Compass',source:page(5094),title:'Your advising space',description:'Make room for good habits and new goals.',topics:[],notes:[],questions:[],resources:[resource('G8 Advising · class page',page(5094))]},
  homeroom:{name:'Homeroom 8B',code:'Hr8.B',icon:'School',source:page(3486),title:'Hello, 8B',description:'Your home base for class news and plans.',topics:[],notes:[],questions:[],resources:[resource('Homeroom 8B · news and calendar',page(3486))]}
};

export const IMPORTED_HOMEWORK = [
  {id:'school-9464',course:'music',title:'Assessment 1: Mid Unit Quiz',kind:'Assessment',due:'2026-09-22T14:20:00+02:00',source:task(9464),sourceStatus:'Upcoming assessment',details:'Feeling the Blues. Review history and context, backbeat, the 12-bar blues, and lyric structure. Schoolbox says the quiz is not currently available to attempt.',done:false,remindHours:24},
  {id:'school-9467',course:'music',title:'Assessment 2: Listening Recognition',kind:'Assessment',due:'2026-10-27T14:20:00+01:00',source:task(9467),sourceStatus:'No online submission',details:'Recognize the 12-bar blues sequence. This assessment does not accept online submissions; follow your teacher’s instructions.',done:false,remindHours:24},
  {id:'school-9471',course:'music',title:'Blues Lyric Writing',kind:'Assessment',due:'2026-11-17T14:20:00+01:00',source:task(9471),sourceStatus:'Submissions not open',details:'Use the table on the last page of your worksheets to write your own blues lyrics. Follow the instructions given in class and review the rubric on Schoolbox.',done:false,remindHours:48},
  {id:'school-10185',course:'computing',title:'8.1 worksheet 3',kind:'Homework',due:'2026-09-20T18:00:00+02:00',source:task(10185),sourceStatus:'Submitted 18 Sep',details:'A submission is recorded in Schoolbox on 18 September 2026 at 13:40. No new reminder is scheduled for submitted work.',done:true,remindHours:null},
  {id:'school-10063',course:'computing',title:'8.1 worksheet 2',kind:'Homework',due:'2026-09-13T18:00:00+02:00',source:task(10063),sourceStatus:'Submitted 11 Sep',details:'A submission is recorded in Schoolbox on 11 September 2026 at 13:59.',done:true,remindHours:null},
  {id:'school-9154',course:'computing',title:'8.1 Worksheet 1',kind:'Homework',due:'2026-09-06T18:00:00+02:00',source:task(9154),sourceStatus:'Submitted 4 Sep',details:'A submission is recorded in Schoolbox on 4 September 2026 at 14:00.',done:true,remindHours:null},
  {id:'school-10609',course:'social',title:'Refugees Across Time & Case Study Homework',kind:'Check deadline',due:null,portalDate:'2027-07-01T18:00:00+02:00',source:task(10609),sourceStatus:'Teacher completion not verified',details:'The coursework links to a lesson presentation. Schoolbox lists 1 July 2027 at 18:00, the same date used by many unit resources. Confirm the actual homework deadline in class, then set it here.',done:false,remindHours:null}
];
