import React, { useMemo, useState } from 'react';
import { Plus, Search, Pin, Archive, ArchiveRestore, Eye, EyeOff, Download, NotebookPen } from 'lucide-react';
import { COURSES, SUBJECT_ORDER, dayKey } from '../../study.js';
import { notebookMarkdown } from '../../revision.js';
import { useT } from '../../i18n.jsx';
import { Button } from '../UI.jsx';
import { downloadText } from './downloadText.js';
import s from './Revision.module.css';

export default function StudyNotebook({ notes, setNotes, selected, setSelected, onCreate, saveError }) {
  const tr = useT();
  const [query, setQuery] = useState(''), [subject, setSubject] = useState('all'), [archived, setArchived] = useState(false), [recall, setRecall] = useState(false), [answer, setAnswer] = useState(''), [revealed, setRevealed] = useState(false);
  const visible = useMemo(() => notes.filter(note => note.archived === archived && (subject === 'all' || note.subject === subject) && `${note.title} ${note.cue} ${note.notes} ${note.summary}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt.localeCompare(a.updatedAt)), [notes, subject, query, archived]);
  const note = notes.find(n => n.id === selected);
  function choose(id) { setSelected(id); setRecall(false); setAnswer(''); setRevealed(false); }
  function update(changes) { setNotes(list => list.map(n => n.id === selected ? { ...n, ...changes, updatedAt: new Date().toISOString() } : n)); }
  function create() { setQuery(''); setSubject('all'); setArchived(false); setRecall(false); setAnswer(''); setRevealed(false); onCreate(); }
  return <>
    <section className={s.notebookIntro}><div><span className={s.kicker}>{tr('MAKE IT YOUR OWN')}</span><h2>{tr('Ideas worth keeping. In your words.')}</h2><p>{tr('Capture a question, work through the explanation, then write a short summary from memory.')}</p></div><div className={s.rowActions}><Button onClick={create} disabled={notes.length >= 60}><Plus size={17}/>{tr('New study note')}</Button><Button variant="secondary" disabled={!notes.length} onClick={() => downloadText(notebookMarkdown(notes), `aster-notebook-${dayKey()}.md`, 'text/markdown;charset=utf-8')}><Download size={16}/>{tr('Export notebook')}</Button></div></section>
    {notes.length >= 60 && <p role="status">{tr('Notebook limit reached: 60 notes. Edit an existing note or export your notebook.')}</p>}
    <div className={s.notebookLayout}><aside className={s.noteSidebar}><label className={s.search}><Search size={17}/><input placeholder={tr('Search notes…')} aria-label={tr('Search study notes')} value={query} onChange={e => setQuery(e.target.value)}/></label><label className={s.selectLabel}>{tr('Subject')}<select value={subject} onChange={e => setSubject(e.target.value)}><option value="all">{tr('All subjects')}</option>{SUBJECT_ORDER.map(id => <option key={id} value={id}>{tr(COURSES[id].name)}</option>)}</select></label><button className={s.archiveToggle} aria-pressed={archived} onClick={() => setArchived(v => !v)}><Archive size={16}/>{tr(archived ? 'Show active notes' : 'Show archived notes')}</button><p className={s.subtle} role="status">{visible.length} {tr(visible.length===1?'note':'notes')}</p><div className={s.noteList}>{visible.map(n => <button key={n.id} onClick={() => choose(n.id)} aria-pressed={selected === n.id}><span>{n.pinned && <Pin size={12}/>} {tr(COURSES[n.subject].name)}</span><strong>{n.title || tr('Untitled note')}</strong><p>{n.cue || n.notes || tr('Start with one question.')}</p><small>{new Date(n.updatedAt).toLocaleDateString(tr.locale, { day: 'numeric', month: 'short' })}</small></button>)}</div>{!visible.length && <p className={s.subtle}>{tr('No notes match this view.')}</p>}</aside>
    {!note ? <div className={`${s.panel} ${s.empty}`}><NotebookPen size={40}/><h2>{tr('Your thinking belongs here.')}</h2><p>{tr('Create a study note, or save an explanation directly from your review queue.')}</p><Button onClick={create} disabled={notes.length >= 60}><Plus size={16}/>{tr('Create your first note')}</Button></div> : <section className={s.editor} key={note.id}>
      <div className={s.editorTop}><span role="status">{tr(saveError ? 'Not saved — export a copy' : 'Saved in this browser')}</span><div><button aria-label={tr(note.pinned ? 'Unpin note' : 'Pin note')} aria-pressed={note.pinned} onClick={() => update({ pinned: !note.pinned })}><Pin size={17}/></button><button aria-label={tr(note.archived ? 'Restore note' : 'Archive note')} onClick={() => update({ archived: !note.archived })}>{note.archived ? <ArchiveRestore size={17}/> : <Archive size={17}/>}</button><button aria-label={tr('Export this note')} onClick={() => downloadText(notebookMarkdown([note]), `aster-note-${dayKey()}.md`, 'text/markdown;charset=utf-8')}><Download size={17}/></button></div></div>
      {note.archived && <p className={s.archiveNotice}>{tr('This note is archived. You can still edit it or restore it.')}</p>}
      <label className={s.selectLabel}>{tr('Note title')}<input className={s.noteTitle} value={note.title} maxLength={120} placeholder={tr('Give this idea a title…')} onChange={e => update({ title: e.target.value })}/></label>
      <div className={s.noteToolbar}><label className={s.selectLabel}>{tr('Subject')}<select value={note.subject} onChange={e => update({ subject: e.target.value })}>{SUBJECT_ORDER.map(id => <option key={id} value={id}>{tr(COURSES[id].name)}</option>)}</select></label><Button variant="secondary" onClick={() => { setRecall(v => !v); setRevealed(false); setAnswer(''); }}>{recall ? <Eye size={16}/> : <EyeOff size={16}/>}{tr(recall ? 'Return to editing' : 'Test my recall')}</Button></div>
      {recall ? <div className={s.recall}><span className={s.kicker}>{tr('WITHOUT PEEKING')}</span><h3>{note.cue || note.title || tr('Explain this idea in your own words.')}</h3><label>{tr('What do you remember?')}<textarea rows={7} value={answer} maxLength={3500} onChange={e => setAnswer(e.target.value)} placeholder={tr('Write your explanation before revealing the note.')}/></label><Button onClick={() => setRevealed(true)} disabled={!answer.trim() || revealed}>{tr('Reveal & compare')}</Button>{revealed && <div className={s.reveal}><h3>{tr('Your saved explanation')}</h3><p>{note.notes}</p><h4>{tr('In my own words')}</h4><p>{note.summary || tr('Add a summary when you return to editing.')}</p><p className={s.subtle}>{tr('Compare the key ideas. This is self-review, not automatic grading.')}</p><Button variant="secondary" onClick={() => { update({ summary: answer.slice(0, 700) }); setRecall(false); }}>{tr('Save my explanation as the summary')}</Button><small>{tr('Replaces the summary with the first 700 characters of your explanation.')}</small></div>}</div> : <><div className={s.cornell}><label><span>{tr('Recall prompt')}</span><small>{tr('What should future-you be able to explain?')}</small><textarea rows={10} maxLength={700} value={note.cue} onChange={e => update({ cue: e.target.value })} placeholder={tr('One clear question…')}/></label><label><span>{tr('Working notes')}</span><small>{tr('Definitions, examples, steps, or a corrected mistake.')}</small><textarea rows={10} maxLength={3500} value={note.notes} onChange={e => update({ notes: e.target.value })} placeholder={tr('Make the explanation useful to you…')}/></label></div><label className={s.summaryField}><span>{tr('In my own words')}</span><small>{tr('Close the source. Write the central idea in two or three sentences.')}</small><textarea rows={4} maxLength={700} value={note.summary} onChange={e => update({ summary: e.target.value })} placeholder={tr('The key idea is…')}/></label></>}
      <div className={s.editorBottom}><span>{[note.cue, note.notes, note.summary].join(' ').trim().split(/\s+/).filter(Boolean).length} {tr('words')}</span><span>{tr('Notebook structure: prompt · notes · summary')}</span></div>
    </section>}</div>
  </>;
}
