import React, { useState } from 'react';
import { ArrowRight, Target, TrendingUp, CheckCircle2, Sparkles } from 'lucide-react';
import { useApp } from '../../context.jsx';
import { useT } from '../../i18n.jsx';
import { COURSES } from '../../study.js';
import { Button, Progress, ColorIcon } from '../UI.jsx';
import s from './Revision.module.css';

export default function StudyInsights({ analytics }) {
  const tr = useT(), { prefs, setPrefs, startRevision, navigate } = useApp(), [range, setRange] = useState(28);
  const { week, previous, days, subjects, topics, confidence } = analytics;
  const goal = [10, 25, 50, 100].includes(prefs.revisionTarget) ? prefs.revisionTarget : 25;
  const focusGoal = [30, 60, 120, 180, 300].includes(prefs.revisionMinutes) ? prefs.revisionMinutes : 60;
  const chartDays = days.slice(-range), max = Math.max(5, ...chartDays.map(d => d.attempts));
  const improvement = week.accuracy !== null && previous.accuracy !== null ? week.accuracy - previous.accuracy : null;
  const completed = week.total >= goal && week.minutes >= focusGoal;
  return <>
    <section className={s.insightIntro}><div><span className={s.kicker}>{tr('YOUR LAST SEVEN DAYS')}</span><h2>{tr('Your progress, in perspective.')}</h2><p>{tr('Compare with your own earlier work. Every chart begins with your real activity.')}</p></div><TrendingUp size={46}/></section>
    <div className={s.metrics}><div><strong>{week.total}</strong><span>{tr('Answers checked')}</span><small>{previous.total} {tr('in the previous seven days')}</small></div><div><strong>{week.accuracy === null ? '—' : `${week.accuracy}%`}</strong><span>{tr('Practice accuracy')}</span><small>{improvement === null ? tr('Keep practising to build a comparison') : `${improvement > 0 ? '+' : ''}${improvement} ${tr('percentage points vs previous seven days')}`}</small></div><div><strong>{week.minutes}<small> min</small></strong><span>{tr('Focused study')}</span><small>{week.activeDays} {tr('active days out of seven')}</small></div></div>
    <div className={s.insightsGrid}><section className={s.panel}><div className={s.panelHeading}><div><h2>{tr('Your practice rhythm')}</h2><p>{tr('Blue: all answers. Green: correct answers.')}</p></div><select aria-label={tr('Chart range')} value={range} onChange={e => setRange(Number(e.target.value))}><option value={7}>{tr('7 days')}</option><option value={28}>{tr('28 days')}</option></select></div>
      <svg className={s.chart} viewBox="0 0 600 220" role="img" aria-label={tr('Daily answers and correct answers. Exact values are in the table below.')}>
        {[0, .5, 1].map(t => <g key={t}><line x1="35" x2="590" y1={180 - t * 150} y2={180 - t * 150} stroke="currentColor" opacity=".12"/><text x="25" y={184 - t * 150} textAnchor="end" fill="currentColor" fontSize="10">{Math.round(max * t)}</text></g>)}
        {chartDays.map((day, i) => { const width = 550 / chartDays.length, x = 38 + i * width, y = 180 - day.attempts / max * 150; return <g key={day.day}><title>{`${day.day}: ${day.attempts} ${tr(day.attempts===1?'answer':'answers')}, ${day.correct} ${tr('correct')}`}</title><rect x={x} y={y} width={Math.max(3, width - 5)} height={day.attempts / max * 150} rx="3" fill="#5483ed"/><rect x={x + (width - 5) * .22} y={180 - day.correct / max * 150} width={(width - 5) * .56} height={day.correct / max * 150} rx="2" fill="#3eb7a0"/>{(i === 0 || i === chartDays.length - 1 || (chartDays.length === 7 && i % 2 === 0)) && <text x={x + width / 2} y="203" textAnchor="middle" fill="currentColor" fontSize="10">{day.day.slice(5)}</text>}</g>; })}
      </svg>
      {!chartDays.some(d => d.attempts) && <p className={s.subtle}>{tr('No practice answers in this period yet. Your first session will appear here.')}</p>}
      <details className={s.dataTable}><summary>{tr('View chart data')}</summary><table><caption>{tr('Daily practice and saved focus time')}</caption><thead><tr>{['Date', 'Answers', 'Correct', 'Focus minutes'].map(x => <th scope="col" key={x}>{tr(x)}</th>)}</tr></thead><tbody>{chartDays.map(d => <tr key={d.day}><th scope="row">{d.day}</th><td>{d.attempts}</td><td>{d.correct}</td><td>{d.minutes}</td></tr>)}</tbody></table></details>
    </section><section className={s.panel}><Target size={24}/><h2>{tr('Make room for progress.')}</h2><p>{tr('Flexible targets for the last seven days. Adjust them to fit your week.')}</p><div className={s.goal}><label>{tr('Question target')}<select value={goal} onChange={e => setPrefs(p => ({ ...p, revisionTarget: Number(e.target.value) }))}>{[10, 25, 50, 100].map(n => <option key={n} value={n}>{n}</option>)}</select></label><Progress value={100 * week.total / goal} label={tr('Question target progress')}/><span>{week.total} / {goal}</span></div><div className={s.goal}><label>{tr('Focus target (minutes)')}<select value={focusGoal} onChange={e => setPrefs(p => ({ ...p, revisionMinutes: Number(e.target.value) }))}>{[30, 60, 120, 180, 300].map(n => <option key={n} value={n}>{n}</option>)}</select></label><Progress value={100 * week.minutes / focusGoal} label={tr('Focus target progress')}/><span>{week.minutes} / {focusGoal} min</span></div><p className={s.goalMessage}>{completed ? <CheckCircle2 size={18}/> : <Sparkles size={18}/>} {tr(completed ? 'Targets met. Make room for a break.' : 'A small session counts. Rest days do too.')}</p><Button variant="secondary" onClick={() => navigate('focus')}>{tr('Open focus room')}<ArrowRight size={16}/></Button></section></div>
    <section className={s.panel}><div className={s.panelHeading}><div><h2>{tr('Where to put your next ten minutes')}</h2><p>{tr('Topics with missed, hinted, or low-confidence answers in your latest checks.')}</p></div></div>{!topics.length ? <p>{tr('No topics flagged yet. Practise a subject to find your next step.')}</p> : <div className={s.topicGrid}>{topics.slice(0, 6).map(topic => <button className={s.topic} key={topic.id} onClick={() => startRevision(topic.subject, topic.questionIds.slice(0, 10))}><ColorIcon id={topic.subject} size={18}/><strong>{tr(topic.topic)}</strong><small>{tr(COURSES[topic.subject].name)}</small><span>{topic.support} / {topic.seen} {tr('checked ideas need support')}<ArrowRight size={16}/></span></button>)}</div>}</section>
    <div className={s.insightsGrid}><section className={s.panel}><h2>{tr('Confidence meets accuracy')}</h2><p>{tr('Answers from the last 28 days, grouped by how sure you felt.')}</p><div className={s.confidence}>{confidence.map(c => <div key={c.level}><div><strong>{tr(['', 'Unsure', 'Fairly sure', 'Very confident'][c.level])}</strong><span>{c.correct} / {c.total} {tr('correct')}</span></div><Progress value={c.total ? 100 * c.correct / c.total : 0} label={tr(['', 'Unsure', 'Fairly sure', 'Very confident'][c.level])}/></div>)}</div><p className={s.subtle}>{tr('Correct but unsure? Explain it once more. Confident but incorrect? Check the method before trying again.')}</p></section><section className={s.panel}><h2>{tr('28 days of showing up')}</h2><p>{tr('A filled tile means practice or saved focus time. Empty days are simply days without recorded activity.')}</p><div className={s.heatmap}>{days.map(day => <div key={day.day} data-level={day.attempts + day.minutes === 0 ? 0 : day.attempts >= 10 || day.minutes >= 25 ? 2 : 1} title={`${day.day}: ${day.attempts} ${tr(day.attempts===1?'answer':'answers')}, ${day.minutes} min`} aria-label={`${day.day}: ${day.attempts} ${tr(day.attempts===1?'answer':'answers')}, ${day.minutes} min`}><span>{Number(day.day.slice(-2))}</span></div>)}</div><small className={s.subtle}>{days[0].day} → {days.at(-1).day} · Europe/Berlin</small></section></div>
    <section className={s.panel}><h2>{tr('Your subject overview')}</h2><div className={s.subjects}>{subjects.map(item => <button key={item.subject} onClick={() => navigate(`subjects/${item.subject}`)}><ColorIcon id={item.subject} size={19}/><div><strong>{tr(COURSES[item.subject].name)}</strong><small>{item.seen} / {item.bank} {tr('questions practised')}</small></div><span>{item.accuracy === null ? '—' : `${item.accuracy}%`}<small>{tr('accuracy')}</small></span></button>)}</div></section>
    <p className={s.footnote}>{tr('Answer charts use up to 500 saved attempts; focus charts use saved sessions. Question coverage uses the separate review schedule. These are different measures, not a complete syllabus assessment.')}</p>
  </>;
}
